wibble: wibble::commandline::BoolOption Class Reference
wibble::commandline::BoolOption Class Reference
Boolean option.
#include <options.h>
Public Member Functions
bool boolValue () const
std::string stringValue () const
Protected Member Functions
BoolOption (const std::string &name)
BoolOption (const std::string &name, char shortName, const std::string &longName, const std::string &usage=std::string(), const std::string &description=std::string())
virtual ArgList::iterator parse (ArgList &, ArgList::iterator begin)
Parse the next commandline parameter after the short form of the command has been found.
virtual bool parse (const std::string &)
Parse the commandline parameter of a long commandline switch.
virtual void parse_noarg ()
Notify that the option is present in the command line, but has no arguments.
Friends
class OptionGroup
class Engine
Detailed Description
Boolean option.
Constructor & Destructor Documentation
wibble::commandline::BoolOption::BoolOption (const std::string & name) [inline, protected]
wibble::commandline::BoolOption::BoolOption (const std::string & name, char shortName, const std::string & longName, const std::string & usage = std::string(), const std::string & description = std::string()) [inline, protected]
Member Function Documentation
bool wibble::commandline::BoolOption::boolValue () const [inline]
Referenced by TestCommandlineEngine::clusteredShortOpts(), TestCommandlineEngine::commandsWithoutCommand(), TestCommandlineEngine::commandsWithOverlappingArgs(), TestCommandlineEngine::commandWithArg(), TestCommandlineEngine::creationShortcuts(), TestCommandlineEngine::longOptsWithArgs(), TestCommandlineEngine::longOptsWithDashes(), TestCommandlineEngine::noSwitchesAfterFirstArg(), TestCommandlineEngine::optsAndArgs(), TestCommandlineEngine::optsOnly(), and withCommands().
virtual ArgList::iterator wibble::commandline::BoolOption::parse (ArgList & list, ArgList::iterator begin) [inline, protected, virtual]
Parse the next commandline parameter after the short form of the command has been found.
It may or may not remove the parameter from the list, depending on if the option wants a value or not.
Signal that the option has been found, with the given argument (or 0 if no argument).
Returns:
true if it used the argument, else false
Implements wibble::commandline::Option.
References wibble::list::begin(), and parse_noarg().
virtual bool wibble::commandline::BoolOption::parse (const std::string & param) [inline, protected, virtual]
Parse the commandline parameter of a long commandline switch.
Returns:
true if the parameter has been used
Implements wibble::commandline::Option.
References parse_noarg().
virtual void wibble::commandline::BoolOption::parse_noarg () [inline, protected, virtual]
Notify that the option is present in the command line, but has no arguments.
Implements wibble::commandline::Option.
References wibble::commandline::Option::m_isset.
Referenced by parse().
std::string wibble::commandline::BoolOption::stringValue () const [inline]
Friends And Related Function Documentation
friend class Engine [friend]
Reimplemented from wibble::commandline::Option.
friend class OptionGroup [friend]
Reimplemented from wibble::commandline::Option.
The documentation for this class was generated from the following file:
options.h