wibble: wibble::commandline::StandardParserWithMandatoryCommand Class Reference
wibble::commandline::StandardParserWithMandatoryCommand Class Reference
Parser for commandline arguments, with builting help functions and manpage generation, and requiring a mandatory command.
#include <parser.h>
Public Member Functions
StandardParserWithMandatoryCommand (const std::string &appname, const std::string &version, int section, const std::string &author)
bool parse (int argc, const char *argv[])
Parse the commandline.
Public Attributes
Engine * helpCommand
Detailed Description
Parser for commandline arguments, with builting help functions and manpage generation, and requiring a mandatory command.
Constructor & Destructor Documentation
wibble::commandline::StandardParserWithMandatoryCommand::StandardParserWithMandatoryCommand (const std::string & appname, const std::string & version, int section, const std::string & author) [inline]
References wibble::commandline::Engine::addEngine(), and helpCommand.
Member Function Documentation
bool wibble::commandline::StandardParserWithMandatoryCommand::parse (int argc, const char * argv[])
Parse the commandline.
Returns:
true if it also took care of performing the action requested by the user, or false if the caller should do it instead.
Reimplemented from wibble::commandline::StandardParserWithManpage.
References wibble::commandline::Help::outputHelp().
Referenced by withCommands().
Member Data Documentation
Engine* wibble::commandline::StandardParserWithMandatoryCommand::helpCommand
Referenced by StandardParserWithMandatoryCommand().
The documentation for this class was generated from the following files:
parser.h
parser.cpp