wibble: wibble::Singleton< T > Class Template Reference
wibble::Singleton< T > Class Template Reference
#include <singleton.h>
Classes
class const_iterator
class iterator
Public Types
typedef T value_type
Public Member Functions
Singleton (const T &value)
bool empty () const
size_t size () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Protected Attributes
T value
template<typename T>
class wibble::Singleton< T >
Member Typedef Documentation
template<typename T> typedef T wibble::Singleton< T >::value_type
Constructor & Destructor Documentation
template<typename T> wibble::Singleton< T >::Singleton (const T & value) [inline, explicit]
Member Function Documentation
template<typename T> iterator wibble::Singleton< T >::begin () [inline]
References wibble::iterator(), and wibble::Singleton< T >::value.
Referenced by wibble::operators::operator-(), wibble::operators::operator-=(), and wibble::operators::operator|().
template<typename T> const_iterator wibble::Singleton< T >::begin () const [inline]
References wibble::Singleton< T >::value.
template<typename T> bool wibble::Singleton< T >::empty () const [inline]
template<typename T> iterator wibble::Singleton< T >::end () [inline]
References wibble::iterator().
template<typename T> const_iterator wibble::Singleton< T >::end () const [inline]
template<typename T> size_t wibble::Singleton< T >::size () const [inline]
Member Data Documentation
template<typename T> T wibble::Singleton< T >::value [protected]
Referenced by wibble::Singleton< T >::begin().
The documentation for this class was generated from the following file:
singleton.h