wibble: wibble::commandline::Help Class Reference
wibble::commandline::Help Class Reference
#include <doc.h>
Public Member Functions
Help (const std::string &app, const std::string &ver)
void outputVersion (std::ostream &out)
void outputHelp (std::ostream &out, const Engine &cp)
Protected Member Functions
void outputOptions (std::ostream &out, HelpWriter &writer, const Engine &cp)
Constructor & Destructor Documentation
wibble::commandline::Help::Help (const std::string & app, const std::string & ver) [inline]
Member Function Documentation
void wibble::commandline::Help::outputHelp (std::ostream & out, const Engine & cp)
References wibble::commandline::Engine::aliases, wibble::commandline::Engine::commands(), wibble::commandline::Engine::description, wibble::commandline::Engine::hasOptions(), wibble::commandline::Engine::primaryAlias, and wibble::commandline::Engine::usage.
Referenced by wibble::commandline::StandardParser::outputHelp(), and wibble::commandline::StandardParserWithMandatoryCommand::parse().
void wibble::commandline::Help::outputOptions (std::ostream & out, HelpWriter & writer, const Engine & cp) [protected]
References wibble::commandline::Engine::groups(), and wibble::commandline::Engine::options().
void wibble::commandline::Help::outputVersion (std::ostream & out)
Referenced by wibble::commandline::StandardParser::parse().
The documentation for this class was generated from the following files:
doc.h
doc.cpp