wibble: wibble::commandline::StandardParserWithManpage Class Reference
wibble::commandline::StandardParserWithManpage Class Reference
Parser for commandline arguments, with builting help functions and manpage generation.
#include <parser.h>
Public Member Functions
StandardParserWithManpage (const std::string &appname, const std::string &version, int section, const std::string &author)
bool parse (int argc, const char *argv[])
Parse the commandline.
Public Attributes
StringOption * manpage
Protected Attributes
int m_section
std::string m_author
Detailed Description
Parser for commandline arguments, with builting help functions and manpage generation.
Constructor & Destructor Documentation
wibble::commandline::StandardParserWithManpage::StandardParserWithManpage (const std::string & appname, const std::string & version, int section, const std::string & author) [inline]
References wibble::commandline::OptionGroup::add(), wibble::commandline::StandardParser::helpGroup, manpage, and wibble::commandline::Engine::name().
Member Function Documentation
bool wibble::commandline::StandardParserWithManpage::parse (int argc, const char * argv[])
Parse the commandline.
Returns:
true if it also took care of performing the action requested by the user, or false if the caller should do it instead.
Reimplemented from wibble::commandline::StandardParser.
Reimplemented in wibble::commandline::StandardParserWithMandatoryCommand.
References wibble::commandline::Manpage::output(), and wibble::commandline::Manpage::readHooks().
Member Data Documentation
std::string wibble::commandline::StandardParserWithManpage::m_author [protected]
int wibble::commandline::StandardParserWithManpage::m_section [protected]
StringOption* wibble::commandline::StandardParserWithManpage::manpage
Referenced by StandardParserWithManpage(), and withCommands().
The documentation for this class was generated from the following files:
parser.h
parser.cpp