wibble: wibble::commandline::ArgList Class Reference
wibble::commandline::ArgList Class Reference
#include <core.h>
Public Member Functions
iterator & eraseAndAdvance (iterator &i)
Static Public Member Functions
static bool isSwitch (const char *str)
static bool isSwitch (const std::string &str)
static bool isSwitch (const const_iterator &iter)
static bool isSwitch (const iterator &iter)
Member Function Documentation
iterator& wibble::commandline::ArgList::eraseAndAdvance (iterator & i) [inline]
References wibble::list::end(), and wibble::iterator().
Referenced by TestCommandlineCore::eraseAndAdvance(), wibble::commandline::SingleOption< T >::parse(), wibble::commandline::VectorOption< T >::parse(), and wibble::commandline::Engine::parseFirstIfKnown().
bool wibble::commandline::ArgList::isSwitch (const char * str) [static]
Referenced by TestCommandlineCore::isSwitch(), isSwitch(), wibble::commandline::Engine::parse(), and wibble::commandline::Engine::parseKnownSwitches().
bool wibble::commandline::ArgList::isSwitch (const std::string & str) [static]
bool wibble::commandline::ArgList::isSwitch (const const_iterator & iter) [static]
References isSwitch().
bool wibble::commandline::ArgList::isSwitch (const iterator & iter) [static]
References isSwitch().
The documentation for this class was generated from the following files:
core.h
core.cpp