wibble: wibble::exception::Context Class Reference
wibble::exception::Context Class Reference
Store context information for an exception.
#include <exception.h>
Public Member Functions
Context () throw ()
Context (const std::string &context) throw ()
void addContext (const std::string &c) throw ()
std::string formatContext () const throw ()
const std::vector< std::string > & context () const throw ()
Protected Attributes
std::vector< std::string > m_context
Detailed Description
Store context information for an exception.
Constructor & Destructor Documentation
wibble::exception::Context::Context () throw () [inline]
References wibble::exception::AddContext::copyContext(), and m_context.
wibble::exception::Context::Context (const std::string & context) throw () [inline]
References addContext(), context(), wibble::exception::AddContext::copyContext(), and m_context.
Member Function Documentation
void wibble::exception::Context::addContext (const std::string & c) throw () [inline]
References m_context.
Referenced by Context().
const std::vector<std::string>& wibble::exception::Context::context () const throw () [inline]
References m_context.
Referenced by Context().
std::string wibble::exception::Context::formatContext () const throw () [inline]
References m_context.
Referenced by TestException::addContext(), and wibble::exception::Generic::fullInfo().
Member Data Documentation
std::vector<std::string> wibble::exception::Context::m_context [protected]
Referenced by addContext(), Context(), context(), and formatContext().
The documentation for this class was generated from the following file:
exception.h