wibble: wibble::commandline::StandardParser Class Reference
wibble::commandline::StandardParser Class Reference
Parser for commandline arguments, with builting help functions.
#include <parser.h>
Public Member Functions
StandardParser (const std::string &appname, const std::string &version)
void outputHelp (std::ostream &out)
bool parse (int argc, const char *argv[])
Parse the commandline.
Public Attributes
OptionGroup * helpGroup
BoolOption * help
BoolOption * version
Protected Attributes
std::string m_version
Detailed Description
Parser for commandline arguments, with builting help functions.
Constructor & Destructor Documentation
wibble::commandline::StandardParser::StandardParser (const std::string & appname, const std::string & version) [inline]
References wibble::commandline::OptionGroup::add(), wibble::commandline::Option::addAlias(), wibble::commandline::Engine::addGroup(), help, and helpGroup.
Member Function Documentation
void wibble::commandline::StandardParser::outputHelp (std::ostream & out)
References wibble::commandline::Help::outputHelp().
Referenced by withCommands().
bool wibble::commandline::StandardParser::parse (int argc, const char * argv[])
Parse the commandline.
Returns:
true if it also took care of performing the action requested by the user, or false if the caller should do it instead.
Reimplemented from wibble::commandline::Parser.
Reimplemented in wibble::commandline::StandardParserWithMandatoryCommand, and wibble::commandline::StandardParserWithManpage.
References wibble::commandline::Help::outputVersion().
Member Data Documentation
BoolOption* wibble::commandline::StandardParser::help
Referenced by StandardParser(), and withCommands().
OptionGroup* wibble::commandline::StandardParser::helpGroup
Referenced by StandardParser(), and wibble::commandline::StandardParserWithManpage::StandardParserWithManpage().
std::string wibble::commandline::StandardParser::m_version [protected]
BoolOption* wibble::commandline::StandardParser::version
Referenced by withCommands().
The documentation for this class was generated from the following files:
parser.h
parser.cpp