wibble: wibble::sys::fs::Directory Class Reference
wibble::sys::fs::Directory Class Reference
Nicely wrap access to directories.
#include <fs.h>
Classes
class const_iterator
Public Member Functions
Directory (const std::string &path)
const std::string & path () const
Pathname of the directory.
bool valid ()
Check that the directory exists and is a directory.
const_iterator begin ()
Begin iterator.
const_iterator end () const
End iterator.
bool isdir (const const_iterator &i) const
Detailed Description
Nicely wrap access to directories.
Constructor & Destructor Documentation
wibble::sys::fs::Directory::Directory (const std::string & path) [inline]
Member Function Documentation
const_iterator wibble::sys::fs::Directory::begin ()
Begin iterator.
Referenced by TestFs::directoryIterate(), and wibble::sys::fs::rmtree().
const_iterator wibble::sys::fs::Directory::end () const
End iterator.
Referenced by TestFs::directoryIterate(), and wibble::sys::fs::rmtree().
bool wibble::sys::fs::Directory::isdir (const const_iterator & i) const
Returns:
true if i points to a directory, else false
References wibble::str::joinpath(), and wibble::sys::fs::stat().
Referenced by wibble::sys::fs::rmtree().
const std::string& wibble::sys::fs::Directory::path () const [inline]
Pathname of the directory.
bool wibble::sys::fs::Directory::valid ()
Check that the directory exists and is a directory.
Referenced by TestFs::invalidDirectories().
The documentation for this class was generated from the following files:
fs.h
fs.cpp