wibble: wibble::tests::Location Class Reference
wibble::tests::Location Class Reference
#include <tests.h>
Public Member Functions
Location (const std::string &file, int line, const std::string &str)
Location (const Location &loc, const std::string &testfile, int testline, const std::string &str)
std::string locstr () const
std::string msg (const std::string m) const
Constructor & Destructor Documentation
wibble::tests::Location::Location (const std::string & file, int line, const std::string & str) [inline]
wibble::tests::Location::Location (const Location & loc, const std::string & testfile, int testline, const std::string & str) [inline]
Member Function Documentation
std::string Location::locstr () const
Referenced by wibble::tests::impl_ensure(), and msg().
std::string Location::msg (const std::string m) const
References locstr().
Referenced by wibble::tests::impl_ensure_equals(), and wibble::tests::impl_ensure_similar().
The documentation for this class was generated from the following files:
tests.h
tests.cpp