wibble: wibble::tests Namespace Reference
wibble::tests Namespace Reference
Classes
class Location
Functions
void impl_ensure (const Location &loc, bool res)
template<class Actual , class Expected >
void impl_ensure_equals (const Location &loc, const Actual &actual, const Expected &expected)
template<class Actual , class Expected , class Precision >
void impl_ensure_similar (const Location &loc, const Actual &actual, const Expected &expected, const Precision &precision)
Function Documentation
void wibble::tests::impl_ensure (const Location & loc, bool res)
References wibble::tests::Location::locstr().
template<class Actual , class Expected > void wibble::tests::impl_ensure_equals (const Location & loc, const Actual & actual, const Expected & expected)
References wibble::tests::Location::msg().
template<class Actual , class Expected , class Precision > void wibble::tests::impl_ensure_similar (const Location & loc, const Actual & actual, const Expected & expected, const Precision & precision)
References wibble::tests::Location::msg().