wibble: wibble::grcal::dtime Namespace Reference
wibble::grcal::dtime Namespace Reference
Functions that work with int[3] time of day values.
Functions
void lowerbound (const int *src, int *dst)
Make a copy of the time, filling in missing values with the lowest possible value they can have.
void lowerbound (int *val)
Fill in the missing values of a time of day with the lowest possible value they can have.
int lowerbound_sec (const int *src)
Convert a time of day in second, filling the missing values with the lowest possible value they can have.
void upperbound (const int *src, int *dst)
Make a copy of the time, filling in missing values with the highest possible value they can have.
void upperbound (int *val)
Fill in the missing values of a time of day with the highest possible value they can have.
int upperbound_sec (const int *src)
Convert a time of day in second, filling the missing values with the highest possible value they can have.
int duration (const int *begin, const int *end)
Give the duration in seconds of the interval between the end of begin and the beginning of end.
std::string tostring (const int *val)
Format a time of day to a string.
std::string tostring (int val)
Format a time of day expressed in seconds to a string.
Detailed Description
Functions that work with int[3] time of day values.
Function Documentation
int wibble::grcal::dtime::duration (const int * begin, const int * end)
Give the duration in seconds of the interval between the end of begin and the beginning of end.
The result can be negative if end is an earlier time than begin.
References lowerbound_sec(), and upperbound_sec().
void wibble::grcal::dtime::lowerbound (const int * src, int * dst)
Make a copy of the time, filling in missing values with the lowest possible value they can have.
void wibble::grcal::dtime::lowerbound (int * val)
Fill in the missing values of a time of day with the lowest possible value they can have.
int wibble::grcal::dtime::lowerbound_sec (const int * src)
Convert a time of day in second, filling the missing values with the lowest possible value they can have.
Referenced by duration().
std::string wibble::grcal::dtime::tostring (const int * val)
Format a time of day to a string.
std::string wibble::grcal::dtime::tostring (int val)
Format a time of day expressed in seconds to a string.
void wibble::grcal::dtime::upperbound (const int * src, int * dst)
Make a copy of the time, filling in missing values with the highest possible value they can have.
void wibble::grcal::dtime::upperbound (int * val)
Fill in the missing values of a time of day with the highest possible value they can have.
int wibble::grcal::dtime::upperbound_sec (const int * src)
Convert a time of day in second, filling the missing values with the highest possible value they can have.
Referenced by duration().