wibble: wibble Namespace Reference
wibble Namespace Reference
Namespaces
namespace commandline
namespace exception
namespace grcal
namespace list
namespace log
namespace mixin
namespace net
namespace operators
namespace str
namespace stream
namespace sys
namespace tests
namespace text
Classes
struct ReturnType
struct ReturnType< void >
struct SanitizeReturn
struct SanitizeReturn< F, void >
struct IsZero
struct IsZero< 0 >
struct IsPolymorphic
struct SanitizeResultType
struct Baseless
struct VirtualBase
struct MorphInterface
An interface implemented by all morph classes.
struct MorphAllocator
custom allocator for morph classes
struct MorphBase
struct Morph
class AmorphPadder
class AmorphPadder< 0 >
struct Amorph
struct IsType
struct ConsumerInterface
struct ConsumerMorph
struct ConsumerMixin
struct Consumer
struct ConsumerFromIterator
class Empty
struct Error
struct Fallback
struct IteratorTraits
struct IteratorTraits< T, typename std::set< T >::iterator >
struct IteratorTraits< T, typename std::multiset< T >::iterator >
struct IteratorInterface
struct IteratorProxy
struct IteratorMorph
struct IteratorMixin
struct Iterator
struct StlIterator
struct Maybe
struct Maybe< void >
struct RangeIterator
struct RangeMixin
struct RangeInterface
struct RangeMorph
struct Range
struct IteratorRange
struct CastedRange
struct IntersectionRange
struct FilteredRange
struct UniqueRange
struct TransformedRange
struct GeneratedRange
class Regexp
class ERegexp
class Tokenizer
class Splitter
Split a string using a regular expression to match the token separators.
struct Unit
struct TTrue
struct TFalse
struct TSame
struct TSame< A, A >
struct TAndC
struct TAndC< true, true, true, true, true >
struct TAnd
struct TOrC
struct TOrC< false, false, false, false, false >
struct TOr
struct TNotC
struct TNot
struct TImplyC
struct TImply
struct EnableIfC
struct EnableIfC< true, Type >
struct EnableIf
struct TPair
struct Preferred
struct NotPreferred
class Singleton
Typedefs
typedef bool SortabilityTag
Functions
template<typename T , typename X >
X::template Convert< T >::type & downcast (const X &a)
template<typename T , typename X >
T & downcast (X *v)
template<typename T >
T::WrappedType & unwrap (const T &x)
template<typename T >
T & unwrap (T &x)
template<typename R >
Consumer< typename
R::ConsumedType > consumerMorph (R r)
template<typename Out >
Consumer< typename
Out::container_type::value_type > consumer (Out out)
template<typename T >
IsType< Consumer< typename
T::value_type >, typename
T::iterator >::T consumer (T &c)
template<typename T >
Consumer< T > consumer (const ConsumerInterface< T > &t)
template<typename T , typename I >
IteratorTraits< T, I >::Unsorted isSortedT (I, I)
template<typename I >
Iterator< typename I::value_type > iterator (I i)
template<typename T , typename C >
Range< T > castedRange (C r)
template<typename T , typename C >
Range< T > upcastRange (C r)
template<typename In >
Range< typename In::value_type > range (In b, In e)
template<typename C >
Range< typename
C::iterator::value_type > range (C &c)
template<typename R >
IntersectionRange< typename
R::ElementType > intersectionRange (R r1, R r2)
template<typename R , typename Pred >
FilteredRange< R, Pred > filteredRange (R r, Pred p)
template<typename R >
UniqueRange< typename
R::ElementType > uniqueRange (R r1)
template<typename Trans >
TransformedRange< Trans > transformedRange (Range< typename Trans::argument_type > r, Trans t)
template<typename T , typename A , typename E >
GeneratedRange< T, A, E > generatedRange (T t, A a, E e)
template<typename T >
Singleton< T > singleton (const T &value)
Typedef Documentation
typedef bool wibble::SortabilityTag
Function Documentation
template<typename T , typename C > Range< T > wibble::castedRange (C r)
template<typename Out > Consumer< typename Out::container_type::value_type > wibble::consumer (Out out)
References consumerMorph().
Referenced by consumer().
template<typename T > IsType< Consumer< typename T::value_type >, typename T::iterator >::T wibble::consumer (T & c)
References consumer().
template<typename T > Consumer< T > wibble::consumer (const ConsumerInterface< T > & t)
template<typename R > Consumer< typename R::ConsumedType > wibble::consumerMorph (R r)
Referenced by consumer().
template<typename T , typename X > T& wibble::downcast (X * v)
template<typename T , typename X > X::template Convert<T>::type& wibble::downcast (const X & a)
template<typename R , typename Pred > FilteredRange< R, Pred > wibble::filteredRange (R r, Pred p)
template<typename T , typename A , typename E > GeneratedRange< T, A, E > wibble::generatedRange (T t, A a, E e)
template<typename R > IntersectionRange< typename R::ElementType > wibble::intersectionRange (R r1, R r2)
template<typename T , typename I > IteratorTraits< T, I >::Sorted wibble::isSortedT (I , I)
template<typename I > Iterator< typename I::value_type > wibble::iterator (I i)
Referenced by wibble::commandline::Engine::add(), wibble::net::http::Params::add(), wibble::commandline::Engine::addWithoutAna(), wibble::Empty< T >::begin(), wibble::Singleton< T >::begin(), TestCommandlineEngine::clusteredShortOpts(), TestCommandlineEngine::commandsWithoutCommand(), TestCommandlineEngine::commandsWithOverlappingArgs(), TestCommandlineEngine::commandWithArg(), TestCommandlineEngine::creationShortcuts(), wibble::Empty< T >::end(), wibble::Singleton< T >::end(), TestCommandlineCore::eraseAndAdvance(), wibble::commandline::ArgList::eraseAndAdvance(), wibble::net::http::Params::field(), wibble::net::http::Params::file_field(), TestCommandlineEngine::longOptsWithArgs(), TestCommandlineEngine::longOptsWithDashes(), TestCommandlineEngine::noSwitchesAfterFirstArg(), wibble::net::http::Params::obtain_field(), wibble::net::http::Params::obtain_file_field(), wibble::operators::operator&=(), wibble::operators::operator-=(), TestCommandlineEngine::optsAndArgs(), TestCommandlineEngine::optsOnly(), wibble::commandline::Engine::parse(), wibble::commandline::Engine::parseFirstIfKnown(), wibble::commandline::Engine::parseKnownSwitches(), wibble::net::http::FileParam::FileInfo::read(), wibble::net::mime::Reader::read_headers(), tut::test_runner::register_group(), wibble::log::Tee::send(), and wibble::net::http::Params::~Params().
template<typename In > Range< typename In::value_type > wibble::range (In b, In e)
Referenced by range().
template<typename C > Range< typename C::iterator::value_type > wibble::range (C & c)
References range().
template<typename T > Singleton<T> wibble::singleton (const T & value)
template<typename Trans > TransformedRange< Trans > wibble::transformedRange (Range< typename Trans::argument_type > r, Trans t)
template<typename R > UniqueRange< typename R::ElementType > wibble::uniqueRange (R r1)
template<typename T > T::WrappedType& wibble::unwrap (const T & x)
template<typename T > T& wibble::unwrap (T & x)
template<typename T , typename C > Range< T > wibble::upcastRange (C r)