wibble: wibble::list::Sorted< List >::SharedPtr Struct Reference
wibble::list::Sorted< List >::SharedPtr Struct Reference
#include <list.h>
Public Member Functions
SharedPtr (bool a=false)
SharedPtr (const SharedPtr &o)
SharedPtr & operator= (const SharedPtr &o)
operator bool ()
Vec & operator* ()
Vec * operator-> ()
~SharedPtr ()
Public Attributes
SharedVec * vec
template<typename List>
struct wibble::list::Sorted< List >::SharedPtr
Constructor & Destructor Documentation
template<typename List > wibble::list::Sorted< List >::SharedPtr::SharedPtr (bool a = false) [inline]
References wibble::list::Sorted< List >::SharedPtr::vec.
template<typename List > wibble::list::Sorted< List >::SharedPtr::SharedPtr (const SharedPtr & o) [inline]
References wibble::list::Sorted< List >::SharedVec::_ref(), and wibble::list::Sorted< List >::SharedPtr::vec.
template<typename List > wibble::list::Sorted< List >::SharedPtr::~SharedPtr () [inline]
References wibble::list::Sorted< List >::SharedVec::_deref(), wibble::list::Sorted< List >::SharedVec::refs, and wibble::list::Sorted< List >::SharedPtr::vec.
Member Function Documentation
template<typename List > wibble::list::Sorted< List >::SharedPtr::operator bool () [inline]
References wibble::list::Sorted< List >::SharedPtr::vec.
template<typename List > Vec& wibble::list::Sorted< List >::SharedPtr::operator* () [inline]
References wibble::list::Sorted< List >::SharedVec::vec, and wibble::list::Sorted< List >::SharedPtr::vec.
template<typename List > Vec* wibble::list::Sorted< List >::SharedPtr::operator-> () [inline]
References wibble::list::Sorted< List >::SharedVec::vec, and wibble::list::Sorted< List >::SharedPtr::vec.
template<typename List > SharedPtr& wibble::list::Sorted< List >::SharedPtr::operator= (const SharedPtr & o) [inline]
References wibble::list::Sorted< List >::SharedVec::_ref(), and wibble::list::Sorted< List >::SharedPtr::vec.
Member Data Documentation
template<typename List > SharedVec* wibble::list::Sorted< List >::SharedPtr::vec
Referenced by wibble::list::Sorted< List >::SharedPtr::operator bool(), wibble::list::Sorted< List >::SharedPtr::operator*(), wibble::list::Sorted< List >::SharedPtr::operator->(), wibble::list::Sorted< List >::SharedPtr::operator=(), wibble::list::Sorted< List >::SharedPtr::SharedPtr(), and wibble::list::Sorted< List >::SharedPtr::~SharedPtr().
The documentation for this struct was generated from the following file:
list.h