wibble: wibble::ConsumerMorph< T, W > Struct Template Reference
wibble::ConsumerMorph< T, W > Struct Template Reference
#include <consumer.h>
Public Member Functions
ConsumerMorph ()
ConsumerMorph (const W &w)
virtual void consume (const T &a)
virtual void consume (Range< T > s)
template<typename T, typename W>
struct wibble::ConsumerMorph< T, W >
Constructor & Destructor Documentation
template<typename T , typename W > wibble::ConsumerMorph< T, W >::ConsumerMorph () [inline]
template<typename T , typename W > wibble::ConsumerMorph< T, W >::ConsumerMorph (const W & w) [inline]
Member Function Documentation
template<typename T , typename W > virtual void wibble::ConsumerMorph< T, W >::consume (const T & a) [inline, virtual]
Implements wibble::ConsumerInterface< T >.
References wibble::Morph< ConsumerMorph< T, W >, W, ConsumerInterface< T > >::wrapped().
Referenced by wibble::ConsumerMorph< T, W >::consume().
template<typename T , typename W > virtual void wibble::ConsumerMorph< T, W >::consume (Range< T > s) [inline, virtual]
Implements wibble::ConsumerInterface< T >.
References wibble::ConsumerMorph< T, W >::consume(), wibble::RangeMixin< T, Range< T > >::empty(), wibble::Range< T >::head(), and wibble::RangeMixin< T, Range< T > >::tail().
The documentation for this struct was generated from the following file:
consumer.h