wibble: wibble::RangeInterface< T > Struct Template Reference
wibble::RangeInterface< T > Struct Template Reference
#include <range.h>
Public Member Functions
virtual T head () const =0
virtual void removeFirst ()=0
virtual void setToEmpty ()=0
virtual ~RangeInterface ()
template<typename T>
struct wibble::RangeInterface< T >
Constructor & Destructor Documentation
template<typename T > virtual wibble::RangeInterface< T >::~RangeInterface () [inline, virtual]
Member Function Documentation
template<typename T > virtual T wibble::RangeInterface< T >::head () const [pure virtual]
Implemented in wibble::RangeMorph< T, W >.
Referenced by wibble::Range< Casted >::head().
template<typename T > virtual void wibble::RangeInterface< T >::removeFirst () [pure virtual]
Implemented in wibble::RangeMorph< T, W >.
Referenced by wibble::Range< Casted >::removeFirst().
template<typename T > virtual void wibble::RangeInterface< T >::setToEmpty () [pure virtual]
Implemented in wibble::RangeMorph< T, W >.
Referenced by wibble::Range< Casted >::setToEmpty().
The documentation for this struct was generated from the following file:
range.h