wibble: wibble::UniqueRange< T > Struct Template Reference
wibble::UniqueRange< T > Struct Template Reference
#include <range.h>
Public Member Functions
UniqueRange ()
UniqueRange (Range< T > r)
void find () const
void removeFirst ()
T head () const
void setToEmpty ()
bool operator<= (const UniqueRange &r) const
Protected Attributes
Range< T > m_range
bool m_valid:1
template<typename T>
struct wibble::UniqueRange< T >
Constructor & Destructor Documentation
template<typename T > wibble::UniqueRange< T >::UniqueRange () [inline]
template<typename T > wibble::UniqueRange< T >::UniqueRange (Range< T > r) [inline]
Member Function Documentation
template<typename T > void wibble::UniqueRange< T >::find () const [inline]
References wibble::UniqueRange< T >::m_range, and wibble::UniqueRange< T >::m_valid.
Referenced by wibble::UniqueRange< T >::head(), wibble::UniqueRange< T >::operator<=(), and wibble::UniqueRange< T >::removeFirst().
template<typename T > T wibble::UniqueRange< T >::head () const [inline]
References wibble::UniqueRange< T >::find(), and wibble::UniqueRange< T >::m_range.
template<typename T > bool wibble::UniqueRange< T >::operator<= (const UniqueRange< T > & r) const [inline]
References wibble::UniqueRange< T >::find(), and wibble::UniqueRange< T >::m_range.
template<typename T > void wibble::UniqueRange< T >::removeFirst () [inline]
References wibble::UniqueRange< T >::find(), wibble::UniqueRange< T >::m_range, and wibble::UniqueRange< T >::m_valid.
template<typename T > void wibble::UniqueRange< T >::setToEmpty () [inline]
References wibble::UniqueRange< T >::m_range.
Member Data Documentation
template<typename T > Range< T > wibble::UniqueRange< T >::m_range [mutable, protected]
Referenced by wibble::UniqueRange< T >::find(), wibble::UniqueRange< T >::head(), wibble::UniqueRange< T >::operator<=(), wibble::UniqueRange< T >::removeFirst(), and wibble::UniqueRange< T >::setToEmpty().
template<typename T > bool wibble::UniqueRange< T >::m_valid [mutable, protected]
Referenced by wibble::UniqueRange< T >::find(), and wibble::UniqueRange< T >::removeFirst().
The documentation for this struct was generated from the following file:
range.h