wibble: wibble::Morph< Self, W, Interface > Struct Template Reference
wibble::Morph< Self, W, Interface > Struct Template Reference
#include <amorph.h>
Public Types
typedef W Wrapped
Public Member Functions
Morph (const Wrapped &w)
const Self & self () const
bool operator<= (const Morph &o) const
virtual bool leq (const MorphInterface< Interface > *_o) const
virtual MorphInterface
< Interface > * constructCopy (void *where, unsigned int available) const
virtual void destroy (unsigned int available)
const Wrapped & wrapped () const
Wrapped & wrapped ()
virtual ~Morph ()
template<typename Self, typename W, typename Interface>
struct wibble::Morph< Self, W, Interface >
Member Typedef Documentation
template<typename Self, typename W, typename Interface> typedef W wibble::Morph< Self, W, Interface >::Wrapped
Reimplemented in wibble::RangeMorph< T, W >, and wibble::IteratorMorph< T, W >.
Constructor & Destructor Documentation
template<typename Self, typename W, typename Interface> wibble::Morph< Self, W, Interface >::Morph (const Wrapped & w) [inline]
template<typename Self, typename W, typename Interface> virtual wibble::Morph< Self, W, Interface >::~Morph () [inline, virtual]
Referenced by wibble::Morph< IteratorMorph< T, W >, W, IteratorInterface< T > >::destroy().
Member Function Documentation
template<typename Self, typename W, typename Interface> virtual MorphInterface< Interface >* wibble::Morph< Self, W, Interface >::constructCopy (void * where, unsigned int available) const [inline, virtual]
Implements wibble::MorphInterface< Interface >.
template<typename Self, typename W, typename Interface> virtual void wibble::Morph< Self, W, Interface >::destroy (unsigned int available) [inline, virtual]
Implements wibble::MorphInterface< Interface >.
template<typename Self, typename W, typename Interface> virtual bool wibble::Morph< Self, W, Interface >::leq (const MorphInterface< Interface > * _o) const [inline, virtual]
Implements wibble::MorphInterface< Interface >.
template<typename Self, typename W, typename Interface> bool wibble::Morph< Self, W, Interface >::operator<= (const Morph< Self, W, Interface > & o) const [inline]
template<typename Self, typename W, typename Interface> const Self& wibble::Morph< Self, W, Interface >::self () const [inline]
template<typename Self, typename W, typename Interface> const Wrapped& wibble::Morph< Self, W, Interface >::wrapped () const [inline]
Referenced by wibble::Morph< IteratorMorph< T, W >, W, IteratorInterface< T > >::leq(), and wibble::Morph< IteratorMorph< T, W >, W, IteratorInterface< T > >::operator<=().
template<typename Self, typename W, typename Interface> Wrapped& wibble::Morph< Self, W, Interface >::wrapped () [inline]
Reimplemented from wibble::MorphBase< W, Interface >.
The documentation for this struct was generated from the following file:
amorph.h