wibble: TestCommandlineDoc Struct Reference
TestCommandlineDoc Struct Reference
#include <doc.test.h>
Public Member Functions
Test basic ()
Member Function Documentation
Test TestCommandlineDoc::basic () [inline]
References wibble::commandline::OptionGroup::add(), wibble::commandline::Engine::addEngine(), and wibble::commandline::Engine::addGroup().
The documentation for this struct was generated from the following file:
doc.test.h