wibble: wibble::log::Sender Struct Reference
wibble::log::Sender Struct Reference
Handle sending a log message.
#include <stream.h>
Public Member Functions
virtual ~Sender ()
virtual void send (Level level, const std::string &msg)=0
Log one line of text with the given level.
Detailed Description
Handle sending a log message.
Constructor & Destructor Documentation
virtual wibble::log::Sender::~Sender () [inline, virtual]
Member Function Documentation
virtual void wibble::log::Sender::send (Level level, const std::string & msg) [pure virtual]
Log one line of text with the given level.
Do not add a trailing newline
Implemented in wibble::log::Tee, wibble::log::LevelFilter, wibble::log::Timestamper, wibble::log::FileSender, wibble::log::OstreamSender, and wibble::log::NullSender.
Referenced by wibble::log::Timestamper::send(), wibble::log::LevelFilter::send(), and wibble::log::Streambuf::send().
The documentation for this struct was generated from the following file:
stream.h