wibble: tut::callback Struct Reference
tut::callback Struct Reference
Test runner callback interface.
#include <tut.h>
Public Member Functions
virtual ~callback ()
Virtual destructor is a must for subclassed types.
virtual void run_started ()
Called when new test run started.
virtual void group_started (const std::string &)
Called when a group started.
virtual void test_completed (const test_result &)
Called when a test finished.
virtual void group_completed (const std::string &)
Called when a group is completed.
virtual void run_completed ()
Called when all tests in run completed.
Detailed Description
Test runner callback interface.
Can be implemented by caller to update tests results in real-time. User can implement any of callback methods, and leave unused in default implementation.
Constructor & Destructor Documentation
virtual tut::callback::~callback () [inline, virtual]
Virtual destructor is a must for subclassed types.
Member Function Documentation
virtual void tut::callback::group_completed (const std::string &) [inline, virtual]
Called when a group is completed.
Parameters:
name Name of the group
Referenced by tut::test_runner::run_test(), and tut::test_runner::run_tests().
virtual void tut::callback::group_started (const std::string &) [inline, virtual]
Called when a group started.
Parameters:
name Name of the group
Referenced by tut::test_runner::run_test(), and tut::test_runner::run_tests().
virtual void tut::callback::run_completed () [inline, virtual]
Called when all tests in run completed.
Referenced by tut::test_runner::run_test(), and tut::test_runner::run_tests().
virtual void tut::callback::run_started () [inline, virtual]
Called when new test run started.
Referenced by tut::test_runner::run_test(), and tut::test_runner::run_tests().
virtual void tut::callback::test_completed (const test_result &) [inline, virtual]
Called when a test finished.
Parameters:
tr Test results.
Referenced by tut::test_runner::run_test().
The documentation for this struct was generated from the following file:
tut.h