wibble: wibble::list::Sorted< List > Struct Template Reference
wibble::list::Sorted< List > Struct Template Reference
#include <list.h>
Classes
struct SharedPtr
struct SharedVec
Public Types
typedef std::vector< typename
List::Type > Vec
typedef List::Type Type
Public Member Functions
void sort () const
Type head () const
Sorted tail () const
bool empty () const
Sorted (const Sorted &o)
Sorted & operator= (const Sorted &o)
Sorted (List l=List())
Public Attributes
List m_list
SharedPtr m_sorted
size_t m_pos
template<typename List>
struct wibble::list::Sorted< List >
Member Typedef Documentation
template<typename List > typedef List::Type wibble::list::Sorted< List >::Type
template<typename List > typedef std::vector< typename List::Type > wibble::list::Sorted< List >::Vec
Constructor & Destructor Documentation
template<typename List > wibble::list::Sorted< List >::Sorted (const Sorted< List > & o) [inline]
template<typename List > wibble::list::Sorted< List >::Sorted (List l = List()) [inline]
Member Function Documentation
template<typename List > bool wibble::list::Sorted< List >::empty () const [inline]
References wibble::list::Sorted< List >::m_pos, wibble::list::Sorted< List >::m_sorted, and wibble::list::Sorted< List >::sort().
template<typename List > Type wibble::list::Sorted< List >::head () const [inline]
References wibble::list::Sorted< List >::m_pos, wibble::list::Sorted< List >::m_sorted, and wibble::list::Sorted< List >::sort().
template<typename List > Sorted& wibble::list::Sorted< List >::operator= (const Sorted< List > & o) [inline]
References wibble::list::Sorted< List >::m_list, wibble::list::Sorted< List >::m_pos, and wibble::list::Sorted< List >::m_sorted.
template<typename List > void wibble::list::Sorted< List >::sort () const [inline]
References wibble::list::Sorted< List >::m_list, and wibble::list::Sorted< List >::m_sorted.
Referenced by wibble::list::Sorted< List >::empty(), wibble::list::Sorted< List >::head(), and wibble::list::Sorted< List >::tail().
template<typename List > Sorted wibble::list::Sorted< List >::tail () const [inline]
References wibble::list::Sorted< List >::m_pos, and wibble::list::Sorted< List >::sort().
Member Data Documentation
template<typename List > List wibble::list::Sorted< List >::m_list
Referenced by wibble::list::Sorted< List >::operator=(), and wibble::list::Sorted< List >::sort().
template<typename List > size_t wibble::list::Sorted< List >::m_pos
Referenced by wibble::list::Sorted< List >::empty(), wibble::list::Sorted< List >::head(), wibble::list::Sorted< List >::operator=(), and wibble::list::Sorted< List >::tail().
template<typename List > SharedPtr wibble::list::Sorted< List >::m_sorted [mutable]
Referenced by wibble::list::Sorted< List >::empty(), wibble::list::Sorted< List >::head(), wibble::list::Sorted< List >::operator=(), and wibble::list::Sorted< List >::sort().
The documentation for this struct was generated from the following file:
list.h