wibble: wibble::FilteredRange< R, Pred > Struct Template Reference
wibble::FilteredRange< R, Pred > Struct Template Reference
#include <range.h>
Public Types
typedef R::ElementType ElementType
Public Member Functions
FilteredRange (const R &r, Pred p)
void find () const
void removeFirst ()
ElementType head () const
void setToEmpty ()
bool operator<= (const FilteredRange &f) const
Protected Member Functions
const Pred & pred () const
Protected Attributes
R m_range
R::iterator m_current
Pred m_pred
bool m_valid:1
template<typename R, typename Pred>
struct wibble::FilteredRange< R, Pred >
Member Typedef Documentation
template<typename R, typename Pred> typedef R::ElementType wibble::FilteredRange< R, Pred >::ElementType
Reimplemented from wibble::RangeMixin< R::ElementType, FilteredRange< R, Pred > >.
Constructor & Destructor Documentation
template<typename R, typename Pred> wibble::FilteredRange< R, Pred >::FilteredRange (const R & r, Pred p) [inline]
Member Function Documentation
template<typename R, typename Pred> void wibble::FilteredRange< R, Pred >::find () const [inline]
References wibble::FilteredRange< R, Pred >::m_current, wibble::FilteredRange< R, Pred >::m_range, wibble::FilteredRange< R, Pred >::m_valid, and wibble::FilteredRange< R, Pred >::pred().
Referenced by wibble::FilteredRange< R, Pred >::head(), wibble::FilteredRange< R, Pred >::operator<=(), and wibble::FilteredRange< R, Pred >::removeFirst().
template<typename R, typename Pred> ElementType wibble::FilteredRange< R, Pred >::head () const [inline]
References wibble::FilteredRange< R, Pred >::find(), and wibble::FilteredRange< R, Pred >::m_current.
template<typename R, typename Pred> bool wibble::FilteredRange< R, Pred >::operator<= (const FilteredRange< R, Pred > & f) const [inline]
References wibble::FilteredRange< R, Pred >::find(), and wibble::FilteredRange< R, Pred >::m_current.
template<typename R, typename Pred> const Pred& wibble::FilteredRange< R, Pred >::pred () const [inline, protected]
References wibble::FilteredRange< R, Pred >::m_pred.
Referenced by wibble::FilteredRange< R, Pred >::find().
template<typename R, typename Pred> void wibble::FilteredRange< R, Pred >::removeFirst () [inline]
References wibble::FilteredRange< R, Pred >::find(), wibble::FilteredRange< R, Pred >::m_current, and wibble::FilteredRange< R, Pred >::m_valid.
template<typename R, typename Pred> void wibble::FilteredRange< R, Pred >::setToEmpty () [inline]
References wibble::FilteredRange< R, Pred >::m_current, and wibble::FilteredRange< R, Pred >::m_range.
Member Data Documentation
template<typename R, typename Pred> R::iterator wibble::FilteredRange< R, Pred >::m_current [mutable, protected]
Referenced by wibble::FilteredRange< R, Pred >::find(), wibble::FilteredRange< R, Pred >::head(), wibble::FilteredRange< R, Pred >::operator<=(), wibble::FilteredRange< R, Pred >::removeFirst(), and wibble::FilteredRange< R, Pred >::setToEmpty().
template<typename R, typename Pred> Pred wibble::FilteredRange< R, Pred >::m_pred [protected]
Referenced by wibble::FilteredRange< R, Pred >::pred().
template<typename R, typename Pred> R wibble::FilteredRange< R, Pred >::m_range [protected]
Referenced by wibble::FilteredRange< R, Pred >::find(), and wibble::FilteredRange< R, Pred >::setToEmpty().
template<typename R, typename Pred> bool wibble::FilteredRange< R, Pred >::m_valid [mutable, protected]
Referenced by wibble::FilteredRange< R, Pred >::find(), and wibble::FilteredRange< R, Pred >::removeFirst().
The documentation for this struct was generated from the following file:
range.h