wibble: wibble::list::Filtered< List, Predicate > Struct Template Reference
wibble::list::Filtered< List, Predicate > Struct Template Reference
#include <list.h>
Public Types
typedef List::Type Type
Public Member Functions
bool empty () const
Type head () const
void seek () const
Filtered tail () const
Filtered (List l, Predicate p)
Filtered ()
Public Attributes
List m_list
Predicate m_pred
template<typename List, typename Predicate>
struct wibble::list::Filtered< List, Predicate >
Member Typedef Documentation
template<typename List, typename Predicate> typedef List::Type wibble::list::Filtered< List, Predicate >::Type
Constructor & Destructor Documentation
template<typename List, typename Predicate> wibble::list::Filtered< List, Predicate >::Filtered (List l, Predicate p) [inline]
template<typename List, typename Predicate> wibble::list::Filtered< List, Predicate >::Filtered () [inline]
Member Function Documentation
template<typename List, typename Predicate> bool wibble::list::Filtered< List, Predicate >::empty () const [inline]
References wibble::list::Filtered< List, Predicate >::m_list, and wibble::list::Filtered< List, Predicate >::seek().
template<typename List, typename Predicate> Type wibble::list::Filtered< List, Predicate >::head () const [inline]
References wibble::list::Filtered< List, Predicate >::m_list, and wibble::list::Filtered< List, Predicate >::seek().
template<typename List, typename Predicate> void wibble::list::Filtered< List, Predicate >::seek () const [inline]
References wibble::list::Filtered< List, Predicate >::m_list, and wibble::list::Filtered< List, Predicate >::m_pred.
Referenced by wibble::list::Filtered< List, Predicate >::empty(), wibble::list::Filtered< List, Predicate >::head(), and wibble::list::Filtered< List, Predicate >::tail().
template<typename List, typename Predicate> Filtered wibble::list::Filtered< List, Predicate >::tail () const [inline]
References wibble::list::Filtered< List, Predicate >::m_list, and wibble::list::Filtered< List, Predicate >::seek().
Member Data Documentation
template<typename List, typename Predicate> List wibble::list::Filtered< List, Predicate >::m_list [mutable]
Referenced by wibble::list::Filtered< List, Predicate >::empty(), wibble::list::Filtered< List, Predicate >::head(), wibble::list::Filtered< List, Predicate >::seek(), and wibble::list::Filtered< List, Predicate >::tail().
template<typename List, typename Predicate> Predicate wibble::list::Filtered< List, Predicate >::m_pred
Referenced by wibble::list::Filtered< List, Predicate >::seek().
The documentation for this struct was generated from the following file:
list.h