wibble: wibble::RangeMixin< T, Self > Struct Template Reference
wibble::RangeMixin< T, Self > Struct Template Reference
#include <range.h>
Public Types
typedef Self RangeImplementation
typedef T ElementType
typedef IteratorMixin< T, Self > Base
typedef RangeIterator< Self > iterator
Public Member Functions
const Self & self () const
iterator begin () const
iterator end () const
T head ()
Self tail () const
void output (Consumer< T > t) const
bool empty () const
~RangeMixin ()
Friends
struct RangeIterator< Self >
template<typename T, typename Self>
struct wibble::RangeMixin< T, Self >
Member Typedef Documentation
template<typename T, typename Self> typedef IteratorMixin< T, Self > wibble::RangeMixin< T, Self >::Base
template<typename T, typename Self> typedef T wibble::RangeMixin< T, Self >::ElementType
Reimplemented in wibble::FilteredRange< R, Pred >.
template<typename T, typename Self> typedef RangeIterator< Self > wibble::RangeMixin< T, Self >::iterator
template<typename T, typename Self> typedef Self wibble::RangeMixin< T, Self >::RangeImplementation
Constructor & Destructor Documentation
template<typename T, typename Self> wibble::RangeMixin< T, Self >::~RangeMixin () [inline]
Member Function Documentation
template<typename T, typename Self> iterator wibble::RangeMixin< T, Self >::begin () const [inline]
Referenced by wibble::RangeMixin< T, GeneratedRange< T, _Advance, _End > >::empty(), and wibble::RangeMixin< T, GeneratedRange< T, _Advance, _End > >::output().
template<typename T, typename Self> bool wibble::RangeMixin< T, Self >::empty () const [inline]
template<typename T, typename Self> iterator wibble::RangeMixin< T, Self >::end () const [inline]
Referenced by wibble::RangeMixin< T, GeneratedRange< T, _Advance, _End > >::empty(), and wibble::RangeMixin< T, GeneratedRange< T, _Advance, _End > >::output().
template<typename T, typename Self> T wibble::RangeMixin< T, Self >::head () [inline]
Referenced by wibble::RangeMixin< T, GeneratedRange< T, _Advance, _End > >::head().
template<typename T, typename Self> void wibble::RangeMixin< T, Self >::output (Consumer< T > t) const [inline]
template<typename T, typename Self> const Self& wibble::RangeMixin< T, Self >::self () const [inline]
template<typename T, typename Self> Self wibble::RangeMixin< T, Self >::tail () const [inline]
Friends And Related Function Documentation
template<typename T, typename Self> friend struct RangeIterator< Self > [friend]
The documentation for this struct was generated from the following file:
range.h