wibble: wibble::Maybe< T > Struct Template Reference
wibble::Maybe< T > Struct Template Reference
#include <maybe.h>
Public Member Functions
bool nothing () const
T & value ()
const T & value () const
Maybe (bool n, const T &v)
Maybe (const T &df=T())
operator T () const
bool operator<= (const Maybe< T > &o) const
Static Public Member Functions
static Maybe Just (const T &t)
static Maybe Nothing (const T &df=T())
Protected Attributes
bool m_nothing:1
T m_value
template<typename T>
struct wibble::Maybe< T >
Constructor & Destructor Documentation
template<typename T > wibble::Maybe< T >::Maybe (bool n, const T & v) [inline]
Referenced by wibble::Maybe< T >::Just(), wibble::Maybe< void >::Just(), wibble::Maybe< T >::Nothing(), and wibble::Maybe< void >::Nothing().
template<typename T > wibble::Maybe< T >::Maybe (const T & df = T()) [inline]
Member Function Documentation
template<typename T > static Maybe wibble::Maybe< T >::Just (const T & t) [inline, static]
References wibble::Maybe< T >::Maybe().
template<typename T > bool wibble::Maybe< T >::nothing () const [inline]
References wibble::Maybe< T >::m_nothing.
Referenced by wibble::Maybe< T >::operator<=().
template<typename T > static Maybe wibble::Maybe< T >::Nothing (const T & df = T()) [inline, static]
References wibble::Maybe< T >::Maybe().
template<typename T > wibble::Maybe< T >::operator T () const [inline]
References wibble::Maybe< T >::value().
template<typename T > bool wibble::Maybe< T >::operator<= (const Maybe< T > & o) const [inline]
References wibble::Maybe< T >::nothing(), and wibble::Maybe< T >::value().
template<typename T > T& wibble::Maybe< T >::value () [inline]
References wibble::Maybe< T >::m_value.
Referenced by wibble::Maybe< T >::operator T(), and wibble::Maybe< T >::operator<=().
template<typename T > const T& wibble::Maybe< T >::value () const [inline]
References wibble::Maybe< T >::m_value.
Member Data Documentation
template<typename T > bool wibble::Maybe< T >::m_nothing [protected]
Referenced by wibble::Maybe< T >::nothing().
template<typename T > T wibble::Maybe< T >::m_value [protected]
Referenced by wibble::Maybe< T >::value().
The documentation for this struct was generated from the following file:
maybe.h