wibble: wibble::net::TCPServer Struct Reference
wibble::net::TCPServer Struct Reference
#include <server.h>
Public Member Functions
TCPServer ()
virtual ~TCPServer ()
int accept_loop ()
Loop accepting connections on the socket, until interrupted by a signal in stop_signals.
virtual void handle_client (int sock, const std::string &peer_hostname, const std::string &peer_hostaddr, const std::string &peer_port)=0
Public Attributes
std::vector< int > stop_signals
Protected Member Functions
void signal_setup ()
void signal_install ()
void signal_uninstall ()
Static Protected Member Functions
static void signal_handler (int sig)
Static Protected Attributes
static int last_signal = -1
Constructor & Destructor Documentation
wibble::net::TCPServer::TCPServer ()
References stop_signals.
wibble::net::TCPServer::~TCPServer () [virtual]
Member Function Documentation
int wibble::net::TCPServer::accept_loop ()
Loop accepting connections on the socket, until interrupted by a signal in stop_signals.
Returns:
the signal number that stopped the loop
References handle_client(), wibble::net::Server::host, last_signal, wibble::net::Server::port, signal_install(), signal_setup(), signal_uninstall(), and wibble::net::Server::sock.
virtual void wibble::net::TCPServer::handle_client (int sock, const std::string & peer_hostname, const std::string & peer_hostaddr, const std::string & peer_port) [pure virtual]
Referenced by accept_loop().
void wibble::net::TCPServer::signal_handler (int sig) [static, protected]
References last_signal.
Referenced by signal_setup().
void wibble::net::TCPServer::signal_install () [protected]
References wibble::str::fmt(), last_signal, wibble::net::Server::old_signal_actions, wibble::net::Server::signal_actions, and stop_signals.
Referenced by accept_loop().
void wibble::net::TCPServer::signal_setup () [protected]
References wibble::net::Server::old_signal_actions, wibble::net::Server::signal_actions, and signal_handler().
Referenced by accept_loop().
void wibble::net::TCPServer::signal_uninstall () [protected]
References wibble::str::fmt(), wibble::net::Server::old_signal_actions, and stop_signals.
Referenced by accept_loop().
Member Data Documentation
int wibble::net::TCPServer::last_signal = -1 [static, protected]
Referenced by accept_loop(), signal_handler(), and signal_install().
std::vector<int> wibble::net::TCPServer::stop_signals
Referenced by signal_install(), signal_uninstall(), and TCPServer().
The documentation for this struct was generated from the following files:
server.h
server.cpp