wibble: wibble::TransformedRange< Transform > Struct Template Reference
wibble::TransformedRange< Transform > Struct Template Reference
#include <range.h>
Public Types
typedef Transform::argument_type Source
typedef Transform::result_type Result
Public Member Functions
TransformedRange (Range< Source > r, Transform t)
bool operator<= (const TransformedRange &o) const
Result head () const
void removeFirst ()
void setToEmpty ()
Protected Attributes
Range< Source > m_range
Transform m_transform
template<typename Transform>
struct wibble::TransformedRange< Transform >
Member Typedef Documentation
template<typename Transform> typedef Transform::result_type wibble::TransformedRange< Transform >::Result
template<typename Transform> typedef Transform::argument_type wibble::TransformedRange< Transform >::Source
Constructor & Destructor Documentation
template<typename Transform> wibble::TransformedRange< Transform >::TransformedRange (Range< Source > r, Transform t) [inline]
Member Function Documentation
template<typename Transform> Result wibble::TransformedRange< Transform >::head () const [inline]
References wibble::Range< T >::head(), wibble::TransformedRange< Transform >::m_range, and wibble::TransformedRange< Transform >::m_transform.
template<typename Transform> bool wibble::TransformedRange< Transform >::operator<= (const TransformedRange< Transform > & o) const [inline]
References wibble::TransformedRange< Transform >::m_range.
template<typename Transform> void wibble::TransformedRange< Transform >::removeFirst () [inline]
References wibble::TransformedRange< Transform >::m_range, and wibble::Range< T >::removeFirst().
template<typename Transform> void wibble::TransformedRange< Transform >::setToEmpty () [inline]
References wibble::TransformedRange< Transform >::m_range, and wibble::Range< T >::setToEmpty().
Member Data Documentation
template<typename Transform> Range< Source > wibble::TransformedRange< Transform >::m_range [protected]
Referenced by wibble::TransformedRange< Transform >::head(), wibble::TransformedRange< Transform >::operator<=(), wibble::TransformedRange< Transform >::removeFirst(), and wibble::TransformedRange< Transform >::setToEmpty().
template<typename Transform> Transform wibble::TransformedRange< Transform >::m_transform [protected]
Referenced by wibble::TransformedRange< Transform >::head().
The documentation for this struct was generated from the following file:
range.h