wibble: wibble::mixin::Comparable< Self > Struct Template Reference
wibble::mixin::Comparable< Self > Struct Template Reference
#include <mixin.h>
Public Member Functions
const Self & cmpSelf () const
bool operator!= (const Self &o) const
bool operator== (const Self &o) const
bool operator< (const Self &o) const
bool operator> (const Self &o) const
bool operator>= (const Self &o) const
template<typename Self>
struct wibble::mixin::Comparable< Self >
Member Function Documentation
template<typename Self> const Self& wibble::mixin::Comparable< Self >::cmpSelf () const [inline]
Referenced by wibble::mixin::Comparable< RangeIterator< R > >::operator!=(), wibble::mixin::Comparable< RangeIterator< R > >::operator<(), wibble::mixin::Comparable< RangeIterator< R > >::operator==(), wibble::mixin::Comparable< RangeIterator< R > >::operator>(), and wibble::mixin::Comparable< RangeIterator< R > >::operator>=().
template<typename Self> bool wibble::mixin::Comparable< Self >::operator!= (const Self & o) const [inline]
template<typename Self> bool wibble::mixin::Comparable< Self >::operator< (const Self & o) const [inline]
template<typename Self> bool wibble::mixin::Comparable< Self >::operator== (const Self & o) const [inline]
template<typename Self> bool wibble::mixin::Comparable< Self >::operator> (const Self & o) const [inline]
template<typename Self> bool wibble::mixin::Comparable< Self >::operator>= (const Self & o) const [inline]
The documentation for this struct was generated from the following file:
mixin.h