wibble: wibble::Consumer< T > Struct Template Reference
wibble::Consumer< T > Struct Template Reference
#include <consumer.h>
Public Types
typedef Amorph< Consumer< T >
, ConsumerInterface< T > > Super
typedef void value_type
typedef void difference_type
typedef void pointer
typedef void reference
Public Member Functions
Consumer (const MorphInterface< ConsumerInterface< T > > &i)
Consumer ()
void consume (const T &a)
Consumer< T > & operator= (const T &a)
template<typename T>
struct wibble::Consumer< T >
Member Typedef Documentation
template<typename T> typedef void wibble::Consumer< T >::difference_type
template<typename T> typedef void wibble::Consumer< T >::pointer
template<typename T> typedef void wibble::Consumer< T >::reference
template<typename T> typedef Amorph< Consumer< T >, ConsumerInterface< T > > wibble::Consumer< T >::Super
template<typename T> typedef void wibble::Consumer< T >::value_type
Constructor & Destructor Documentation
template<typename T> wibble::Consumer< T >::Consumer (const MorphInterface< ConsumerInterface< T > > & i) [inline]
template<typename T> wibble::Consumer< T >::Consumer () [inline]
Member Function Documentation
template<typename T> void wibble::Consumer< T >::consume (const T & a) [inline]
References wibble::ConsumerInterface< T >::consume(), and wibble::Amorph< Consumer< T >, ConsumerInterface< T > >::implementation().
Referenced by wibble::Consumer< T >::operator=().
template<typename T> Consumer< T >& wibble::Consumer< T >::operator= (const T & a) [inline]
Reimplemented from wibble::ConsumerMixin< T, Consumer< T > >.
References wibble::Consumer< T >::consume().
The documentation for this struct was generated from the following file:
consumer.h