wibble: wibble::Amorph< Self, _Interface, Padding > Struct Template Reference
wibble::Amorph< Self, _Interface, Padding > Struct Template Reference
#include <amorph.h>
Classes
struct Convert
Public Types
typedef _Interface Interface
Public Member Functions
Amorph (const MorphInterface< Interface > &b)
Amorph (const Amorph &a)
Amorph ()
const Self & self () const
Self & self ()
bool leq (const Self &i) const
bool operator<= (const Self &i) const
void setInterfacePointer (const Interface *i)
void setMorphInterfacePointer (const MorphInterface< Interface > *i)
Amorph & operator= (const Amorph &i)
~Amorph ()
template<typename F >
Maybe< typename F::result_type > ifType (F func)
const Interface * implementation () const
Interface * implementation ()
MorphInterface< Interface > * morphInterface () const
const Interface & wrapped () const
Interface & wrapped ()
template<typename T >
bool is () const
bool isVoid () const
template<typename T >
T * impl () const
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING>
struct wibble::Amorph< Self, _Interface, Padding >
Member Typedef Documentation
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> typedef _Interface wibble::Amorph< Self, _Interface, Padding >::Interface
Constructor & Destructor Documentation
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> wibble::Amorph< Self, _Interface, Padding >::Amorph (const MorphInterface< Interface > & b) [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> wibble::Amorph< Self, _Interface, Padding >::Amorph (const Amorph< Self, _Interface, Padding > & a) [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> wibble::Amorph< Self, _Interface, Padding >::Amorph () [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> wibble::Amorph< Self, _Interface, Padding >::~Amorph () [inline]
Member Function Documentation
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> template<typename F > Maybe< typename F::result_type > wibble::Amorph< Self, _Interface, Padding >::ifType (F func) [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> template<typename T > T* wibble::Amorph< Self, _Interface, Padding >::impl () const [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> const Interface* wibble::Amorph< Self, _Interface, Padding >::implementation () const [inline]
Referenced by wibble::Amorph< Range< T >, RangeInterface< T > >::operator=(), and wibble::Amorph< Range< T >, RangeInterface< T > >::wrapped().
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> Interface* wibble::Amorph< Self, _Interface, Padding >::implementation () [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> template<typename T > bool wibble::Amorph< Self, _Interface, Padding >::is () const [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> bool wibble::Amorph< Self, _Interface, Padding >::isVoid () const [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> bool wibble::Amorph< Self, _Interface, Padding >::leq (const Self & i) const [inline]
Referenced by wibble::Amorph< Range< T >, RangeInterface< T > >::operator<=().
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> MorphInterface< Interface >* wibble::Amorph< Self, _Interface, Padding >::morphInterface () const [inline]
Referenced by wibble::Amorph< Range< T >, RangeInterface< T > >::Amorph(), wibble::Amorph< Range< T >, RangeInterface< T > >::impl(), wibble::Amorph< Range< T >, RangeInterface< T > >::leq(), and wibble::Amorph< Range< T >, RangeInterface< T > >::~Amorph().
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> bool wibble::Amorph< Self, _Interface, Padding >::operator<= (const Self & i) const [inline]
Reimplemented in wibble::Iterator< T >.
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> Amorph& wibble::Amorph< Self, _Interface, Padding >::operator= (const Amorph< Self, _Interface, Padding > & i) [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> const Self& wibble::Amorph< Self, _Interface, Padding >::self () const [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> Self& wibble::Amorph< Self, _Interface, Padding >::self () [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> void wibble::Amorph< Self, _Interface, Padding >::setInterfacePointer (const Interface * i) [inline]
Referenced by wibble::Amorph< Range< T >, RangeInterface< T > >::operator=().
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> void wibble::Amorph< Self, _Interface, Padding >::setMorphInterfacePointer (const MorphInterface< Interface > * i) [inline]
Referenced by wibble::Amorph< Range< T >, RangeInterface< T > >::Amorph().
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> const Interface& wibble::Amorph< Self, _Interface, Padding >::wrapped () const [inline]
template<typename Self, typename _Interface, int Padding = WIBBLE_AMORPH_PADDING> Interface& wibble::Amorph< Self, _Interface, Padding >::wrapped () [inline]
The documentation for this struct was generated from the following file:
amorph.h