wibble: wibble::list::Sorted< List >::SharedVec Struct Reference
wibble::list::Sorted< List >::SharedVec Struct Reference
#include <list.h>
Public Member Functions
SharedVec ()
void _ref ()
void _deref ()
Public Attributes
int refs
Vec vec
template<typename List>
struct wibble::list::Sorted< List >::SharedVec
Constructor & Destructor Documentation
template<typename List > wibble::list::Sorted< List >::SharedVec::SharedVec () [inline]
Member Function Documentation
template<typename List > void wibble::list::Sorted< List >::SharedVec::_deref () [inline]
References wibble::list::Sorted< List >::SharedVec::refs.
Referenced by wibble::list::Sorted< List >::SharedPtr::~SharedPtr().
template<typename List > void wibble::list::Sorted< List >::SharedVec::_ref () [inline]
References wibble::list::Sorted< List >::SharedVec::refs.
Referenced by wibble::list::Sorted< List >::SharedPtr::operator=(), and wibble::list::Sorted< List >::SharedPtr::SharedPtr().
Member Data Documentation
template<typename List > int wibble::list::Sorted< List >::SharedVec::refs
Referenced by wibble::list::Sorted< List >::SharedVec::_deref(), wibble::list::Sorted< List >::SharedVec::_ref(), and wibble::list::Sorted< List >::SharedPtr::~SharedPtr().
template<typename List > Vec wibble::list::Sorted< List >::SharedVec::vec
Referenced by wibble::list::Sorted< List >::SharedPtr::operator*(), and wibble::list::Sorted< List >::SharedPtr::operator->().
The documentation for this struct was generated from the following file:
list.h