wibble: wibble::CastedRange< T, Casted > Struct Template Reference
wibble::CastedRange< T, Casted > Struct Template Reference
#include <range.h>
Public Member Functions
CastedRange ()
CastedRange (Range< Casted > r)
T head () const
void removeFirst ()
bool operator<= (const CastedRange &r) const
void setToEmpty ()
Protected Attributes
Range< Casted > m_casted
template<typename T, typename Casted>
struct wibble::CastedRange< T, Casted >
Constructor & Destructor Documentation
template<typename T , typename Casted > wibble::CastedRange< T, Casted >::CastedRange () [inline]
template<typename T , typename Casted > wibble::CastedRange< T, Casted >::CastedRange (Range< Casted > r) [inline]
Member Function Documentation
template<typename T , typename Casted > T wibble::CastedRange< T, Casted >::head () const [inline]
References wibble::Range< T >::head(), and wibble::CastedRange< T, Casted >::m_casted.
template<typename T , typename Casted > bool wibble::CastedRange< T, Casted >::operator<= (const CastedRange< T, Casted > & r) const [inline]
References wibble::CastedRange< T, Casted >::m_casted.
template<typename T , typename Casted > void wibble::CastedRange< T, Casted >::removeFirst () [inline]
References wibble::CastedRange< T, Casted >::m_casted, and wibble::Range< T >::removeFirst().
template<typename T , typename Casted > void wibble::CastedRange< T, Casted >::setToEmpty () [inline]
References wibble::CastedRange< T, Casted >::m_casted, and wibble::Range< T >::setToEmpty().
Member Data Documentation
template<typename T , typename Casted > Range< Casted > wibble::CastedRange< T, Casted >::m_casted [protected]
Referenced by wibble::CastedRange< T, Casted >::head(), wibble::CastedRange< T, Casted >::operator<=(), wibble::CastedRange< T, Casted >::removeFirst(), and wibble::CastedRange< T, Casted >::setToEmpty().
The documentation for this struct was generated from the following file:
range.h