wibble: wibble::IntersectionRange< T > Struct Template Reference
wibble::IntersectionRange< T > Struct Template Reference
#include <range.h>
Public Member Functions
IntersectionRange ()
IntersectionRange (Range< T > r1, Range< T > r2)
void find () const
void removeFirst ()
T head () const
void setToEmpty ()
bool operator<= (const IntersectionRange &f) const
Protected Attributes
Range< T > m_first
Range< T > m_second
bool m_valid:1
template<typename T>
struct wibble::IntersectionRange< T >
Constructor & Destructor Documentation
template<typename T> wibble::IntersectionRange< T >::IntersectionRange () [inline]
template<typename T> wibble::IntersectionRange< T >::IntersectionRange (Range< T > r1, Range< T > r2) [inline]
Member Function Documentation
template<typename T> void wibble::IntersectionRange< T >::find () const [inline]
References wibble::IntersectionRange< T >::m_first, wibble::IntersectionRange< T >::m_second, and wibble::IntersectionRange< T >::m_valid.
Referenced by wibble::IntersectionRange< T >::head(), wibble::IntersectionRange< T >::operator<=(), and wibble::IntersectionRange< T >::removeFirst().
template<typename T> T wibble::IntersectionRange< T >::head () const [inline]
References wibble::IntersectionRange< T >::find(), and wibble::IntersectionRange< T >::m_first.
template<typename T> bool wibble::IntersectionRange< T >::operator<= (const IntersectionRange< T > & f) const [inline]
References wibble::IntersectionRange< T >::find(), and wibble::IntersectionRange< T >::m_first.
template<typename T> void wibble::IntersectionRange< T >::removeFirst () [inline]
References wibble::IntersectionRange< T >::find(), wibble::IntersectionRange< T >::m_first, wibble::IntersectionRange< T >::m_second, and wibble::IntersectionRange< T >::m_valid.
template<typename T> void wibble::IntersectionRange< T >::setToEmpty () [inline]
References wibble::IntersectionRange< T >::m_first, and wibble::IntersectionRange< T >::m_second.
Member Data Documentation
template<typename T> Range< T > wibble::IntersectionRange< T >::m_first [mutable, protected]
Referenced by wibble::IntersectionRange< T >::find(), wibble::IntersectionRange< T >::head(), wibble::IntersectionRange< T >::operator<=(), wibble::IntersectionRange< T >::removeFirst(), and wibble::IntersectionRange< T >::setToEmpty().
template<typename T> Range< T > wibble::IntersectionRange< T >::m_second [mutable, protected]
Referenced by wibble::IntersectionRange< T >::find(), wibble::IntersectionRange< T >::removeFirst(), and wibble::IntersectionRange< T >::setToEmpty().
template<typename T> bool wibble::IntersectionRange< T >::m_valid [mutable, protected]
Referenced by wibble::IntersectionRange< T >::find(), and wibble::IntersectionRange< T >::removeFirst().
The documentation for this struct was generated from the following file:
range.h