wibble: wibble::Range< T > Struct Template Reference
wibble::Range< T > Struct Template Reference
#include <range.h>
Public Types
typedef Amorph< Range< T >
, RangeInterface< T > > Super
Public Member Functions
template<typename C >
Range (const C &i, typename IsType< int, typename C::RangeImplementation >::T fake=0)
Range ()
T head () const
void removeFirst ()
void setToEmpty ()
template<typename C >
operator Range< C > ()
template<typename T>
struct wibble::Range< T >
Member Typedef Documentation
template<typename T> typedef Amorph< Range< T >, RangeInterface< T > > wibble::Range< T >::Super
Constructor & Destructor Documentation
template<typename T> template<typename C > wibble::Range< T >::Range (const C & i, typename IsType< int, typename C::RangeImplementation >::T fake = 0) [inline]
template<typename T> wibble::Range< T >::Range () [inline]
Member Function Documentation
template<typename T> T wibble::Range< T >::head () const [inline]
Referenced by wibble::ConsumerMorph< T, W >::consume(), wibble::CastedRange< T, Casted >::head(), and wibble::TransformedRange< Transform >::head().
template<typename T > template<typename C > wibble::Range< T >::operator Range< C > ()
template<typename T> void wibble::Range< T >::removeFirst () [inline]
Referenced by wibble::CastedRange< T, Casted >::removeFirst(), and wibble::TransformedRange< Transform >::removeFirst().
template<typename T> void wibble::Range< T >::setToEmpty () [inline]
Referenced by wibble::CastedRange< T, Casted >::setToEmpty(), and wibble::TransformedRange< Transform >::setToEmpty().
The documentation for this struct was generated from the following file:
range.h