wibble: wibble::RangeMorph< T, W > Struct Template Reference
wibble::RangeMorph< T, W > Struct Template Reference
#include <range.h>
Public Types
typedef W::RangeImplementation Wrapped
Public Member Functions
RangeMorph (const Wrapped &w)
virtual void setToEmpty ()
virtual void removeFirst ()
virtual T head () const
template<typename T, typename W>
struct wibble::RangeMorph< T, W >
Member Typedef Documentation
template<typename T , typename W > typedef W::RangeImplementation wibble::RangeMorph< T, W >::Wrapped
Reimplemented from wibble::Morph< RangeMorph< T, W >, W, RangeInterface< T > >.
Constructor & Destructor Documentation
template<typename T , typename W > wibble::RangeMorph< T, W >::RangeMorph (const Wrapped & w) [inline]
Member Function Documentation
template<typename T , typename W > virtual T wibble::RangeMorph< T, W >::head () const [inline, virtual]
Implements wibble::RangeInterface< T >.
References wibble::Morph< RangeMorph< T, W >, W, RangeInterface< T > >::wrapped().
template<typename T , typename W > virtual void wibble::RangeMorph< T, W >::removeFirst () [inline, virtual]
Implements wibble::RangeInterface< T >.
References wibble::Morph< RangeMorph< T, W >, W, RangeInterface< T > >::wrapped().
template<typename T , typename W > virtual void wibble::RangeMorph< T, W >::setToEmpty () [inline, virtual]
Implements wibble::RangeInterface< T >.
References wibble::Morph< RangeMorph< T, W >, W, RangeInterface< T > >::wrapped().
The documentation for this struct was generated from the following file:
range.h