wibble: TestEmpty Struct Reference
TestEmpty Struct Reference
#include <empty.test.h>
Public Member Functions
Test basic ()
Member Function Documentation
Test TestEmpty::basic () [inline]
References assert, assert_eq, wibble::Empty< T >::begin(), wibble::Empty< T >::end(), and wibble::Empty< T >::size().
The documentation for this struct was generated from the following file:
empty.test.h