(* Created with the Wolfram Language : www.wolfram.com *)
<|"person" -> "people", "child" -> "children", "sex" -> "sexes", 
 "move" -> "moves", "beau" -> "beaux", "foot" -> "feet", "goose" -> "geese", 
 "tooth" -> "teeth", "woman" -> "women", "man" -> "men", 
 "antenna" -> "antennae", "formula" -> "formulae", "nebula" -> "nebulae", 
 "vertebra" -> "vertebrae", "vita" -> "vitae", "alga" -> "algae", 
 "larva" -> "larvae", "leaf" -> "leaves", "loaf" -> "loaves", 
 "sheaf" -> "sheaves", "thief" -> "thieves", "echo" -> "echoes", 
 "embargo" -> "embargoes", "hero" -> "heroes", "potato" -> "potatoes", 
 "torpedo" -> "torpedoes", "veto" -> "vetoes", "domino" -> "dominoes", 
 "mosquito" -> "mosquitoes", "cargo" -> "cargoes", "fresco" -> "frescos", 
 "mango" -> "mangoes", "motto" -> "mottoes", "tornado" -> "tornadoes", 
 "volcano" -> "volcanoes", "deer" -> "deer", "cod" -> "cod", 
 "fish" -> "fish", "offspring" -> "offspring", "perch" -> "perch", 
 "sheep" -> "sheep", "trout" -> "trout", "series" -> "series", 
 "species" -> "species", "barracks" -> "barracks", 
 "crossroads" -> "crossroads", "gallows" -> "gallows", 
 "headquarters" -> "headquarters", "incognito" -> "incognitos", "obsequy" -> "obsequies", 
 "means" -> "means", "Japanese" -> "Japanese", 
 "bacillus" -> "bacilli", "syllabus" -> "syllabi", "terminus" -> "termini", 
 "alumnus" -> "alumni", "cactus" -> "cacti", "focus" -> "foci", 
 "fungus" -> "fungi", "nucleus" -> "nuclei", "radius" -> "radii", 
 "stimulus" -> "stimuli", "addendum" -> "addenda", "ovum" -> "ova", 
 "corpus" -> "corpora", "curriculum" -> "curricula", "genus" -> "genera", "genu" -> "genua",
 "memorandum" -> "memoranda", "phenomenon" -> "phenomena", 
 "millenium" -> "millennia", "stadium" -> "stadiums", 
 "thesaurus" -> "thesauri", "apex" -> "apices", "cervix" -> "cervices", 
 "vortex" -> "vortices", "appendix" -> "appendices", "cortex" -> "cortices", 
 "criterion" -> "criteria", "automaton" -> "automata", 
 "libretto" -> "libretti", "tempo" -> "tempi", "virtuoso" -> "virtuosi", 
 "cherub" -> "cherubim", "seraph" -> "seraphim", "schema" -> "schemata", 
 "trousseau" -> "trousseaus", "paparazzo" -> "paparazzi", 
 "stomach" -> "stomachs", "epoch" -> "epochs", "abyss" -> "abysses", 
 "advice" -> "advice", "aircraft" -> "aircraft", "alumna" -> "alumnae", 
 "analysis" -> "analyses", "aquarium" -> "aquaria", "arch" -> "arches", 
 "atlas" -> "atlases", "axe" -> "axes", "axis" -> "axes", "baby" -> "babies", 
 "bacterium" -> "bacteria", "basis" -> "bases", "batch" -> "batches", 
 "beach" -> "beaches", "bison" -> "bison", "brother" -> "brethren", 
 "brush" -> "brushes", "buffalo" -> "buffalo", "bus" -> "buses", 
 "calf" -> "calves", "chateau" -> "chateaux", "cherry" -> "cherries", 
 "church" -> "churches", "circus" -> "circuses", "city" -> "cities", 
 "copy" -> "copies", "corn" -> "corn", "crisis" -> "crises", 
 "datum" -> "data", "diagnosis" -> "diagnoses", 
 "dictionary" -> "dictionaries", "die" -> "dice", "dwarf" -> "dwarves", 
 "elf" -> "elves", "ellipsis" -> "ellipses", "emphasis" -> "emphases", 
 "equipment" -> "equipment", "erratum" -> "errata", "evidence" -> "evidence", 
 "family" -> "families", "fax" -> "faxes", "flush" -> "flushes", 
 "fly" -> "flies", "gold" -> "gold", "grotto" -> "grottoes", 
 "gymnasium" -> "gymnasia", "half" -> "halves", 
 "hippopotamus" -> "hippopotami", "hoax" -> "hoaxes", "hoof" -> "hooves", 
 "hypothesis" -> "hypotheses", "index" -> "indices", 
 "information" -> "information", "iris" -> "irises", "jewelry" -> "jewelry", 
 "kin" -> "kin", "kiss" -> "kisses", "knife" -> "knives", "lady" -> "ladies", 
 "legislation" -> "legislation", "life" -> "lives", "locus" -> "loci", 
 "louse" -> "lice", "luck" -> "luck", "luggage" -> "luggage", 
 "matrix" -> "matrices", "medium" -> "media", "mess" -> "messes", 
 "moose" -> "moose", "mouse" -> "mice", "music" -> "music", 
 "nanny" -> "nannies", "nemesis" -> "nemeses", "neurosis" -> "neuroses", 
 "oasis" -> "oases", "octopus" -> "octopi", "ox" -> "oxen", 
 "paralysis" -> "paralyses", "parenthesis" -> "parentheses", 
 "party" -> "parties", "pass" -> "passes", "penny" -> "pennies", 
 "phalanx" -> "phalanges", "plankton" -> "plankton", "plateau" -> "plateaux", 
 "platypus" -> "platypuses", "polyhedron" -> "polyhedra", 
 "poppy" -> "poppies", "pupa" -> "pupae", "quantum" -> "quanta", 
 "quiz" -> "quizzes", "reflex" -> "reflexes", "scarf" -> "scarves",
 "scratch" -> "scratches", "self" -> "selves", 
 "serum" -> "sera", "shelf" -> "shelves", "silver" -> "silver", 
 "splash" -> "splashes", "spy" -> "spies", "squid" -> "squid", 
 "stitch" -> "stitches", "story" -> "stories", "stratum" -> "strata", 
 "swine" -> "swine", "synopsis" -> "synopses", "synthesis" -> "syntheses", 
 "tableau" -> "tableaux", "tax" -> "taxes", "testis" -> "testes", 
 "that" -> "those", "thesis" -> "theses", "this" -> "these", 
 "tomato" -> "tomatoes", "tornados" -> "tornadoes", "torus" -> "tori", 
 "trousers" -> "trousers", "try" -> "tries", "uterus" -> "uteri", 
 "vertex" -> "vertices", "virus" -> "viruses", "viscus" -> "viscera", 
 "waltz" -> "waltzes", "wash" -> "washes", "watch" -> "watches", 
 "wharf" -> "wharves", "wheat" -> "wheat", "wife" -> "wives", 
 "wolf" -> "wolves", "zero" -> "zeroes", "adman" -> "admen", 
 "aircraftman" -> "aircraftmen", "airman" -> "airmen", 
 "airwoman" -> "airwomen", "alderman" -> "aldermen", 
 "anchorman" -> "anchormen", "angelfish" -> "angelfish", 
 "antihero" -> "antiheroes", "aphelion" -> "aphelia", 
 "artilleryman" -> "artillerymen", "assemblyman" -> "assemblymen", 
 "assemblywoman" -> "assemblywomen", "aviatrix" -> "aviatrices", "backwoodsman" -> "backwoodsmen", 
 "bandsman" -> "bandsmen", "bargeman" -> "bargemen", "barman" -> "barmen", 
 "batman" -> "batmen", "batsman" -> "batsmen", "bellman" -> "bellmen", 
 "bluefish" -> "bluefish", "boatman" -> "boatmen", "bogeyman" -> "bogeymen", 
 "bondman" -> "bondmen", "bondsman" -> "bondsmen", 
 "bondwoman" -> "bondwomen", "bowman" -> "bowmen", "brakeman" -> "brakemen", 
 "bream" -> "bream", "bucktooth" -> "buckteeth", "bushman" -> "bushmen", 
 "businessman" -> "businessmen", "businesswoman" -> "businesswomen", 
 "cafe" -> "cafes", "cameraman" -> "cameramen", 
 "candelabrum" -> "candelabra", "carafe" -> "carafes", "carp" -> "carp", 
 "catfish" -> "catfish", "cattleman" -> "cattlemen", 
 "cavalryman" -> "cavalrymen", "caveman" -> "cavemen", "chafe" -> "chafes", 
 "chairman" -> "chairmen", "chairwoman" -> "chairwomen", 
 "charwoman" -> "charwomen", "chessman" -> "chessmen", "chickenpox" -> "chickenpox", 
 "children" -> "children", "churchman" -> "churchmen", 
 "clansman" -> "clansmen", "clanswoman" -> "clanswomen", 
 "clergyman" -> "clergymen", "clubfoot" -> "clubfeet", 
 "coachman" -> "coachmen", "codex" -> "codices", "codfish" -> "codfish", 
 "committeeman" -> "committeemen", "committeewoman" -> "committeewomen", 
 "congressman" -> "congressmen", "congresswoman" -> "congresswomen", 
 "councilman" -> "councilmen", "councilwoman" -> "councilwomen", 
 "counterman" -> "countermen", "countryman" -> "countrymen", 
 "countrywoman" -> "countrywomen", "cowman" -> "cowmen", 
 "cowpox" -> "cowpox", "craftsman" -> "craftsmen", "crayfish" -> "crayfish", 
 "crewman" -> "crewmen", "cuttlefish" -> "cuttlefish", 
 "cybercafe" -> "cybercafes", "dairyman" -> "dairymen", 
 "daughter-in-law" -> "daughters-in-law", "deliveryman" -> "deliverymen", 
 "dogfish" -> "dogfish", "dominatrix" -> "dominatrices", 
 "doorman" -> "doormen", "dormouse" -> "dormice", "draftsman" -> "draftsmen", 
 "dustman" -> "dustmen", "dutchman" -> "dutchmen", "elk" -> "elk", 
 "englishman" -> "englishmen", "englishwoman" -> "englishwomen", 
 "erebus" -> "erebus", "euphonium" -> "euphoniums", 
 "executrix" -> "executrices", "eyetooth" -> "eyeteeth", 
 "father-in-law" -> "fathers-in-law", "ferryman" -> "ferrymen", 
 "fieldsman" -> "fieldsmen", "fife" -> "fifes", "fireman" -> "firemen", 
 "fisherman" -> "fishermen", "flatfish" -> "flatfish", 
 "flatfoot" -> "flatfeet", "flounder" -> "flounder", 
 "flyleaf" -> "flyleaves", "footman" -> "footmen", "forefoot" -> "forefeet", 
 "foreman" -> "foremen", "forewoman" -> "forewomen", 
 "freedman" -> "freedmen", "freeman" -> "freemen", 
 "frenchman" -> "frenchmen", "frenchwoman" -> "frenchwomen", 
 "freshman" -> "freshmen", "frogman" -> "frogmen", 
 "frontiersman" -> "frontiersmen", "frontierswoman" -> "frontierswomen", 
 "garfish" -> "garfish", "gasman" -> "gasmen", "gateau" -> "gateaux", 
 "gentleman" -> "gentlemen", "gentlewoman" -> "gentlewomen", 
 "goldfish" -> "goldfish", "graffiti" -> "graffiti", 
 "groomsman" -> "groomsmen", "groundsman" -> "groundsmen", 
 "guardsman" -> "guardsmen", "gulf" -> "gulfs", "gunman" -> "gunmen", 
 "handyman" -> "handymen", "hangman" -> "hangmen", "headman" -> "headmen", 
 "headsman" -> "headsmen", "helmsman" -> "helmsmen", 
 "henchman" -> "henchmen", "herdsman" -> "herdsmen", 
 "highwayman" -> "highwaymen", "homework" -> "homework", 
 "horseman" -> "horsemen", "horsewoman" -> "horsewomen", 
 "houseman" -> "housemen", "huntsman" -> "huntsmen", 
 "husbandman" -> "husbandmen", "iceman" -> "icemen", 
 "infantryman" -> "infantrymen", "irishman" -> "irishmen", 
 "irishwoman" -> "irishwomen", "jellyfish" -> "jellyfish", 
 "journeyman" -> "journeymen", "juryman" -> "jurymen", 
 "jurywoman" -> "jurywomen", "killdeer" -> "killdeer", "kine" -> "kine", 
 "kinsman" -> "kinsmen", "kinswoman" -> "kinswomen", 
 "landsman" -> "landsmen", "larynx" -> "larynges", 
 "laundryman" -> "laundrymen", "laundrywoman" -> "laundrywomen", 
 "lawman" -> "lawmen", "layman" -> "laymen", "lineman" -> "linemen", 
 "linesman" -> "linesmen", "linkman" -> "linkmen", 
 "liveryman" -> "liverymen", "longshoreman" -> "longshoremen", 
 "lumberman" -> "lumbermen", "lungfish" -> "lungfish", 
 "mackerel" -> "mackerel", "madman" -> "madmen", "madwoman" -> "madwomen", 
 "mailman" -> "mailmen", "marksman" -> "marksmen", "maxis" -> "maxis", 
 "meninx" -> "meninges", "merchantman" -> "merchantmen", 
 "merman" -> "mermen", "middleman" -> "middlemen", 
 "midshipman" -> "midshipmen", "militiaman" -> "militiamen", 
 "milkman" -> "milkmen", "mother-in-law" -> "mothers-in-law", 
 "motorman" -> "motormen", "muscleman" -> "musclemen", 
 "needlewoman" -> "needlewomen", "newsman" -> "newsmen", 
 "newspaperman" -> "newspapermen", "newspaperwoman" -> "newspaperwomen", 
 "newswoman" -> "newswomen", "nobleman" -> "noblemen", 
 "noblewoman" -> "noblewomen", "norseman" -> "norsemen", 
 "nurseryman" -> "nurserymen", "oarsman" -> "oarsmen", 
 "oarswoman" -> "oarswomen", "oilman" -> "oilmen", 
 "ombudsman" -> "ombudsmen", "oxen" -> "oxen", "patrolman" -> "patrolmen", 
 "penman" -> "penmen", "pharynx" -> "pharynges", "pitchman" -> "pitchmen", 
 "plainclothesman" -> "plainclothesmen", "plainsman" -> "plainsmen", 
 "plowman" -> "plowmen", "policeman" -> "policemen", 
 "policewoman" -> "policewomen", "postman" -> "postmen", "pox" -> "pox", 
 "pressman" -> "pressmen", "psis" -> "psis", "railwayman" -> "railwaymen", 
 "reindeer" -> "reindeer", "repairman" -> "repairmen", 
 "riffraff" -> "riffraff", "rifleman" -> "riflemen", "safe" -> "safes", 
 "sailfish" -> "sailfish", "salesman" -> "salesmen", 
 "saleswoman" -> "saleswomen", "salmon" -> "salmon", "sandman" -> "sandmen", 
 "scotchman" -> "scotchmen", "scotchwoman" -> "scotchwomen", 
 "scotsman" -> "scotsmen", "scotswoman" -> "scotswomen", 
 "seaman" -> "seamen", "selectman" -> "selectmen", "serf" -> "serfs", 
 "serviceman" -> "servicemen", "shellfish" -> "shellfish", 
 "showman" -> "showmen", "shrimp" -> "shrimp", "signalman" -> "signalmen", 
 "silverfish" -> "silverfish", "sister-in-law" -> "sisters-in-law", 
 "smallpox" -> "smallpox", "snowman" -> "snowmen", 
 "son-in-law" -> "sons-in-law", "spaceman" -> "spacemen", 
 "spearfish" -> "spearfish", "spermatozoon" -> "spermatozoa", 
 "splayfoot" -> "splayfeet", "spokesman" -> "spokesmen", 
 "spokeswoman" -> "spokeswomen", "sportsman" -> "sportsmen", 
 "sportswoman" -> "sportswomen", "stableman" -> "stablemen", 
 "starfish" -> "starfish", "statesman" -> "statesmen", 
 "stateswoman" -> "stateswomen", "status" -> "status", 
 "steersman" -> "steersmen", "strafe" -> "strafes", 
 "strongman" -> "strongmen", "sunfish" -> "sunfish", 
 "superman" -> "supermen", "surf" -> "surfs", "swordfish" -> "swordfish", 
 "swordsman" -> "swordsmen", "taxis" -> "taxis", "taxman" -> "taxmen", 
 "testatrix" -> "testatrices", "titmouse" -> "titmice", 
 "townsman" -> "townsmen", "tradesman" -> "tradesmen", 
 "trainman" -> "trainmen", "trencherman" -> "trenchermen", 
 "tribesman" -> "tribesmen", "tum" -> "tums", "tuna" -> "tuna", 
 "turf" -> "turfs", "underclassman" -> "underclassmen", 
 "valium" -> "valiums", "vestryman" -> "vestrymen", 
 "washerwoman" -> "washerwomen", "watchman" -> "watchmen", 
 "weakfish" -> "weakfish", "weatherman" -> "weathermen", 
 "webfoot" -> "webfeet", "welshman" -> "welshmen", 
 "whitefish" -> "whitefish", "whiting" -> "whiting", 
 "wildebeest" -> "wildebeest", "woodlouse" -> "woodlice", 
 "woodman" -> "woodmen", "woodsman" -> "woodsmen", 
 "workingman" -> "workingmen", "workman" -> "workmen", 
 "yachtsman" -> "yachtsmen", "yachtswoman" -> "yachtswomen", 
 "yardman" -> "yardmen", "yeoman" -> "yeomen", "zebus" -> "zebus", 
 "alluvium" -> "alluvia", "arboretum" -> "arboreta", 
 "auditorium" -> "auditoria", "blackfoot" -> "blackfoot", "bubo" -> "buboj", 
 "cambium" -> "cambia", "colloquium" -> "colloquia", 
 "condominium" -> "condominia", "crematorium" -> "crematoria", 
 "cumulonimbus" -> "cumulonimbi", "delirium" -> "deliria", 
 "delphinium" -> "delphinia", "desideratum" -> "desiderata", 
 "elysium" -> "elysia", "encomium" -> "encomiums", "factotum" -> "factotums", 
 "frustum" -> "frusta", "geranium" -> "gerania", "harmonium" -> "harmonia", 
 "iambus" -> "iambi", "incubus" -> "incubi", "millennium" -> "millenia", 
 "moratorium" -> "moratoria", "nasturtium" -> "nasturtia", 
 "navajo" -> "navajo", "nimbus" -> "nimbi", "omnibus" -> "omnibi", 
 "perihelion" -> "perihelia", "planetarium" -> "planetaria", 
 "podium" -> "podia", "premium" -> "premiums", "proscenium" -> "proscenia", 
 "quadrennium" -> "quadrennia", "rectum" -> "recta", 
 "retrovirus" -> "retroviri", "rhombus" -> "rhombi", 
 "sanatorium" -> "sanatoria", "sanctum" -> "sancta", 
 "sanitarium" -> "sanitaria", "sis" -> "sises", "succubus" -> "succubi", 
 "symposium" -> "symposia", "terrarium" -> "terraria", 
 "vivarium" -> "vivaria", "abaculus" -> "abaculi", "abacus" -> "abaci", 
 "abbacy" -> "abbacies", "abnormity" -> "abnormities", 
 "acalephan" -> "acalephans", "acanthus" -> "acanthi", "acarus" -> "acari", 
 "accessary" -> "accessaries", "accipiter" -> "accipiters", 
 "acicula" -> "aciculae", "acinus" -> "acini", "acrimony" -> "acrimonies", 
 "acroterium" -> "acrotplwia", "actinia" -> "actiniae", 
 "aculeus" -> "aculei", "admiralty" -> "admiralties", "agama" -> "agamas", 
 "agami" -> "agamis", "agape" -> "agapae", "agendum" -> "agenda", 
 "agio" -> "agios", "agon" -> "agones", "ai" -> "ais", 
 "alabastrum" -> "alabastra", "albugo" -> "albugines", 
 "alcarraza" -> "alcarrazas", "alkali" -> "alkalies", 
 "almonry" -> "almonries", "alveary" -> "alvearies", "alveolus" -> "alveoli", 
 "alveus" -> "alvei", "ambo" -> "ambos", "ambry" -> "ambries", 
 "ambulacrum" -> "ambulacra", "amity" -> "amities", "amorpha" -> "amorphas", 
 "amphibology" -> "amphibologies", "amphiboly" -> "amphibolies", 
 "amphictyony" -> "amphictyonies", "amphora" -> "amophorae", 
 "ampulla" -> "ampullae", "anaptychus" -> "anaptichi", 
 "anastomosis" -> "anastomoses", "anatifa" -> "anatifae", 
 "ancon" -> "ancones", "animalculum" -> "animalcula", "animus" -> "animi", 
 "annulus" -> "annuli", "ansa" -> "ansae", "anta" -> "antae", 
 "anthelion" -> "anthelia", "antheridium" -> "antheridiums", 
 "antichthon" -> "antichthones", "anticlinorium" -> "anticlinoria", 
 "antilogy" -> "antilogies", "antinomy" -> "antinomies", 
 "antiphony" -> "antiphonies", "antlia" -> "antilae", "antrum" -> "antra", 
 "apathy" -> "apathies", "aphis" -> "aphides", "apode" -> "apodes", 
 "aponeurosis" -> "aponeuroses", "aporia" -> "aporias", 
 "apothecium" -> "apothecia", "appetency" -> "appetencies", 
 "aquila" -> "aquilae", "arango" -> "arangoes", "arcanum" -> "arcana", 
 "areola" -> "areolae", "aridity" -> "aridities", "armilla" -> "armillae", 
 "articulus" -> "articuli", "aruspex" -> "aruspices", "as" -> "asses", 
 "ascarid" -> "ascarides", "ascidium" -> "ascidia", 
 "ascococcus" -> "ascococci", "ascus" -> "asci", 
 "aspersorium" -> "aspplwsoria", "assiduity" -> "assiduities", 
 "athenaeum" -> "athenaea", "atrium" -> "atria", "axilla" -> "axillae", 
 "bacchant" -> "bacchantes", "bacchius" -> "bacchii", 
 "ballista" -> "ballist", "bandeau" -> "bandeaux", 
 "bastinado" -> "bastinadoes", "bateau" -> "bateaux", "batz" -> "batzen", 
 "betony" -> "betonies", "bias" -> "biases", "bijou" -> "bijoux", 
 "bistoury" -> "bistouries", "blastema" -> "blastemas", 
 "blenny" -> "blennies", "bogy" -> "bogies", "bolus" -> "boluses", 
 "bombolo" -> "bomboloes", "bonmot" -> "bonsmots", "vivant" -> "vivants", 
 "booly" -> "boolies", "bosh" -> "boshes", "botany" -> "botanies", 
 "bowery" -> "bowerie", "boyau" -> "boyaus", "brahmin" -> "brahmans", 
 "branchia" -> "branchiae", "bravado" -> "bravadoes", 
 "brettice" -> "brettices", "brevity" -> "brevities", 
 "bribery" -> "briberies", "bucranium" -> "bucrania", 
 "buffoonery" -> "buffooneries", "bugloss" -> "buglosses", 
 "bullary" -> "bullaries", "bumbelo" -> "bumbeloes", "bursch" -> "burschen", 
 "caecum" -> "caeca", "calamus" -> "calami", "calcar" -> "calcaria", 
 "calculus" -> "calcul", "calico" -> "calicoes", "calx" -> "calces", 
 "canaliculus" -> "canaliculi", "cantharis" -> "cantharides", 
 "canthus" -> "canthi", "capitulary" -> "capitularies", 
 "capoch" -> "capoches", "caput" -> "capita", "carbonado" -> "carbonadoes", 
 "carbonaro" -> "carbonari", "carib" -> "caries", "carolus" -> "caroli", 
 "carpale" -> "carpalia", "carpus" -> "carpi", "cartouch" -> "cartouche", 
 "cartulary" -> "cartularies", "caryopsis" -> "caryopses", 
 "castellany" -> "castellanies", "catalysis" -> "catalyse", 
 "catena" -> "catene", "cathetus" -> "catheti", "catso" -> "catsos", 
 "caudex" -> "caudexes", "cauliculus" -> "caulicul", "caulis" -> "caules", 
 "cautery" -> "cauteries", "cento" -> "centos", "centrum" -> "centra", 
 "centumvir" -> "centumviri", "chalaza" -> "chalazae", 
 "chalcedony" -> "chalcedonies", "chansonnette" -> "chansonnettes", 
 "chapellany" -> "chapellanies", "cheiropterygium" -> "cheiropterygia", 
 "chela" -> "chelae", "chelicera" -> "chelicer", "cheval" -> "chevaux", 
 "chintz" -> "chintzes", "chlamys" -> "chlamydes", 
 "chondroma" -> "chondromas", "choragus" -> "choragi", 
 "chorepiscopus" -> "chorepiscopi", "choriambus" -> "choriambi", 
 "chorus" -> "choruses", "chromo" -> "chromos", "chrysalis" -> "chrysalides", 
 "ciborium" -> "ciboria", "cicatrix" -> "cicatrices", 
 "cicisbeo" -> "cicisbei", "cimex" -> "cimices", "cippus" -> "cippi", 
 "cirrus" -> "cirri", "claustrum" -> "claustra", "clavis" -> "claves", 
 "clavy" -> "clavies", "clemency" -> "clemencies", "clivity" -> "clivities", 
 "cloaca" -> "cloacae", "clypeus" -> "clypei", "cnida" -> "cnidae", 
 "coagulum" -> "coagula", "coccobacterium" -> "coccobacteria", 
 "coccus" -> "cocci", "coccyx" -> "coccyges", "cognoscente" -> "cognoscenti", 
 "collum" -> "colla", "collyrium" -> "collyria", "colossus" -> "colossi", 
 "columbarium" -> "columbari", "columbary" -> "columbaries", 
 "colure" -> "colures", "coly" -> "colies", "comedo" -> "comedones", 
 "comity" -> "comities", "commandery" -> "commanderies", 
 "commonalty" -> "commonalties", "compendium" -> "compendia", 
 "complice" -> "complices", "complicity" -> "complicities", 
 "concetto" -> "concetti", "conditory" -> "conditories", 
 "condottiere" -> "condottieri", "conferva" -> "confervae", 
 "congiary" -> "congiaries", "conidium" -> "conida", 
 "contango" -> "contangoes", "contrariety" -> "contrarieties", 
 "contumacy" -> "contumacies", "conversazione" -> "conversazioni", 
 "convexity" -> "convexities", "convolvulus" -> "convoluluses", 
 "coparcenary" -> "coparcenaries", "corby" -> "corbies", "dado" -> "dadoed", 
 "dago" -> "dagoes", "daimio" -> "daimios", "decahedron" -> "decahedra", 
 "decemvir" -> "decemviri", "decennary" -> "decennaries", 
 "decennium" -> "decennia", "decury" -> "decuries", "demy" -> "demies", 
 "denarius" -> "denarii", "dentiroster" -> "dentirostres", 
 "depositary" -> "depositaries", "desperado" -> "desperadoes", 
 "dey" -> "deys", "dialysis" -> "dialyses", "dictum" -> "dicta", 
 "diesis" -> "dieses", "juridicus" -> "dies", 
 "differentia" -> "differentiae", "dilogy" -> "dilogies", 
 "diluvium" -> "diluvia", "diplococcus" -> "diplococci", 
 "dipody" -> "dipodies", "discobolus" -> "discoboli", "discus" -> "disci", 
 "dispathy" -> "dispathies", "diverticulum" -> "diverticula", 
 "domesman" -> "domesmen", "dominus" -> "domini", "dooly" -> "doolies", 
 "doxy" -> "doxies", "dracunculus" -> "dracunculi", 
 "dragoman" -> "dragomans", "dropsy" -> "dropsies", "drosky" -> "droskies", 
 "dryas" -> "dryades", "dubiety" -> "dubieties", 
 "dubiosity" -> "dubiosities", "duumvir" -> "duumviri", 
 "dvergr" -> "dvergar", "ebriety" -> "ebrieties", "ecdysis" -> "ecdyses", 
 "echinus" -> "echini", "ecthoreum" -> "ecthorea", "ecthyma" -> "ecthymata", 
 "ectobronchium" -> "ectobronchia", "ectozooen" -> "ectozoa", 
 "edda" -> "eddas", "effeminacy" -> "effeminacies", 
 "effluvium" -> "effluvia", "effrontery" -> "effronteries", 
 "electricity" -> "electricities", "electrophorus" -> "electrophori", 
 "electuary" -> "electuaries", "elench" -> "elenchs", "elytrum" -> "elytra", 
 "embolus" -> "emboli", "emeritus" -> "emeriti", "emporium" -> "emporia", 
 "emunctory" -> "emunctories", "encrinus" -> "encrini", 
 "endorhiza" -> "endorhizae", "endothelium" -> "endothelia", 
 "endysis" -> "endyses", "entirety" -> "entireness", 
 "entobronchium" -> "entobronchia", "entomology" -> "entomologies", 
 "entoplastron" -> "entoplastra", "entosternum" -> "entosterna", 
 "entozooen" -> "entozoa", "epenthesis" -> "epentheses", 
 "ephemeris" -> "ephemerides", "ephemeron" -> "ephemera", 
 "ephor" -> "ephori", "epichirema" -> "epichiremata", 
 "epimeron" -> "epimera", "epiphysis" -> "epiphyses", 
 "epiplastron" -> "epiplastra", "epiplooen" -> "epiploa", 
 "epipodiale" -> "epipodialia", "epipodium" -> "epipodia", 
 "epipubis" -> "epipubes", "episternum" -> "episterna", 
 "epithalamium" -> "epithalamia", "epithelium" -> "epithelia", 
 "epizooen" -> "epizoa", "equilibrium" -> "equilibria", 
 "equisetum" -> "equiseta", "erf" -> "erven", "erinys" -> "erinyes", 
 "eruca" -> "erucae", "eskimo" -> "eskimos", "esquimau" -> "esquimaux", 
 "essene" -> "essenes", "estufa" -> "estufas", "etymon" -> "a", 
 "eulogium" -> "eulogiums", "euphony" -> "euphonies", 
 "exanthema" -> "exanthemata", "exedra" -> "exedrae", "exequy" -> "exequies", 
 "officio" -> "ex", "exordium" -> "exordia", "exorhiza" -> "exorhize", 
 "fabliau" -> "fabliaux", "factum" -> "facta", "fasciculus" -> "fasciculi", 
 "fasciola" -> "fasciolae", "faunus" -> "fauni", "faux" -> "fauces", 
 "fellah" -> "ar", "fenestra" -> "fenestrae", "fetus" -> "fetuses", 
 "fiasco" -> "fiascoes", "fibulare" -> "fibularia", "fico" -> "ficoes", 
 "fimbria" -> "fimbriae", "finality" -> "finalities", 
 "fingrigo" -> "fingrigos", "firman" -> "firmans", "fitch" -> "fitches", 
 "flagellum" -> "flagella", "flagrancy" -> "flagrancies", 
 "flambeau" -> "flambeaus", "flamen" -> "flamens", "flanch" -> "flanches", 
 "flattery" -> "flatteries", "flitch" -> "flitches", "flo" -> "flon", 
 "flocculus" -> "flocculi", "floccus" -> "flocci", "folium" -> "folia", 
 "fomes" -> "fomites", "foppery" -> "fopperies", "foramen" -> "foramina", 
 "formulary" -> "formularies", "fornix" -> "fornices", 
 "foundery" -> "founderies", "fovea" -> "foveae", "foveola" -> "foveolae", 
 "fovilla" -> "fovillae", "fraenulum" -> "fraenula", "frenum" -> "frena", 
 "fretum" -> "freta", "frigidarium" -> "frigidaria", 
 "fructuary" -> "fructuaries", "frugality" -> "frugalities", 
 "fruitery" -> "fruiteries", "fucus" -> "fuci", "fumado" -> "fumades", 
 "funiculus" -> "funiculi", "galago" -> "galagos", "ganglion" -> "ganglia", 
 "gas" -> "gases", "gastrula" -> "gastrul", "gaudy" -> "gaudie", 
 "gemma" -> "gemmae", "generatrix" -> "generatrices", "gens" -> "gentes", 
 "gentoo" -> "gentoos", "germen" -> "germens", "gigerium" -> "gigeria", 
 "ginglymus" -> "ginglymi", "ginkgo" -> "ginkgoes", "glabella" -> "glabell", 
 "glabellum" -> "glabella", "gladiolus" -> "gladioli", "gladius" -> "gladii", 
 "glans" -> "glandes", "gleeman" -> "gleemen", 
 "globigerina" -> "globigerinae", "glochidium" -> "glochidia", 
 "glomerulus" -> "glomeruli", "glossa" -> "gloss", 
 "gluttony" -> "gluttonies", "gnathidium" -> "gnathidia", "goaf" -> "goafs", 
 "goby" -> "gobies", "gonangium" -> "gonangia", "gonidium" -> "gonidia", 
 "gonoblastidium" -> "gonoblastidia", "gonotheca" -> "gonothec", 
 "gorfly" -> "gorflies", "gorgoneion" -> "gorgoneia", 
 "gradino" -> "gradinos", "grampus" -> "grampuses", "guanaco" -> "guanacos", 
 "guano" -> "guanos", "gumma" -> "gummas", "gyrus" -> "gyri", 
 "haematozooen" -> "haematozoa", "haggada" -> "haggadoth", 
 "hamadryad" -> "hamadryades", "haustellum" -> "haustella", 
 "haustorium" -> "haustoria", "hectocotylus" -> "hectocotyli", 
 "heddle" -> "heddles", "helix" -> "helices", 
 "hemapophysis" -> "hemapophyses", "hemina" -> "heminae", 
 "henry" -> "henries", "hepatica" -> "hepaticae", "herbarium" -> "herbaria", 
 "herma" -> "hermae", "hetman" -> "hetmans", "hexahedron" -> "hexahedra", 
 "hindu" -> "hindoos", "hinny" -> "hinnies", "homunculus" -> "homunculi", 
 "hospitality" -> "hospitalities", "humerus" -> "humeri", 
 "humility" -> "humilities", "hydrocaulus" -> "hydrocauli", 
 "hydromedusa" -> "hydromedusae", "hydrophyllium" -> "hydrophyllia", 
 "hydrorhiza" -> "hydrorhizae", "hydrotheca" -> "hydrothecae", 
 "hymenium" -> "hymenia", "hypanthium" -> "hypanthia", 
 "hypapophysis" -> "hypapophyles", "hyperapophysis" -> "hyperapophyses", 
 "hypoarion" -> "hypoaria", "hypochondrium" -> "hypochondria", 
 "hypocleidium" -> "hypocleida", "hypogeum" -> "hypogea", 
 "hypoplastron" -> "hypoplastra", "hypoptilum" -> "hypoptila", 
 "hyporadius" -> "hyporadii", "hyporhachis" -> "hyporhachides", 
 "hypostasis" -> "hypostases", "hyposternum" -> "hyposterna", 
 "hypotarsus" -> "hypotarsi", "ianthina" -> "ianthinae", 
 "ichthyosaurus" -> "ichthyosauri", "idiocrasy" -> "idiocrasies", 
 "idiopathy" -> "idiopathies", "idolatry" -> "idolatries", 
 "fatuus" -> "fatui", "illiteracy" -> "illiteracies", "imago" -> "imagoes", 
 "imbrocado" -> "imbrocadoes", "immateriality" -> "immaterialities", 
 "immortality" -> "immortalities", "immortelle" -> "immortelles", 
 "importunity" -> "importunities", "improvvisatore" -> "improvvisatori", 
 "improvvisatrice" -> "improvvisatrici", "inamorato" -> "inamoratos", 
 "incensory" -> "incensories", "inclemency" -> "inclemencies", 
 "incommodity" -> "incommodities", "incunabulum" -> "incunabula", 
 "indigo" -> "indigoes", "individuality" -> "individualities", 
 "inductorium" -> "inductoria", "indusium" -> "indu", "infula" -> "infule", 
 "infundibulum" -> "infundibula", "injuria" -> "injurie", 
 "insessor" -> "insessores", "intangibility" -> "intangibilities", 
 "intendancy" -> "intendancies", "interleaf" -> "interleaves", 
 "intermedium" -> "intermedia", "internuncio" -> "internuncios", 
 "interrex" -> "interreges", "intervallum" -> "intervalla", 
 "invitatory" -> "invitatories", "involucellum" -> "involucella", 
 "involucrum" -> "involucra", "io" -> "ios", "isthmus" -> "isthmuses", 
 "jacobus" -> "jacobuses", "janizary" -> "janizaries", "jess" -> "jesses", 
 "jingo" -> "jingoes", "jinnee" -> "jinn", "jo" -> "joes", 
 "jugulum" -> "jugula", "jugum" -> "juga", "july" -> "julies", 
 "jungermannia" -> "jungermanniae", "juno" -> "junos", "junto" -> "juntos", 
 "juvenility" -> "juvenilities", "kavass" -> "kavasse", "kee" -> "cow", 
 "kelpy" -> "kelpies", "kersey" -> "kerseys", "labarum" -> "labara", 
 "labellum" -> "labella", "labium" -> "labia", "labrum" -> "labra", 
 "lacinia" -> "laciniae", "lacinula" -> "lacinulae", 
 "lacunar" -> "lacunaria", "ladino" -> "ladinos", "lagena" -> "lagenae", 
 "lamella" -> "lamellae", "lapis" -> "lapides", "laquear" -> "laquearia", 
 "lar" -> "lares", "latibulum" -> "latibula", 
 "lectica" -> "lecticae", "legumen" -> "legumens", 
 "lenticula" -> "lenticulae", "lex" -> "leges", 
 "liberality" -> "liberalities", "libra" -> "librae", "lied" -> "lieder", 
 "lienculus" -> "lienculi", "ligula" -> "ligulae", "lingua" -> "linguae", 
 "lira" -> "lire", "liriodendron" -> "liriodendra", 
 "literatus" -> "literati", "lituus" -> "litui", "loculus" -> "loculi", 
 "loma" -> "lomata", "longiroster" -> "longirosters", "looby" -> "loobies", 
 "lophosteon" -> "lophostea", "lorica" -> "loricae", "lory" -> "lories", 
 "lunula" -> "lunulae", "lustrum" -> "lustra", "lytta" -> "lyttae", 
 "macula" -> "maculae", "madame" -> "mesdames", 
 "magistracy" -> "magistracies", "magnifico" -> "magnificoes", 
 "mala" -> "malum", "malleolus" -> "malleoli", "malleus" -> "mallei", 
 "malum" -> "mala", "mamma" -> "mammae", "mammilla" -> "mammilae", 
 "manteau" -> "manteaus", "manubrium" -> "manubria", 
 "marsupium" -> "marsupia", "mastery" -> "masteries", 
 "maxilla" -> "maxillae", "medicornu" -> "medicornua", "medius" -> "medii", 
 "melisma" -> "melismata", "mendacity" -> "mendacities", 
 "menstruum" -> "menstrua", "mesobronchium" -> "mesobronchia", 
 "mesopodiale" -> "mesopodialia", "metabasis" -> "metabases", 
 "metalepsis" -> "metalepses", "metapodiale" -> "metapodialia", 
 "metapodium" -> "metapodia", "metapophysis" -> "metapophyses", 
 "metatarsus" -> "metatarsi", "micella" -> "micellae", 
 "micrococcus" -> "micrococci", "midrash" -> "midrashim", 
 "milliary" -> "milliaries", "mina" -> "minae", 
 "mineralogy" -> "mineralogies", "minimus" -> "minimi", "missa" -> "missae", 
 "modiolus" -> "modioli", "modius" -> "modii", "modulus" -> "moduli", 
 "modus" -> "modi", "momentum" -> "momenta", "monopteron" -> "monoptera", 
 "monseigneur" -> "messeigneurs", "monsieur" -> "messieurs", 
 "monsignore" -> "monsignors", "morula" -> "morulae", 
 "mulatto" -> "mulattoes", "mummery" -> "mummeries", "murex" -> "murices", 
 "musa" -> "musae", "musca" -> "muscae", "mussulman" -> "mussulmans", 
 "mutandum" -> "mutanda", "myeloplax" -> "myeloplaces", 
 "myocomma" -> "myocommas", "myxoma" -> "myxomata", "napery" -> "naperies", 
 "nauplius" -> "nauplii", "nautilus" -> "nautili", 
 "necrology" -> "necrologies", "necropolis" -> "necropolises", 
 "nectary" -> "nectaries", "nectocalyx" -> "nectocalyces", 
 "nemathecium" -> "nemathecia", "nephridium" -> "nephridia", 
 "nereid" -> "nereides", "nereis" -> "nereides", 
 "neurapophysis" -> "neurapophyses", "nidus" -> "nidi", "noddy" -> "noddies", 
 "northman" -> "northmen", "notandum" -> "notanda", 
 "notopodium" -> "notopodia", "notum" -> "nota", "nucellus" -> "nucelli", 
 "nucha" -> "nuch", "nucleolus" -> "nucleoli", "nudity" -> "nudities", 
 "nullity" -> "nullities", "nuncius" -> "nuncii", "nympha" -> "nymph", 
 "obelus" -> "obeli", "oblatum" -> "oblata", "obliquity" -> "obliquities", 
 "oblongum" -> "oblonga", "obolus" -> "oboli", "observandum" -> "observanda", 
 "occiput" -> "occipita", "ocellus" -> "ocelli", "ochrea" -> "ochreaee", 
 "oculus" -> "oculi", "omentum" -> "omenta", "ommateum" -> "ommatea", 
 "ommatidium" -> "ommatidia", "onager" -> "onagers", "ooecium" -> "ooecia", 
 "operculum" -> "opercula", "ophidion" -> "ophidia", "opus" -> "opera", 
 "opusculum" -> "opuscula", "orchis" -> "orchises", "orrery" -> "orreries", 
 "ort" -> "orts", "orthostichy" -> "orthostichies", "os" -> "ossa", 
 "osculatrix" -> "osculatrixes", "osculum" -> "oscula", 
 "osmanli" -> "osmanlis", "osmaterium" -> "osmateria", 
 "osphradium" -> "osphradia", "ossiculum" -> "ossicula", 
 "osteocomma" -> "osteocommas", "osteoma" -> "osteomas", 
 "osteosarcoma" -> "osteosarcomas", "ostium" -> "ostia", 
 "otary" -> "otaries", "ovarium" -> "ovaria", "ovococcus" -> "ovococci", 
 "ovulum" -> "ovula", "padrone" -> "padrones", "pagina" -> "paginae", 
 "palama" -> "palamme", "paleola" -> "paleolae", "palestra" -> "palestrae", 
 "palmarium" -> "palmaria", "palpebra" -> "palpebrae", "palpus" -> "palpi", 
 "paludina" -> "paludinae", "palulus" -> "paluli", "palus" -> "pali", 
 "panful" -> "panfuls", "papilla" -> "papillae", "papilloma" -> "papillomas", 
 "papula" -> "papulae", "papyrus" -> "papyri", 
 "parabronchium" -> "parabronchia", "paradactylum" -> "paradactyla", 
 "parados" -> "paradoses", "paraglossa" -> "paraglossae", 
 "paragnathus" -> "paragnathi", "paramo" -> "paramos", 
 "paraphragma" -> "paraphragmata", "paraphysis" -> "paraphyses", 
 "parapleura" -> "parapleurae", "parapodium" -> "parapodia", 
 "parapophysis" -> "parapophyses", "parapterum" -> "paraptera", 
 "parascenium" -> "parascenia", "paraselene" -> "paraselenae", 
 "parathesis" -> "paratheses", "parhelion" -> "parhelia", 
 "paries" -> "parietes", "patagium" -> "patagia", 
 "patellula" -> "patellulae", "paterfamilias" -> "pateresfamilias", 
 "paugy" -> "paugies", "paxillus" -> "paxilli", "pease" -> "peasen", 
 "peccadillo" -> "peccadilloes", "pectus" -> "pectora", 
 "pedary" -> "pedaries", "pedicellaria" -> "pedicellariae", 
 "pediculus" -> "pediculi", "pedipalpus" -> "pedipalpi", 
 "pelma" -> "pelmata", "pelta" -> "peltae", "penna" -> "pennae", 
 "pennatula" -> "pennatulae", "pensionary" -> "pensionaries", 
 "pentacron" -> "pentacra", "pentecosty" -> "pentecosties", 
 "peri" -> "peris", "perichaetium" -> "perichaetia", 
 "periclinium" -> "periclinia", "periculum" -> "pericula", 
 "peridium" -> "peridia", "perigonium" -> "perigonia", 
 "perigynium" -> "perigynia", "perihelium" -> "perihelia", 
 "periodicity" -> "periodicities", "periostracum" -> "periostraca", 
 "perisoma" -> "perisomata", "perispomenon" -> "perispomena", 
 "peristoma" -> "peristomata", "persona" -> "personae", 
 "perula" -> "perulae", "pes" -> "pedes", "pessulus" -> "pessuli", 
 "petalum" -> "petala", "phacellus" -> "phacelli", "phenix" -> "phenixes", 
 "phiz" -> "phizes", "pholas" -> "pholades", "phosphorus" -> "phosphori", 
 "phratry" -> "phratries", "phyle" -> "phylae", 
 "phyllobranchia" -> "phyllobranciae", "phyllocladium" -> "phyllocladia", 
 "phyllodium" -> "phyllodia", "phylon" -> "phyla", "phylum" -> "phyla", 
 "phyma" -> "phymata", "physiology" -> "physiologies", "phyton" -> "phytons", 
 "phytozooen" -> "phytozoa", "pickaninny" -> "pickaninnies", 
 "picus" -> "pici", "pignus" -> "pignora", "pilentum" -> "pilenta", 
 "pileorhiza" -> "pilorhizae", "pileus" -> "pilei", "pilidium" -> "pildia", 
 "pinax" -> "pinaces", "pinna" -> "pinnae", "pinnula" -> "pinnulae", 
 "pintado" -> "pintadoes", "pipra" -> "pipras", "piracy" -> "piracies", 
 "pistillidium" -> "pistillida", "placitum" -> "placita", 
 "plaga" -> "plagae", "plagiary" -> "plagiaries", "planula" -> "planulae", 
 "plasmodium" -> "plasmodia", "plenty" -> "plenties", "pleopod" -> "pleopoda", 
 "plesiosaurus" -> "plesiosauri", "plethrum" -> "plethra", 
 "pleura" -> "pleurae", "pleurapophysis" -> "pleurapophyses", 
 "pleurobranchia" -> "pleuroeranchiae", "pleuron" -> "pleura", 
 "pleurotoma" -> "pleurotomae", "pluma" -> "plumae", 
 "plumularia" -> "plumularias", "pluteus" -> "plutei", 
 "podarthrum" -> "podarthra", "podetium" -> "podetia", 
 "podobranchia" -> "podobranchle", "podotheca" -> "podothecae", 
 "podura" -> "podurae", "pollex" -> "pollices", "pollinium" -> "pollinia", 
 "polyacron" -> "polyacra", "polyanthus" -> "polyanthuses", 
 "polypary" -> "polyparies", "polyporus" -> "polypori", 
 "polypus" -> "polypi", "polyzoarium" -> "polyzoaria", 
 "polyzooen" -> "polyzoa", "pomey" -> "pomeys", 
 "pompelmous" -> "pompelmouses", "ponderosity" -> "ponderosities", 
 "pons" -> "pontes", "pontifex" -> "pontifices", 
 "popularity" -> "popularities", "porphyry" -> "porphyries", 
 "porta" -> "portae", "portico" -> "porticoes", "postcava" -> "postcavae", 
 "postcornu" -> "postcornua", "postfurca" -> "postfurcae", 
 "postulatum" -> "postulata", "postzygapophysis" -> "postzygapophyses", 
 "pourparty" -> "pourparties", "praecornu" -> "praecornua", 
 "praenomen" -> "praenomens", "praetexta" -> "praetextae", 
 "preceptory" -> "preceptories", "prelacy" -> "prelacies", 
 "premaxilla" -> "premaxillae", "prepollent" -> "prepollice", 
 "prezygapophysis" -> "prezygapophyses", "donna" -> "donnas", 
 "privacy" -> "privacies", "proboscis" -> "proboscides", 
 "procuracy" -> "procuracies", "proglottis" -> "proglottides", 
 "programma" -> "programmata", "prolatum" -> "prolata", 
 "prolegomenon" -> "prolegomena", "proletary" -> "proletaries", 
 "pronotum" -> "pronota", "propagulum" -> "propagula", 
 "properispomenon" -> "properispomena", "prophragma" -> "prophragmata", 
 "propodiale" -> "propodialia", "propodium" -> "propodia", 
 "propterygium" -> "propterygia", "propylaeum" -> "propylaea", 
 "propylon" -> "propyla", "proscolex" -> "proscolices", 
 "prosocoelia" -> "prosocoelle", "prosoma" -> "prosomata", 
 "prostomium" -> "prostomia", "prothallium" -> "prothallia", 
 "prothallus" -> "prothalli", "thyalosoma" -> "prothyalosomata", 
 "protiston" -> "protista", "protonema" -> "protonemata", 
 "protovertebra" -> "protovertebrae", "protozooen" -> "protozoa", 
 "prudery" -> "pruderies", "prytanis" -> "prytanes", 
 "psalterium" -> "psalteria", "pseudobranchia" -> "pseudobranchiae", 
 "pseudofilaria" -> "pseudofilari", "pseudohalter" -> "pseudohalteres", 
 "pseudonavicella" -> "pseudonavicullae", "pseudonavicula" -> 
  "pseudonaviculae", "pseudopupa" -> "pseudopupae", 
 "pseudostoma" -> "pseudostomata", "pseudotinea" -> "pseudotineae", 
 "pseudovary" -> "pseudovaries", "pseudovum" -> "pseudova", 
 "psylla" -> "psyllae", "pterostigma" -> "pterostigmata", 
 "pterygium" -> "pterygia", "pterygopodium" -> "pterygopodia", 
 "pteryla" -> "pterylae", "puerility" -> "puerilities", "pullus" -> "pulli", 
 "pulvillus" -> "pulvilli", "pulvinulus" -> "pulvinuli", 
 "punctilio" -> "punctilios", "pycnidium" -> "pycnidia", 
 "pygidium" -> "pygidia", "pyla" -> "pylae", "pylorus" -> "pylori", 
 "pyramidion" -> "pyramidia", "pyramis" -> "pyramides", 
 "pyrena" -> "pyrenae", "pyrexia" -> "pyrexiae", "pyxidium" -> "pyxidia", 
 "quadra" -> "quadrae", "quadrans" -> "quadrantes", 
 "quadriga" -> "quadrigae", "quiddity" -> "quiddities", 
 "quindecemvir" -> "quindecemviri", "quipu" -> "quipus", 
 "rachis" -> "rachides", "radiale" -> "radialia", "radix" -> "radices", 
 "radula" -> "radulae", "ranchero" -> "rancheros", "rancho" -> "ranchos", 
 "ranunculus" -> "ranunculi", "receptaculum" -> "receptacula", 
 "reticulum" -> "reticula", "retinaculum" -> "retinacula", 
 "retineum" -> "retinea", "retinophora" -> "retiniphorae", 
 "retinula" -> "retinulae", "rex" -> "reges", "rhachis" -> "rhachides", 
 "rhamphotheca" -> "rhamphothecae", "rhinencephalon" -> "rhinencephala", 
 "rhinotheca" -> "rhinothecae", "rhizoma" -> "rhizomata", 
 "rhonchus" -> "rhonchi", "rhopalium" -> "rhopalia", "rima" -> "rimae", 
 "rostellum" -> "rostella", "rostrulum" -> "rostrula", "ruga" -> "rugae", 
 "sacculus" -> "sacculi", "saccus" -> "sacci", "sacellum" -> "sacella", 
 "sagum" -> "saga", "salix" -> "salices", "salpa" -> "salpae", 
 "sanctity" -> "sanctities", "sarcobasis" -> "sarcobases", 
 "sarcophagus" -> "sarcophagi", "sarcoseptum" -> "sarcosepta", 
 "satrapy" -> "satrapies", "saury" -> "sauries", "saxicava" -> "saxicavae", 
 "scala" -> "scalae", "scamillus" -> "scamilli", "scapula" -> "scapulae", 
 "scholium" -> "scholia", "scirrhus" -> "scirrhi", 
 "sclerotium" -> "sclerotia", "scolex" -> "scoleces", 
 "scopula" -> "scopulae", "scoria" -> "scoriae", "scorpio" -> "scorpiones", 
 "scriptorium" -> "scriptoria", "scrobicula" -> "scrobiculae", 
 "scudo" -> "scudi", "scutella" -> "scutelle", "scutellum" -> "scutella", 
 "scutum" -> "scuta", "scypha" -> "scyphae", "scyphistoma" -> "scyphistomae", 
 "scyphus" -> "scyphi", "secrecy" -> "secrecies", "semen" -> "semens", 
 "semita" -> "semitae", "sensorium" -> "sensoria", "sepia" -> "sepiae", 
 "septarium" -> "septaria", "septemvir" -> "septemviri", 
 "septulum" -> "septula", "septum" -> "septa", "sequela" -> "sequelae", 
 "sequestrum" -> "sequestra", "sergeancy" -> "sergeancies", 
 "serpula" -> "serpulae", "seta" -> "setae", "setula" -> "setulae", 
 "severity" -> "severities", "sextary" -> "sextaries", "sexto" -> "sextos", 
 "shanny" -> "shannies", "shepherdia" -> "shepherdias", 
 "shindy" -> "shindies", "sigillum" -> "sigilla", "siliqua" -> "siliquae", 
 "sinuosity" -> "sinuosities", "siphonium" -> "siphonia", "slav" -> "slavs", 
 "slavery" -> "slaveries", "socman" -> "socmen", "sodality" -> "sodalities", 
 "solarium" -> "solaria", "soldo" -> "soldi", "sorcery" -> "sorceries", 
 "soredium" -> "soredia", "sors" -> "sortes", "sorus" -> "sori", 
 "sovereignty" -> "sovereignties", "spadix" -> "spadices", 
 "spado" -> "spadones", "spatha" -> "spathae", 
 "speciality" -> "specialities", "speciosity" -> "speciocities", 
 "spectrum" -> "spectra", "spermatheca" -> "spermathecae", 
 "spermatium" -> "spermatia", "spermatooen" -> "spermatoa", 
 "spermatozooen" -> "spermatozoa", "spermidium" -> "spermidia", 
 "sphaeridium" -> "sphaeridia", "spica" -> "spicae", "spiculum" -> "spicula", 
 "spinny" -> "spinnies", "spirituality" -> "spiritualities", 
 "splanchnapophysis" -> "splanchnapophyses", "splenculus" -> "splenculi", 
 "spontaneity" -> "spontaneities", "sporangium" -> "sporangia", 
 "sporidium" -> "sporidia", "sputum" -> "sputa", "squama" -> "squamae", 
 "squamella" -> "squamellae", "squamipen" -> "squamipennes", 
 "squamula" -> "squamulae", "squilla" -> "squillae", 
 "staminodium" -> "staminodia", "stannary" -> "stannaries", 
 "stasimon" -> "stasmia", "statuary" -> "statuaries", "stela" -> "stelae", 
 "stemma" -> "stemmata", "sternebra" -> "sternebrae", 
 "stichidium" -> "stichida", "stipula" -> "stipulae", "stirps" -> "stirpes", 
 "stola" -> "stolae", "stoma" -> "stomas", "stragulum" -> "stragula", 
 "strappado" -> "strappadoes", "strategus" -> "strategi", 
 "streptococcus" -> "streptococci", "stria" -> "striae", 
 "strobila" -> "strobilae", "stroma" -> "stromata", 
 "struthio" -> "struthiones", "stucco" -> "stuccoes", 
 "stylopodium" -> "stylopodia", "sublimity" -> "sublimities", 
 "sublingua" -> "sublinguae", "submentum" -> "submenta", 
 "subsellium" -> "subsellia", "substratum" -> "substrata", 
 "succedaneum" -> "succedanea", "succuba" -> "succubae", 
 "sudatorium" -> "sudatoria", "sudatory" -> "sudatories", 
 "sulcus" -> "sulci", "summons" -> "summonses", 
 "surveillant" -> "surveillants", "suspensorium" -> "suspensoria", 
 "sutra" -> "sutras", "syllabarium" -> "syllabaria", "sylva" -> "sylvae", 
 "symphysis" -> "symphyses", "sympodium" -> "sympodia", 
 "synangium" -> "synangia", "synapticula" -> "synapticulae", 
 "synarthrosis" -> "synarthroses", "syncarpium" -> "syncarpia", 
 "synchondrosis" -> "synchondroses", "synclinorium" -> "synclinoria", 
 "syncytium" -> "syncitia", "syndesmosis" -> "syndesmoses", 
 "synneorosis" -> "synneuroses", "synosteosis" -> "synosteoses", 
 "syrinx" -> "syringes", "syrtis" -> "syrtes", "syzygy" -> "syzygies", 
 "tabula" -> "tabulae", "tachina" -> "tachinae", "taenia" -> "taeniae", 
 "taenidium" -> "taenidia", "taeniola" -> "taeniolae", "talma" -> "talmas", 
 "talus" -> "tali", "tapeti" -> "tapetis", "targum" -> "heb", 
 "tarsale" -> "tarsalia", "tarsometatarsus" -> "tarsometatarsi", 
 "tarsus" -> "tarsi", "tegmen" -> "tegmina", "tegmentum" -> "tegmenta", 
 "tegula" -> "tegulae", "telotrocha" -> "telotrochae", "telson" -> "telsons", 
 "temporality" -> "temporalities", "tentaculum" -> "tentacula", 
 "tenuiroster" -> "tenuirosters", "tenuis" -> "tenues", 
 "teocalli" -> "teocallis", "terebra" -> "terebrae", 
 "terebratula" -> "terebratulae", "teredo" -> "teredines", 
 "tergum" -> "terga", "termes" -> "termities", "tessera" -> "tesserae", 
 "testa" -> "testae", "testudo" -> "testudines", 
 "tetrarchy" -> "tetrarchies", "teuton" -> "teutones", 
 "thalamus" -> "thalami", "thallus" -> "thalli", "theca" -> "thecae", 
 "thrombus" -> "thrombi", "thyrsus" -> "thyrsi", "tibia" -> "tibiae", 
 "tibiale" -> "tibialia", "tilbury" -> "tilburies", "tilery" -> "tileries", 
 "timpano" -> "timpani", "tineman" -> "tinemen", "tipula" -> "tipulae", 
 "titulary" -> "titularies", "tody" -> "todies", "tomentum" -> "tomenta", 
 "tomium" -> "tomi", "tony" -> "tonies", "toparchy" -> "toparchies", 
 "tophus" -> "tophi", "tornaria" -> "tornariae", "tory" -> "tories", 
 "trabea" -> "trabeae", "trachea" -> "tracheae", 
 "tracheobranchia" -> "tracheobranchlae", "trapezium" -> "trapezia", 
 "triarchy" -> "triarchies", "trica" -> "tricae", "trichina" -> "trichinae", 
 "triclinium" -> "triclinia", "trierarchy" -> "trierarchises", 
 "tripos" -> "triposes", "triquetrum" -> "triquetra", 
 "tritovum" -> "tritova", "triungulus" -> "triunguli", 
 "trochilus" -> "trochili", "trochiscus" -> "trochisci", 
 "trochus" -> "trochi", "troilus" -> "troili", "tuberculum" -> "tubercula", 
 "tuberosity" -> "tuberosities", "tumulus" -> "tumuli", 
 "tunicary" -> "tunicaries", "turbary" -> "turbaries", "turio" -> "turiones", 
 "turko" -> "turkos", "tylarus" -> "tylari", "tylosis" -> "tyloses", 
 "tympano" -> "tympani", "ulnare" -> "ulnaria", "ultimatum" -> "ultimata", 
 "umbo" -> "umbones", "uncia" -> "unciae", "uncinus" -> "uncini", 
 "uncus" -> "unci", "unguis" -> "ungues", "ungula" -> "ungulae", 
 "universality" -> "universalities", "urceolus" -> "urceoli", 
 "urosteon" -> "urostea", "vagina" -> "vaginae", "vallecula" -> "valleculae", 
 "vallum" -> "valla", "valvula" -> "valvulae", "varix" -> "varices", 
 "vas" -> "vasa", "vasculum" -> "vascula", "velarium" -> "velaria", 
 "velum" -> "vela", "vena" -> "venae", "ventriculus" -> "ventriculi", 
 "verbosity" -> "verbosities", "vertigo" -> "vertigines", 
 "vesicula" -> "vesiculae", "vespillo" -> "vespilloes", 
 "vestibulum" -> "vestibula", "vettura" -> "vetture", 
 "vetturino" -> "vetturini", "vexillum" -> "vexilla", 
 "vibraculum" -> "vibracula", "vibrio" -> "vibriones", 
 "vibrissa" -> "vibrissae", "villanella" -> "villanelle", 
 "villus" -> "villi", "vinculum" -> "vincula", "virago" -> "viragoes", 
 "vitta" -> "vittae", "volkslied" -> "volksliede", "volta" -> "volte", 
 "voluta" -> "volutae", "wady" -> "wadies", "wealsman" -> "wealsmen", 
 "whisky" -> "whiskeys", "withy" -> "withies", "xenium" -> "xenia", 
 "xiphiplastron" -> "xiphiplastra", "xiphisternum" -> "xiphisterna", 
 "zambo" -> "zambos", "zingaro" -> "zingari", "zona" -> "zonae", 
 "zooecium" -> "zooecia", "zooen" -> "zoa", "zygantrum" -> "zygantra", 
 "zygapophysis" -> "zygapophyses",
 "backdoor" -> "backdoors", "bag" -> "bags", 
 "bakehouse" -> "bakehouses", "ball" -> "balls", "bat" -> "bats", 
 "baud" -> "bauds", "beachfront" -> "beachfronts", 
 "bedsitter" -> "bedsitters", "beef" -> "beefs", "berk" -> "berks", 
 "blintz" -> "blintzes", "blitz" -> "blitzes", "blouse" -> "blouses", 
 "boatyard" -> "boatyards", "bolshie" -> "bolshies", 
 "bolshy" -> "bolshies", "bonce" -> "bonces", "borstal" -> "borstals",
  "box" -> "boxes", "bracero" -> "braceros", 
 "brainchild" -> "brainchildren", 
 "buckminsterfullerene" -> "buckminsterfullerenes", 
 "bursa" -> "bursae", "businessperson" -> "businesspeople", 
 "busload" -> "busloads", "bustier" -> "bustiers", 
 "butty" -> "butties", "buzz" -> "buzzes", "byre" -> "byres", 
 "canola" -> "canolas", "cardholder" -> "cardholders", 
 "cardinality" -> "cardinalities", "caribou" -> "caribou", 
 "CD" -> "CDs", "cecum" -> "ceca", "ceilidh" -> "ceilidhs", 
 "CEO" -> "CEOs", "CFC" -> "CFCs", "char" -> "chars", 
 "charisma" -> "charismas", "cheer" -> "cheers", "chili" -> "chilis", 
 "chipolata" -> "chipolatas", "chlamydia" -> "chlamydiae", 
 "chub" -> "chubs", "cicerone" -> "ciceroni", "citrate" -> "citrates",
  "cityscape" -> "cityscapes", "claymore" -> "claymores", 
 "clingfilm" -> "clingflims", "closer" -> "closers", 
 "cochlea" -> "cochleae", "coho" -> "cohos", 
 "collimation" -> "collimations", "coma" -> "comas", 
 "commute" -> "commutes", "conch" -> "conchs", 
 "concurrency" -> "concurrencies", "congregant" -> "congregant", 
 "continuum" -> "continua", "coprolite" -> "coprolites", 
 "cornflour" -> "cornflours", "corporatism" -> "corporatisms", 
 "corporatist" -> "corporatists", 
 "counterargument" -> "counterarguments", "CPU" -> "CPUs", 
 "cracker" -> "crackers", "crappie" -> "crappies", "cred" -> "creds", 
 "crowfoot" -> "crowfeet", "crumb" -> "crumbs", 
 "cryptanalysis" -> "cryptanalyses", 
 "cryptanalyst" -> "cryptanalysts", 
 "crystallographer" -> "crystallographers", "curse" -> "curses", 
 "cytochrome" -> "cytochromes", "dace" -> "dace", 
 "dalesman" -> "dalesmen", "dB" -> "dBs", "DDT" -> "DDTs", 
 "debaser" -> "debasers", "deco" -> "decos", 
 "defenestration" -> "defenestrations", 
 "deliverable" -> "deliverables", "descender" -> "descenders", 
 "descriptor" -> "descriptors", "diamante" -> "diamantes", 
 "dickybird" -> "dickybirds", "diddly" -> "diddlies", 
 "diluent" -> "diluents", "dimorphism" -> "dimorphisms", 
 "dingo" -> "dingos", "diopter" -> "diopters", 
 "diptych" -> "diptychs", "disambiguation" -> "disambiguations", 
 "disconnect" -> "disconnects", "diuresis" -> "diureses", 
 "diver" -> "divers", "doddle" -> "doddles", "doe" -> "does", 
 "doppelganger" -> "doppelgangers", "doubler" -> "doublers", 
 "duodenum" -> "duodena", "DVD" -> "DVDs", "dybbuk" -> "dybbuks", 
 "dybbukim" -> "dybbukim", "dystrophy" -> "dystrophies", 
 "eigenvalue" -> "eigenvalues", "eland" -> "elands", 
 "elect" -> "elects", "eliminator" -> "eliminators", 
 "emoticon" -> "emoticons", "encephalopathy" -> "encephalopathies", 
 "endgame" -> "endgames", "enhancer" -> "enhancers", 
 "entr'acte" -> "entr'actes", "epitaxy" -> "epitaxies", 
 "equilibration" -> "equilibrations", "ethicist" -> "ethicists", 
 "eunuch" -> "eunuchs", "euro" -> "euros", "everyman" -> "everymen", 
 "exfoliation" -> "exfoliations", "expat" -> "expats", 
 "faller" -> "fallers", "FAQ" -> "FAQs", "farrago" -> "farragoes", 
 "fauvist" -> "fauvists", "FBI" -> "FBIs", "FDA" -> "FDAs", 
 "FDR" -> "FDRs", "feedstock" -> "feedstocks", "feller" -> "fellers", 
 "fenland" -> "fenlands", "fez" -> "fezzes", "fibula" -> "fibulae", 
 "fizz" -> "fizzes", "flak" -> "flaks", "folksong" -> "folksongs", 
 "foreperson" -> "forepeople", "fowl" -> "fowls", 
 "frontbencher" -> "frontbenchers", 
 "functionality" -> "functionalities", "fundraiser" -> "fundraisers", 
 "fuzz" -> "fuzzes", "gangsta" -> "gangstas", 
 "gaolbird" -> "gaolbirds", "gaolbreak" -> "gaolbreaks", 
 "garbageman" -> "garbagemen", "gazillion" -> "gazillions", 
 "geisha" -> "geishas", "gerontocracy" -> "gerontacracies", 
 "git" -> "gits", "glissando" -> "glissandi", "gnu" -> "gnus", 
 "go" -> "goes", "godchild" -> "godchildren", 
 "goofball" -> "goofballs", "GPA" -> "GPAs", "graffito" -> "graffiti",
  "gran" -> "grans", "grand" -> "grand", 
 "grandchild" -> "grandchildren", "grandmaster" -> "grandmasters", 
 "graver" -> "gravers", "graviton" -> "gravitons", 
 "great-uncle" -> "great-uncles", "grinner" -> "grinners", 
 "groaner" -> "groaners", "gross" -> "gross", "grouse" -> "grouses", 
 "GUI" -> "GUIs", "guttersnipe" -> "guttersnipes", 
 "guvnor" -> "guvnor", "gymslip" -> "gymslips", 
 "haemorrhoid" -> "haemorrhoids", "haiku" -> "haiku", 
 "hairgrip" -> "hairgrips", "hajj" -> "hajjes", "hake" -> "hakes", 
 "half-brother" -> "half-brothers", "halfpenny" -> "halfpennies", 
 "half-sister" -> "half-sisters", "halibut" -> "halibut", 
 "halon" -> "halons", "handbasin" -> "handbasins", 
 "handshake" -> "handshakes", "have-not" -> "have-nots", 
 "head" -> "heads", "hepatic" -> "hepatics", 
 "hieratic" -> "hieratics", "HMO" -> "HMOs", "hobbit" -> "hobbits", 
 "holism" -> "holisms", "homomorphism" -> "homomorphisms", 
 "horror" -> "horrors", "horsebox" -> "horseboxes", 
 "horseflesh" -> "horseflesh", "hose" -> "hoses", 
 "hotpot" -> "hotpots", "hotspot" -> "hotspots", 
 "housemate" -> "housemates", "hovercraft" -> "hovercrafts", 
 "HQ" -> "HQs", "hugger" -> "huggers", 
 "hyperboloid" -> "hyperboloids", "hyperlink" -> "hyperlinks", 
 "hypothetical" -> "hypotheticals", "hysteresis" -> "hystereses", 
 "ibex" -> "ibices", "icepick" -> "icepicks", 
 "identifier" -> "identifiers", "ileum" -> "ilea", 
 "immunoassay" -> "immunoassays", 
 "inhomogeneity" -> "inhomogeneities", "in-law" -> "in-laws", 
 "instantiation" -> "instantiations", 
 "interoperability" -> "interoperabilities", 
 "interpenetration" -> "interpenetrations", "intifada" -> "intifadas",
  "intranet" -> "intranets", "invariant" -> "invariants", 
 "IOU" -> "IOUs", "IQ" -> "IQs", "IRS" -> "IRSs", 
 "isotropy" -> "isotropies", "jejunum" -> "jejuna", "JFK" -> "JFKs", 
 "jigger" -> "jiggers", "kerfuffle" -> "kerfuffles", 
 "kibbutz" -> "kibbutzes", "kingmaker" -> "kingmakers", 
 "kip" -> "kips", "klutz" -> "klutzes", "KO" -> "KOs", 
 "kohlrabi" -> "kohlrabis", "krona" -> "kronor", "krone" -> "kroner", 
 "lacteal" -> "lacteals", "lacuna" -> "lacunae", 
 "lamina" -> "laminae", "LAN" -> "LANs", "lander" -> "landers", 
 "lateralization" -> "lateralizations", "latex" -> "latexes", 
 "layperson" -> "laypeople", "layup" -> "layups", "LBJ" -> "LBJs", 
 "lech" -> "leches", "legitimation" -> "legitimations", 
 "lemongrass" -> "lemongrasses", "lepton" -> "leptons", 
 "letch" -> "letches", "leucotomy" -> "leucotomies", 
 "limper" -> "limpers", "lingo" -> "lingos", 
 "linguine" -> "linguines", "lire" -> "lires", 
 "listeria" -> "listerias", "lithology" -> "lithologies", 
 "LLB" -> "LLBs", "lobster" -> "lobsters", "loch" -> "lochs", 
 "lopper" -> "loppers", "lowlife" -> "lowlifes", "lynx" -> "lynxes", 
 "macaroni" -> "macaronis", "MacArthur" -> "MacArthurs", 
 "madam" -> "madams", "mafioso" -> "mafiosi", 
 "maintainer" -> "maintainers", "mangler" -> "manglers", 
 "manservant" -> "manservants", 
 "marginalization" -> "marginalizations", "markka" -> "markkas", 
 "marlin" -> "marlins", "matcher" -> "matchers", 
 "matriarch" -> "matriarchs", "matzo" -> "matzos", "MBA" -> "MBAs", 
 "McCarthy" -> "McCarthys", "McCartney" -> "McCartneys", 
 "McCormick" -> "McCormicks", "McGuffey" -> "McGuffeys", 
 "McIntosh" -> "McIntoshes", "McKinley" -> "McKinleys", 
 "McLuhan" -> "McLuhans", "McPherson" -> "McPhersons", 
 "meatloaf" -> "meatloaves", "mechanist" -> "mechanists", 
 "meeter" -> "meeters", "melter" -> "melters", 
 "menhaden" -> "menhadens", "metastability" -> "metastabilities", 
 "methylene" -> "methylenes", "microcode" -> "microcodes", 
 "microfarad" -> "microfarads", "microfiche" -> "microfiches", 
 "microscopist" -> "microscopists", "military" -> "militaries", 
 "milkshake" -> "milkshakes", "minicab" -> "minicabs", 
 "mink" -> "minks", "miscellanea" -> "miscellanee", "MIT" -> "MITs", 
 "monarch" -> "monarchs", "monoculture" -> "monocultures", 
 "munch" -> "munches", "muncher" -> "munchers", "musher" -> "mushers",
  "muskellunge" -> "muskellunge", "NAFTA" -> "NAFTAs", 
 "naif" -> "naifs", "nan" -> "nans", 
 "nanotechnology" -> "nanotechnologies", "NASA" -> "NASAs", 
 "NASDAQ" -> "NASDAQs", "NATO" -> "NATOs", "need" -> "needs", 
 "neoconservative" -> "neoconservatives", "netball" -> "netballs", 
 "newsreader" -> "newsreaders", "nightlife" -> "nightlives", 
 "nitride" -> "nitrides", "no" -> "noes", 
 "normalizer" -> "normalizers", "nosedive" -> "nosedives", 
 "nosher" -> "noshers", "no-show" -> "no-shows", 
 "nuclease" -> "nucleases", "null" -> "nulls", 
 "numberplate" -> "numberplates", "nut" -> "nuts", 
 "nutter" -> "nutters", "oar" -> "oars", "O'Brien" -> "O'Briens", 
 "O'Casey" -> "O'Caseys", "O'Connor" -> "O'Connors", 
 "offside" -> "offsides", "O'Hara" -> "O'Haras", "OK" -> "OKs", 
 "O'Keeffe" -> "O'Keefes", "oligarch" -> "oligarchs", 
 "oligopoly" -> "oligopolies", "O'Neill" -> "O'Neils", 
 "OPEC" -> "OPECs", "optimum" -> "optima", "O'Toole" -> "O'Tooles", 
 "outgo" -> "outgoes", "overpressure" -> "overpressures", 
 "oxymoron" -> "oxymora", "paintball" -> "paintballs", 
 "panellist" -> "panellists", "para" -> "paras", 
 "parenthetical" -> "parentheticals", "parkland" -> "parklands", 
 "parser" -> "parsers", "participial" -> "participials", 
 "passerby" -> "passersby", "patriarch" -> "patriarchs", 
 "pave" -> "paver", "pavlova" -> "pavlovas", "PC" -> "PCs", 
 "pedophile" -> "pedophiles", "perfecter" -> "perfecters", 
 "perineum" -> "perinea", "peroxidase" -> "peroxidases", 
 "pertussis" -> "pertusses", "petrolatum" -> "petrolatums", 
 "pettifoggery" -> "pettifoggeries", "PhD" -> "PhDs", 
 "phenolphthalein" -> "phenolphthaleins", 
 "phenomenology" -> "phenomenologies", "phlox" -> "phloxes", 
 "phosphatase" -> "phosphatases", "photosphere" -> "photospheres", 
 "pibroch" -> "pibrochs", "pic" -> "pics", "pickerel" -> "pickerels", 
 "pike" -> "pikes", "pillock" -> "pillocks", "piranha" -> "piranhas", 
 "pirogi" -> "pirogies", "piste" -> "pistes", 
 "pizzicato" -> "pizzicati", "placekicker" -> "placekickers", 
 "plasmid" -> "plasmids", "plasterwork" -> "plasterworks", 
 "platy" -> "platy", "playbook" -> "playbooks", 
 "plectrum" -> "plectra", "PLO" -> "PLOs", "poi" -> "po", 
 "police" -> "police", "pollack" -> "pollacks", 
 "polychrome" -> "polychromes", "pompano" -> "pompanos", 
 "pong" -> "pongs", "porgy" -> "porgies", "porpoise" -> "porpoises", 
 "postdoc" -> "postdocs", "POW" -> "POWs", "prang" -> "prangs", 
 "prayerbook" -> "prayerbooks", "prion" -> "prions", 
 "pro-lifer" -> "pro-lifers", "prosciutto" -> "prosciutti", 
 "provocateur" -> "provocateurs", "ptarmigan" -> "ptarmigans", 
 "pudendum" -> "pudenda", "putz" -> "putzes", 
 "pyrolysis" -> "pyrolyses", "quail" -> "quails", 
 "quango" -> "quangos", "quartile" -> "quartiles", 
 "quartz" -> "quartzes", "quid" -> "quids", "quoter" -> "quoters", 
 "rand" -> "rands", "rapporteur" -> "rapporteurs", "rat" -> "rats", 
 "ratatouille" -> "ratatouilles", "real" -> "reals", 
 "recirculation" -> "recirculations", 
 "recombination" -> "recombinations", "redshift" -> "redshifts", 
 "reflexology" -> "reflexologies", 
 "remonstration" -> "remonstrations", "requester" -> "requesters", 
 "residuum" -> "residua", "retro" -> "retros", 
 "rigatoni" -> "rigatonis", "roach" -> "roaches", 
 "runner-up" -> "runners-up", "sable" -> "sables", 
 "sacrum" -> "sacra", "safe-conduct" -> "safe-conducts", 
 "salesperson" -> "salespeople", "salter" -> "salters", 
 "samizdat" -> "samizdats", "samosa" -> "samosas", 
 "samurai" -> "samurais", "sash" -> "sashes", 
 "sawtooth" -> "sawteeth", "scalability" -> "scalabilities", 
 "scheduler" -> "schedulers", "schmo" -> "schmos", 
 "schmoozer" -> "schmoozers", "schnoz" -> "schnozzes", 
 "schoolchild" -> "schoolchildren", "schoolfriend" -> "schoolfriends",
  "scouter" -> "scouters", "scrod" -> "scrods", "scrotum" -> "scrota",
  "scrumpy" -> "scrumpies", "scurf" -> "scurfs", 
 "secreter" -> "secreters", "securer" -> "securers", 
 "seismogram" -> "seismograms", "self-abasement" -> "self-abasements",
  "self-absorption" -> "self-absorptions", 
 "self-abuse" -> "self-abuses", "self-analysis" -> "self-analyses", 
 "self-assurance" -> "self-assurances", 
 "self-criticism" -> "self-criticisms", 
 "self-defense" -> "self-defenses", "self-denial" -> "self-denials", 
 "self-doubt" -> "self-doubts", 
 "self-effacement" -> "self-effacements", 
 "self-examination" -> "self-examinations", 
 "self-expression" -> "self-expressions", 
 "self-fulfillment" -> "self-fulfillments", 
 "self-interest" -> "self-interests", 
 "self-portrait" -> "self-portraits", 
 "self-sacrifice" -> "self-sacrifices", 
 "self-seeker" -> "self-seekers", "self-starter" -> "self-starters", 
 "self-sufficiency" -> "self-sufficiencies", 
 "sequencer" -> "sequencers", "SGML" -> "SGMLs", "shad" -> "shads", 
 "sheller" -> "shellers", "shifter" -> "shifters", 
 "Shi'ite" -> "Shi'ites", "shopaholic" -> "shopaholics", 
 "shortlist" -> "shortlists", "showstopper" -> "showstoppers", 
 "showtime" -> "showtimes", "shrimper" -> "shrimpers", 
 "signage" -> "signages", "signifier" -> "signifiers", 
 "signore" -> "signori", "singalong" -> "singalongs", 
 "sit-in" -> "sit-ins", "six-pack" -> "six-packs", 
 "sixpence" -> "sixpences", "skate" -> "skates", 
 "skinful" -> "skinfuls", "skinner" -> "skinners", 
 "slagheap" -> "slagheaps", "slapper" -> "slappers", 
 "slingback" -> "slingbacks", "smiley" -> "smileys", 
 "snipe" -> "snipes", "sole" -> "soles", 
 "sou'wester" -> "sou'westers", "sparer" -> "sparers", 
 "spat" -> "spats", "speakerphone" -> "speakerphones", 
 "specifier" -> "specifiers", "spiff" -> "spiffs", 
 "spiller" -> "spillers", "spliff" -> "spliffs", 
 "splitter" -> "splitters", "spokeshave" -> "spokeshaves", 
 "spokesperson" -> "spokespeople", "springbok" -> "springboks", 
 "spritz" -> "spritzes", "sprog" -> "sprogs", 
 "spymaster" -> "spymaster", "squab" -> "squabs", 
 "squinter" -> "squinters", "stacker" -> "stackers", 
 "staff" -> "staffs", "stainer" -> "stainers", 
 "standby" -> "standbys", "stater" -> "staters", 
 "stealer" -> "stealers", "steeper" -> "steepers", 
 "stepchild" -> "stepchildren", "stone" -> "stones", 
 "storyline" -> "storylines", "strider" -> "striders", 
 "strife" -> "strifes", "stuffer" -> "stuffers", 
 "sturgeon" -> "sturgeons", "subduction" -> "subductions", 
 "submitter" -> "submitters", "suck" -> "sucks", 
 "suggester" -> "suggesters", "sundress" -> "sundresses", 
 "supercargo" -> "supercargos", "supercomputer" -> "supercomputers", 
 "supergrass" -> "supergrasses", "supermodel" -> "supermodels", 
 "supremo" -> "supremos", "sweatsuit" -> "sweatsuits", 
 "swiz" -> "swizes", "tailgater" -> "tailgaters", 
 "takeaway" -> "takeaways", "tarpon" -> "tarpons", "teal" -> "teals", 
 "techie" -> "techies", "technophobe" -> "technophobes", 
 "technophobia" -> "technophobias", 
 "terpsichorean" -> "terpsichoreans", "thaumaturge" -> "thaumaturges",
  "threepence" -> "threepences", "thumbprint" -> "thumbprints", 
 "tideland" -> "tidelands", "timeline" -> "timelines", 
 "timid" -> "timid", "timpani" -> "timpanis", "TNT" -> "TNT", 
 "top" -> "tops", "topaz" -> "topazes", "tosser" -> "tossers", 
 "trad" -> "trads", "tranche" -> "tranches", 
 "transferee" -> "transferees", "triptych" -> "triptychs", 
 "tuba" -> "tubas", "TV" -> "TVs", "twiddler" -> "twiddlers", 
 "twopence" -> "twopences", "tympani" -> "tympanis", 
 "typology" -> "typologies", "UFO" -> "UFOs", "UK" -> "UKs", 
 "ulna" -> "ulnae", "ultramontane" -> "ultramontanes", "UN" -> "UNs", 
 "unambiguity" -> "unambiguities", "unicyclist" -> "unicyclists", 
 "UNIX" -> "UNIXs", "unperson" -> "unpeople", 
 "unsolvability" -> "unsolvabilities", "urethra" -> "urethras", 
 "URL" -> "URLs", "US" -> "USs", "USA" -> "USAs", "USAF" -> "USAFs", 
 "USMC" -> "USMCs", "USSR" -> "USSRs", "utterer" -> "utterers", 
 "vaporisation" -> "vaporisations", "VCR" -> "VCRs", "veg" -> "vegs", 
 "velodrome" -> "velodromes", "verifier" -> "verifiers", 
 "vermin" -> "vermin", "verruca" -> "verrucas", "VHF" -> "VHFs", 
 "vice-presidency" -> "vice-presidencies", "VIP" -> "VIPs", 
 "viva" -> "vivas", "voicemail" -> "voicemails", "vulva" -> "vulvas", 
 "walleye" -> "walleye", "wally" -> "wallies", 
 "warehouseman" -> "warehousemen", "wasteland" -> "wastelands", 
 "watercraft" -> "watercrafts", "waterfowl" -> "waterfowls", 
 "waterman" -> "watermen", "waveband" -> "wavebands", 
 "wavefront" -> "wavefronts", "weatherstrip" -> "weatherstrips", 
 "webmaster" -> "webmasters", "weedkiller" -> "weedkillers", 
 "whiz" -> "whizzes", "WHO" -> "WHOs", "whoop" -> "whoops", 
 "why" -> "whies", "wildfowl" -> "wildfowl", "wirer" -> "wirers", 
 "witch-hunt" -> "witch-hunts", "wog" -> "wogs", "won" -> "won", 
 "write-off" -> "write-offs", "XL" -> "XLs", "yen" -> "yen", 
 "yes-man" -> "yes-men", "yid" -> "yids", "yuan" -> "yuan", 
 "minutia" -> "minutiae", "salmonella" -> "salmonellae", 
 "stigma" -> "stigmata", "UHF" -> "UHFs","ABC" -> "ABCs", 
 "abort" -> "aborts", "abseiler" -> "abseilers", 
 "abstinent" -> "abstinents", "AC" -> "ACs", "adaption" -> "adaptions", 
 "add-on" -> "add-ons", "affine" -> "affines", "ageratum" -> "ageratums", 
 "airgun" -> "airguns", "albacore" -> "albacores", 
 "albatross" -> "albatrosses", "albedo" -> "albedos", 
 "allocator" -> "allocators", "AM" -> "AMs", "amino" -> "aminos", 
 "anchorperson" -> "anchorpeople", "anionic" -> "anionics", 
 "antelope" -> "antelopes", "anterior" -> "anteriors", 
 "apparatchik" -> "apparatchiks", "arachnophobia" -> "arachnophobias", 
 "archeopteryx" -> "archeopteryges", "arsenide" -> "arsenides", 
 "assaulter" -> "assaulters", "associateship" -> "associateships", 
 "ATP" -> "ATPs", "attendee" -> "attendees", "attenuator" -> "attenuators", 
 "attractor" -> "attractors", "austral" -> "australs", "auteur" -> "auteurs", 
 "authenticator" -> "authenticators", "avant-garde" -> "avant-gardes", 
 "AZT" -> "AZTs", "ban" -> "bans", "beechwood" -> "beechwoods", 
 "broody" -> "broodies", "centralism" -> "centralisms", "CIA" -> "CIAs", 
 "DNA" -> "DNAs", "firstborn" -> "firstborns", "FM" -> "FMs", 
 "frizz" -> "frizzes", "GOP" -> "GOPs", "GP" -> "GPs", "hi-fi" -> "hi-fis", 
 "HIV" -> "HIVs", "horsepower" -> "horsepower", "HTML" -> "HTMLs", 
 "HTTP" -> "HTTPs", "IMF" -> "IMFs", "indie" -> "indies", 
 "infernal" -> "infernals", "misquote" -> "misquotes", 
 "pantyhose" -> "pantyhose", "quarterstaff" -> "quarterstaves", 
 "swimwear" -> "swimwear","nevi"->"nevi", "French"->"French",
 "trivium"->"trivia", "bacchanalia"->"bacchanalias", "tedium"->"tediums"|>
