libept: ept::debtags::SourceDir Class Reference
ept::debtags::SourceDir Class Reference
Access a directory containing Debtags data files.
#include <sourcedir.h>
Public Member Functions
SourceDir (const std::string &path)
time_t timestamp ()
Return the time of the newest file in the source directory.
time_t vocTimestamp ()
Return the time of the newest vocabulary file in the source directory.
time_t tagTimestamp ()
Return the time of the newest tag file in the source directory.
template<typename OUT >
void readTags (OUT out)
Read the tag files in the directory and output their content to out.
void readVocabularies (Vocabulary &out)
Read the vocabulary files in the directory and output their content to out.
Protected Types
enum FileType {
SKIP, TAG, VOC, TAGGZ,
VOCGZ
}
Protected Member Functions
FileType fileType (const std::string &name)
Detailed Description
Access a directory containing Debtags data files.
Member Enumeration Documentation
enum ept::debtags::SourceDir::FileType protected
Enumerator:
SKIP
TAG
VOC
TAGGZ
VOCGZ
Constructor & Destructor Documentation
ept::debtags::SourceDir::SourceDir (const std::string & path) inline
Member Function Documentation
SourceDir::FileType ept::debtags::SourceDir::fileType (const std::string & name) protected
template<typename OUT > void ept::debtags::SourceDir::readTags (OUT out)
Read the tag files in the directory and output their content to out.
Referenced by ept::debtags::Debtags::changes(), and ept::debtags::Debtags::Debtags().
void ept::debtags::SourceDir::readVocabularies (Vocabulary & out)
Read the vocabulary files in the directory and output their content to out.
References ept::debtags::Vocabulary::read().
Referenced by ept::debtags::Vocabulary::Vocabulary().
time_t ept::debtags::SourceDir::tagTimestamp ()
Return the time of the newest tag file in the source directory.
References ept::axi::timestamp().
Referenced by ept::debtags::Debtags::Debtags().
time_t ept::debtags::SourceDir::timestamp ()
Return the time of the newest file in the source directory.
References ept::axi::timestamp().
time_t ept::debtags::SourceDir::vocTimestamp ()
Return the time of the newest vocabulary file in the source directory.
References ept::axi::timestamp().
Referenced by ept::debtags::Vocabulary::Vocabulary(), and ept::debtags::Vocabulary::write().
The documentation for this class was generated from the following files:
debtags/maint/sourcedir.h
debtags/maint/sourcedir.cc