libept: ept::debtags::DebDBParser Class Reference
ept::debtags::DebDBParser Class Reference
Parse Debian records from a parser input.
#include <debdbparser.h>
Public Types
typedef std::map< std::string,
std::string > Record
Public Member Functions
DebDBParser (tagcoll::input::Input &input)
const std::string & fileName () const throw ()
int lineNumber () const throw ()
bool nextRecord (Record &rec)
Protected Member Functions
int eatSpacesAndEmptyLines ()
std::string getFieldName ()
void eatFieldSep ()
void appendFieldBody (std::string &body)
Protected Attributes
tagcoll::input::Input & in
bool isBOL
bool isEOF
Detailed Description
Parse Debian records from a parser input.
Member Typedef Documentation
typedef std::map<std::string, std::string> ept::debtags::DebDBParser::Record
Constructor & Destructor Documentation
ept::debtags::DebDBParser::DebDBParser (tagcoll::input::Input & input)
References eatSpacesAndEmptyLines().
Member Function Documentation
void ept::debtags::DebDBParser::appendFieldBody (std::string & body) protected
Referenced by nextRecord().
void ept::debtags::DebDBParser::eatFieldSep () protected
Referenced by nextRecord().
int ept::debtags::DebDBParser::eatSpacesAndEmptyLines () protected
Referenced by DebDBParser(), and nextRecord().
const std::string& ept::debtags::DebDBParser::fileName () const throw () inline
References in.
std::string ept::debtags::DebDBParser::getFieldName () protected
Referenced by nextRecord().
int ept::debtags::DebDBParser::lineNumber () const throw () inline
References in.
bool ept::debtags::DebDBParser::nextRecord (Record & rec)
References appendFieldBody(), eatFieldSep(), eatSpacesAndEmptyLines(), getFieldName(), isBOL, and isEOF.
Referenced by ept::debtags::Vocabulary::read().
Member Data Documentation
tagcoll::input::Input& ept::debtags::DebDBParser::in protected
Referenced by fileName(), and lineNumber().
bool ept::debtags::DebDBParser::isBOL protected
Referenced by nextRecord().
bool ept::debtags::DebDBParser::isEOF protected
Referenced by nextRecord().
The documentation for this class was generated from the following files:
debdbparser.h
debdbparser.cc