libept: ept::debtags::Path Class Reference
ept::debtags::Path Class Reference
Singleton class to configure and access the various Debtags paths.
#include <path.h>
Classes
class OverrideDebtagsIndexDir
class OverrideDebtagsSourceDir
class OverrideDebtagsUserIndexDir
class OverrideDebtagsUserSourceDir
Static Public Member Functions
static std::string vocabulary ()
static std::string userVocabulary ()
static std::string tagdb ()
static std::string userTagdb ()
static std::string debtagsSourceDir ()
static std::string debtagsIndexDir ()
static std::string debtagsUserSourceDir ()
static std::string debtagsUserIndexDir ()
static void setDebtagsSourceDir (const std::string &s)
static void setDebtagsIndexDir (const std::string &s)
static void setDebtagsUserSourceDir (const std::string &s)
static void setDebtagsUserIndexDir (const std::string &s)
static int access (const std::string &, int)
static time_t timestamp (const std::string &)
Static Protected Member Functions
static Path & instance ()
Protected Attributes
std::string m_debtagsSourceDir
std::string m_debtagsIndexDir
std::string m_debtagsUserSourceDir
std::string m_debtagsUserIndexDir
Static Protected Attributes
static Path * s_instance = 0
Detailed Description
Singleton class to configure and access the various Debtags paths.
Member Function Documentation
int ept::debtags::Path::access (const std::string & s, int m) static
std::string ept::debtags::Path::debtagsIndexDir () static
std::string ept::debtags::Path::debtagsSourceDir () static
std::string ept::debtags::Path::debtagsUserIndexDir () static
std::string ept::debtags::Path::debtagsUserSourceDir () static
Path & ept::debtags::Path::instance () static protected
References m_debtagsSourceDir.
void ept::debtags::Path::setDebtagsIndexDir (const std::string & s) static
Referenced by ept::debtags::Path::OverrideDebtagsIndexDir::OverrideDebtagsIndexDir(), and ept::debtags::Path::OverrideDebtagsIndexDir::~OverrideDebtagsIndexDir().
void ept::debtags::Path::setDebtagsSourceDir (const std::string & s) static
Referenced by ept::debtags::Path::OverrideDebtagsSourceDir::OverrideDebtagsSourceDir(), and ept::debtags::Path::OverrideDebtagsSourceDir::~OverrideDebtagsSourceDir().
void ept::debtags::Path::setDebtagsUserIndexDir (const std::string & s) static
Referenced by ept::debtags::Path::OverrideDebtagsUserIndexDir::OverrideDebtagsUserIndexDir(), and ept::debtags::Path::OverrideDebtagsUserIndexDir::~OverrideDebtagsUserIndexDir().
void ept::debtags::Path::setDebtagsUserSourceDir (const std::string & s) static
Referenced by ept::debtags::Path::OverrideDebtagsUserSourceDir::OverrideDebtagsUserSourceDir(), and ept::debtags::Path::OverrideDebtagsUserSourceDir::~OverrideDebtagsUserSourceDir().
std::string ept::debtags::Path::tagdb () static
time_t ept::debtags::Path::timestamp (const std::string & file) static
std::string ept::debtags::Path::userTagdb () static
std::string ept::debtags::Path::userVocabulary () static
std::string ept::debtags::Path::vocabulary () static
Member Data Documentation
std::string ept::debtags::Path::m_debtagsIndexDir protected
std::string ept::debtags::Path::m_debtagsSourceDir protected
Referenced by instance().
std::string ept::debtags::Path::m_debtagsUserIndexDir protected
std::string ept::debtags::Path::m_debtagsUserSourceDir protected
Path * ept::debtags::Path::s_instance = 0 static protected
The documentation for this class was generated from the following files:
debtags/maint/path.h
debtags/maint/path.cc