libept: ept::apt::PackageRecord Class Reference
ept::apt::PackageRecord Class Reference
RecordParser specialised with access methods for common Debian package information.
#include <packagerecord.h>
Public Member Functions
PackageRecord ()
PackageRecord (const std::string &str)
std::string package (const std::string &def=std::string()) const
std::string priority (const std::string &def=std::string()) const
std::string section (const std::string &def=std::string()) const
size_t installedSize (size_t def=0) const
std::string maintainer (const std::string &def=std::string()) const
std::string architecture (const std::string &def=std::string()) const
std::string source (const std::string &def=std::string()) const
std::string version (const std::string &def=std::string()) const
std::string replaces (const std::string &def=std::string()) const
std::string depends (const std::string &def=std::string()) const
std::string preDepends (const std::string &def=std::string()) const
std::string recommends (const std::string &def=std::string()) const
std::string suggests (const std::string &def=std::string()) const
std::string enhances (const std::string &def=std::string()) const
std::string provides (const std::string &def=std::string()) const
std::string conflicts (const std::string &def=std::string()) const
std::string filename (const std::string &def=std::string()) const
size_t packageSize (size_t def=0) const
std::string md5sum (const std::string &def=std::string()) const
std::string sha1 (const std::string &def=std::string()) const
std::string sha256 (const std::string &def=std::string()) const
std::string description (const std::string &def=std::string()) const
std::string shortDescription (const std::string &def=std::string()) const
std::string longDescription (const std::string &def=std::string()) const
bool buildEssential (bool def=false) const
std::set< std::string > tag (const std::set< std::string > &def=std::set< std::string >()) const
Public Member Functions inherited from ept::apt::RecordParser
RecordParser ()
RecordParser (const std::string &str)
void scan (const std::string &str)
Index a new record.
size_t index (const std::string &str) const
Get the index of the field with the given name.
std::string field (size_t idx) const
Return the field by its index.
std::string name (size_t idx) const
Return the name of a field by its index.
std::string lookup (size_t idx) const
Return the content of a field by its index.
std::string lookup (const std::string &name) const
Return the content of a field by its name.
std::string operator[] (size_t idx) const
Return the content of a field by its index.
std::string operator[] (const std::string &name) const
Return the content of a field by its name.
const std::string & record () const
Return the entire record.
std::string record ()
Return the entire record.
size_t size () const
Return the number of fields in the record.
Detailed Description
RecordParser specialised with access methods for common Debian package information.
Constructor & Destructor Documentation
ept::apt::PackageRecord::PackageRecord () inline
ept::apt::PackageRecord::PackageRecord (const std::string & str) inline
Member Function Documentation
std::string ept::apt::PackageRecord::architecture (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
bool ept::apt::PackageRecord::buildEssential (bool def = false) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::conflicts (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::depends (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::description (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::enhances (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::filename (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
size_t ept::apt::PackageRecord::installedSize (size_t def = 0) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::longDescription (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::maintainer (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::md5sum (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::package (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
size_t ept::apt::PackageRecord::packageSize (size_t def = 0) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::preDepends (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::priority (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::provides (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::recommends (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::replaces (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::section (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::sha1 (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::sha256 (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::shortDescription (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::source (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::suggests (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::set<std::string> ept::apt::PackageRecord::tag (const std::set< std::string > & def = std::set<std::string>()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
std::string ept::apt::PackageRecord::version (const std::string & def = std::string()) const inline
References ept::apt::RecordParser::lookup().
Referenced by TestAptPackagerecord::supportedFields().
The documentation for this class was generated from the following files:
packagerecord.h
packagerecord.cc