libept: ept::popcon::SourceDir Class Reference
ept::popcon::SourceDir Class Reference
Access a directory containing Debtags data files.
#include <sourcedir.h>
Public Member Functions
SourceDir (const std::string &path)
time_t timestamp ()
Return the time of the newest file in the source directory.
bool readScores (std::map< std::string, Score > &out, size_t &submissions)
Read the tag files in the directory and output their content to the map.
Protected Types
enum FileType { SKIP, RAW, RAWGZ }
Protected Member Functions
FileType fileType (const std::string &name)
Detailed Description
Access a directory containing Debtags data files.
Member Enumeration Documentation
enum ept::popcon::SourceDir::FileType protected
Enumerator:
SKIP
RAW
RAWGZ
Constructor & Destructor Documentation
ept::popcon::SourceDir::SourceDir (const std::string & path) inline
Member Function Documentation
SourceDir::FileType ept::popcon::SourceDir::fileType (const std::string & name) protected
bool ept::popcon::SourceDir::readScores (std::map< std::string, Score > & out, size_t & submissions)
Read the tag files in the directory and output their content to the map.
Referenced by ept::popcon::PopconIndexer::rebuild().
time_t ept::popcon::SourceDir::timestamp ()
Return the time of the newest file in the source directory.
References ept::axi::timestamp().
Referenced by ept::popcon::PopconIndexer::rescan().
The documentation for this class was generated from the following files:
popcon/maint/sourcedir.h
popcon/maint/sourcedir.cc