libept: ept::popcon::Path Class Reference
ept::popcon::Path Class Reference
Singleton class to configure and access the various Popcon paths.
#include <path.h>
Classes
class OverridePopconIndexDir
class OverridePopconSourceDir
class OverridePopconUserIndexDir
class OverridePopconUserSourceDir
Static Public Member Functions
static std::string scores ()
static std::string scoresIndex ()
static std::string userScores ()
static std::string userScoresIndex ()
static std::string popconSourceDir ()
static std::string popconIndexDir ()
static std::string popconUserSourceDir ()
static std::string popconUserIndexDir ()
static void setPopconSourceDir (const std::string &s)
static void setPopconIndexDir (const std::string &s)
static void setPopconUserSourceDir (const std::string &s)
static void setPopconUserIndexDir (const std::string &s)
static int access (const std::string &, int)
static time_t timestamp (const std::string &)
Static Protected Member Functions
static Path & instance ()
Protected Attributes
std::string m_popconSourceDir
std::string m_popconIndexDir
std::string m_popconUserSourceDir
std::string m_popconUserIndexDir
Static Protected Attributes
static Path * s_instance = 0
Detailed Description
Singleton class to configure and access the various Popcon paths.
Member Function Documentation
int ept::popcon::Path::access (const std::string & s, int m) static
Referenced by ept::popcon::PopconIndexer::rebuildIfNeeded().
Path & ept::popcon::Path::instance () static protected
References m_popconSourceDir.
std::string ept::popcon::Path::popconIndexDir () static
Referenced by ept::popcon::PopconIndexer::rebuildIfNeeded().
std::string ept::popcon::Path::popconSourceDir () static
std::string ept::popcon::Path::popconUserIndexDir () static
std::string ept::popcon::Path::popconUserSourceDir () static
std::string ept::popcon::Path::scores () static
Referenced by ept::popcon::PopconIndexer::deleteRedundantUserIndex(), ept::popcon::PopconIndexer::getUpToDatePopcon(), ept::popcon::PopconIndexer::rebuildIfNeeded(), and ept::popcon::PopconIndexer::rescan().
std::string ept::popcon::Path::scoresIndex () static
Referenced by ept::popcon::PopconIndexer::deleteRedundantUserIndex(), ept::popcon::PopconIndexer::getUpToDatePopcon(), ept::popcon::PopconIndexer::rebuildIfNeeded(), and ept::popcon::PopconIndexer::rescan().
void ept::popcon::Path::setPopconIndexDir (const std::string & s) static
Referenced by ept::popcon::Path::OverridePopconIndexDir::OverridePopconIndexDir(), and ept::popcon::Path::OverridePopconIndexDir::~OverridePopconIndexDir().
void ept::popcon::Path::setPopconSourceDir (const std::string & s) static
Referenced by ept::popcon::Path::OverridePopconSourceDir::OverridePopconSourceDir(), and ept::popcon::Path::OverridePopconSourceDir::~OverridePopconSourceDir().
void ept::popcon::Path::setPopconUserIndexDir (const std::string & s) static
Referenced by ept::popcon::Path::OverridePopconUserIndexDir::OverridePopconUserIndexDir(), and ept::popcon::Path::OverridePopconUserIndexDir::~OverridePopconUserIndexDir().
void ept::popcon::Path::setPopconUserSourceDir (const std::string & s) static
Referenced by ept::popcon::Path::OverridePopconUserSourceDir::OverridePopconUserSourceDir(), and ept::popcon::Path::OverridePopconUserSourceDir::~OverridePopconUserSourceDir().
time_t ept::popcon::Path::timestamp (const std::string & file) static
std::string ept::popcon::Path::userScores () static
Referenced by ept::popcon::PopconIndexer::deleteRedundantUserIndex(), ept::popcon::PopconIndexer::getUpToDatePopcon(), ept::popcon::PopconIndexer::rebuildIfNeeded(), and ept::popcon::PopconIndexer::rescan().
std::string ept::popcon::Path::userScoresIndex () static
Referenced by ept::popcon::PopconIndexer::deleteRedundantUserIndex(), ept::popcon::PopconIndexer::getUpToDatePopcon(), ept::popcon::PopconIndexer::rebuildIfNeeded(), and ept::popcon::PopconIndexer::rescan().
Member Data Documentation
std::string ept::popcon::Path::m_popconIndexDir protected
std::string ept::popcon::Path::m_popconSourceDir protected
Referenced by instance().
std::string ept::popcon::Path::m_popconUserIndexDir protected
std::string ept::popcon::Path::m_popconUserSourceDir protected
Path * ept::popcon::Path::s_instance = 0 static protected
The documentation for this class was generated from the following files:
popcon/maint/path.h
popcon/maint/path.cc