libept: ept Namespace Reference
ept Namespace Reference
Namespaces
namespace apt
namespace axi
Maintains and accesses a Xapian index of package descriptions.
namespace debtags
namespace popcon
Classes
class ProgressCallback
struct Sources
struct Token
Functions
std::istream & operator>> (std::istream &i, Sources::Entry::Word &w)
std::istream & operator>> (std::istream &i, Sources::Entry &e)
std::ostream & operator<< (std::ostream &o, const Sources::Entry &e)
std::istream & operator>> (std::istream &i, Sources &s)
std::ostream & operator<< (std::ostream &o, const Sources &s)
Function Documentation
std::ostream& ept::operator<< (std::ostream & o, const Sources::Entry & e) inline
References ept::Sources::Entry::Comment, ept::Sources::Entry::comment(), ept::Sources::Entry::components(), ept::Sources::Entry::distribution(), ept::Sources::Entry::enabled(), ept::Sources::Entry::type(), ept::Sources::Entry::typeString(), and ept::Sources::Entry::url().
std::ostream& ept::operator<< (std::ostream & o, const Sources & s) inline
References ept::Sources::entries().
std::istream& ept::operator>> (std::istream & i, Sources::Entry::Word & w) inline
References ept::Sources::Entry::Word::s.
std::istream& ept::operator>> (std::istream & i, Sources::Entry & e) inline
References ept::Sources::Entry::Comment, ept::Sources::Entry::m_components, ept::Sources::Entry::m_dist, ept::Sources::Entry::m_url, ept::Sources::Entry::setComment(), ept::Sources::Entry::setEnabled(), ept::Sources::Entry::setType(), and ept::Sources::Entry::setTypeString().
std::istream& ept::operator>> (std::istream & i, Sources & s) inline
References ept::Sources::m_entries.