libept: ept::debtags::voc Namespace Reference
ept::debtags::voc Namespace Reference
Classes
struct Data
Base class for facet and tag data.
struct TagData
Representation of a tag.
class FacetData
Representation of a facet.
Functions
std::string getfacet (const std::string &tagname)
Extract the facet name from a tag name.
Function Documentation
std::string ept::debtags::voc::getfacet (const std::string & tagname)
Extract the facet name from a tag name.
Referenced by ept::debtags::Vocabulary::hasTag(), ept::debtags::Vocabulary::obtainTag(), and ept::debtags::Vocabulary::tagData().