libept: ept::axi Namespace Reference
ept::axi Namespace Reference
Maintains and accesses a Xapian index of package descriptions.
Classes
class OverrideIndexDir
RAII temporary override of the location of the index root directory, used for tests.
Functions
std::string path_dir ()
Return the path to the Apt Xapian index root directory.
std::string path_db ()
Return the path to the Apt Xapian index Xapian database.
time_t timestamp ()
Return the last update timestamp of the index.
Variables
const Xapian::valueno VAL_APT_INSTALLED_SIZE = 1
const Xapian::valueno VAL_APT_PACKAGE_SIZE = 2
const Xapian::valueno VAL_POPCON = 10
const Xapian::valueno VAL_ITERATING_RATING = 20
const Xapian::valueno VAL_ITERATING_FUNCTIONALITY = 21
const Xapian::valueno VAL_ITERATING_USABILITY = 22
const Xapian::valueno VAL_ITERATING_SECURITY = 23
const Xapian::valueno VAL_ITERATING_PERFORMANCE = 24
const Xapian::valueno VAL_ITERATING_QUALITY = 25
const Xapian::valueno VAL_ITERATING_SUPPORT = 26
const Xapian::valueno VAL_ITERATING_ADOPTION = 27
Detailed Description
Maintains and accesses a Xapian index of package descriptions.
Contrarily to Debtags and Popcon, TextSearch does not attempt to create the index in the home directory if no system index is found and it is not running as root: this is to avoid secretly building large indexes (>50Mb) in the home directory of users.
The idea then is to have root keep the index up to date, possibly running a reindexing tool once a day, or after an apt-get update.
This works because the full text search index is useful even if it is slightly out of date.
Function Documentation
std::string ept::axi::path_db ()
Return the path to the Apt Xapian index Xapian database.
std::string ept::axi::path_dir ()
Return the path to the Apt Xapian index root directory.
time_t ept::axi::timestamp ()
Return the last update timestamp of the index.
Referenced by TestAxi::empty(), ept::popcon::Local::Local(), ept::popcon::Popcon::Popcon(), ept::popcon::PopconIndexer::rebuildIfNeeded(), ept::popcon::PopconIndexer::rescan(), ept::debtags::SourceDir::tagTimestamp(), ept::debtags::SourceDir::timestamp(), ept::popcon::SourceDir::timestamp(), and ept::debtags::SourceDir::vocTimestamp().
Variable Documentation
const Xapian::valueno ept::axi::VAL_APT_INSTALLED_SIZE = 1
const Xapian::valueno ept::axi::VAL_APT_PACKAGE_SIZE = 2
const Xapian::valueno ept::axi::VAL_ITERATING_ADOPTION = 27
const Xapian::valueno ept::axi::VAL_ITERATING_FUNCTIONALITY = 21
const Xapian::valueno ept::axi::VAL_ITERATING_PERFORMANCE = 24
const Xapian::valueno ept::axi::VAL_ITERATING_QUALITY = 25
const Xapian::valueno ept::axi::VAL_ITERATING_RATING = 20
const Xapian::valueno ept::axi::VAL_ITERATING_SECURITY = 23
const Xapian::valueno ept::axi::VAL_ITERATING_SUPPORT = 26
const Xapian::valueno ept::axi::VAL_ITERATING_USABILITY = 22
const Xapian::valueno ept::axi::VAL_POPCON = 10