libept: ept::debtags::voc::Data Struct Reference
ept::debtags::voc::Data Struct Reference
Base class for facet and tag data.
#include <vocabulary.h>
Public Member Functions
std::string shortDescription () const
Return the short description of the tag.
std::string longDescription () const
Return the long description of the tag.
Public Attributes
std::string name
Protected Attributes
std::string m_desc
Detailed Description
Base class for facet and tag data.
Member Function Documentation
std::string ept::debtags::voc::Data::longDescription () const
Return the long description of the tag.
Exceptions:
std::out_of_range if the tag is not valid
Referenced by TestVocabulary::_9().
std::string ept::debtags::voc::Data::shortDescription () const
Return the short description of the tag.
Exceptions:
std::out_of_range if the tag is not valid
Referenced by TestVocabulary::_13(), and TestVocabulary::_9().
Member Data Documentation
std::string ept::debtags::voc::Data::m_desc mutable protected
std::string ept::debtags::voc::Data::name
Referenced by TestVocabulary::_13(), TestVocabulary::_6(), ept::debtags::Vocabulary::obtainFacet(), ept::debtags::voc::FacetData::obtainTag(), and ept::debtags::Vocabulary::read().
The documentation for this struct was generated from the following files:
vocabulary.h
vocabulary.cc