libept: ept::Sources::Entry Struct Reference
ept::Sources::Entry Struct Reference
#include <sources.h>
Classes
struct Word
Public Types
enum Type { Binary, Source, Comment }
typedef wibble::Range
< std::string > StringRange
typedef wibble::Consumer
< std::string > StringConsumer
typedef std::vector< std::string > StringVector
Public Member Functions
Entry (bool e=false, Type t=Comment, std::string u="", std::string d="", StringRange c=wibble::range(*new StringVector))
Entry (const Entry &e)
bool operator< (const Entry &o) const
bool operator== (const Entry &e) const
std::string components () const
void setComponents (const std::string &s)
std::string typeString () const
void setTypeString (const std::string &s)
std::string distribution () const
void setDistribution (const std::string &s)
std::string url () const
void setUrl (const std::string &s)
bool enabled () const
void setEnabled (bool e)
std::string comment () const
void setComment (const std::string &s)
Type type () const
void setType (Type t)
Protected Attributes
bool m_enabled
Type m_type
std::string m_url
std::string m_dist
StringVector m_components
std::string m_comment
Friends
std::istream & operator>> (std::istream &i, Entry &s)
Member Typedef Documentation
typedef wibble::Consumer< std::string > ept::Sources::Entry::StringConsumer
typedef wibble::Range< std::string > ept::Sources::Entry::StringRange
typedef std::vector< std::string > ept::Sources::Entry::StringVector
Member Enumeration Documentation
enum ept::Sources::Entry::Type
Enumerator:
Binary
Source
Comment
Constructor & Destructor Documentation
ept::Sources::Entry::Entry (bool e = false, Type t = Comment, std::string u = "", std::string d = "", StringRange c = wibble::range(*new StringVector)) inline
References m_components.
ept::Sources::Entry::Entry (const Entry & e) inline
References m_components.
Member Function Documentation
std::string ept::Sources::Entry::comment () const inline
References m_comment.
Referenced by operator<(), and ept::operator<<().
std::string ept::Sources::Entry::components () const inline
References m_components.
Referenced by operator<(), and ept::operator<<().
std::string ept::Sources::Entry::distribution () const inline
References m_dist.
Referenced by operator<(), and ept::operator<<().
bool ept::Sources::Entry::enabled () const inline
References m_enabled.
Referenced by operator<(), and ept::operator<<().
bool ept::Sources::Entry::operator< (const Entry & o) const inline
References comment(), components(), distribution(), enabled(), type(), and url().
bool ept::Sources::Entry::operator== (const Entry & e) const inline
void ept::Sources::Entry::setComment (const std::string & s) inline
References m_comment.
Referenced by ept::operator>>().
void ept::Sources::Entry::setComponents (const std::string & s) inline
References m_components.
void ept::Sources::Entry::setDistribution (const std::string & s) inline
References m_dist.
void ept::Sources::Entry::setEnabled (bool e) inline
References m_enabled.
Referenced by ept::operator>>(), and setType().
void ept::Sources::Entry::setType (Type t) inline
References Comment, m_type, and setEnabled().
Referenced by ept::operator>>(), and setTypeString().
void ept::Sources::Entry::setTypeString (const std::string & s) inline
References Binary, Comment, setType(), and Source.
Referenced by ept::operator>>().
void ept::Sources::Entry::setUrl (const std::string & s) inline
References m_url.
Type ept::Sources::Entry::type () const inline
References m_type.
Referenced by operator<(), ept::operator<<(), and typeString().
std::string ept::Sources::Entry::typeString () const inline
References Binary, Comment, Source, and type().
Referenced by ept::operator<<().
std::string ept::Sources::Entry::url () const inline
References m_url.
Referenced by operator<(), and ept::operator<<().
Friends And Related Function Documentation
std::istream& operator>> (std::istream & i, Sources::Entry & e) friend
Member Data Documentation
std::string ept::Sources::Entry::m_comment protected
Referenced by comment(), and setComment().
StringVector ept::Sources::Entry::m_components protected
Referenced by components(), Entry(), ept::operator>>(), and setComponents().
std::string ept::Sources::Entry::m_dist protected
Referenced by distribution(), ept::operator>>(), and setDistribution().
bool ept::Sources::Entry::m_enabled protected
Referenced by enabled(), and setEnabled().
Type ept::Sources::Entry::m_type protected
Referenced by setType(), and type().
std::string ept::Sources::Entry::m_url protected
Referenced by ept::operator>>(), setUrl(), and url().
The documentation for this struct was generated from the following file:
sources.h