libept: TestPopcon Struct Reference
TestPopcon Struct Reference
#include <popcon.test.h>
Public Member Functions
TestPopcon ()
Test basicAccess ()
Test accessibility ()
Test haveScores ()
Test validScores ()
Test fallbackValues ()
Public Attributes
popcon::Path::OverridePopconSourceDir odsd
popcon::Path::OverridePopconIndexDir odid
popcon::Path::OverridePopconUserSourceDir odusd
popcon::Path::OverridePopconUserIndexDir oduid
Apt apt
Popcon popcon
Constructor & Destructor Documentation
TestPopcon::TestPopcon () inline
Member Function Documentation
Test TestPopcon::accessibility () inline
Test TestPopcon::basicAccess () inline
Test TestPopcon::fallbackValues () inline
References ept::popcon::Popcon::hasData(), ept::popcon::Popcon::score(), ept::popcon::Popcon::size(), ept::popcon::Popcon::submissions(), and ept::popcon::Popcon::timestamp().
Test TestPopcon::haveScores () inline
Test TestPopcon::validScores () inline
Member Data Documentation
Apt TestPopcon::apt
popcon::Path::OverridePopconIndexDir TestPopcon::odid
popcon::Path::OverridePopconSourceDir TestPopcon::odsd
popcon::Path::OverridePopconUserIndexDir TestPopcon::oduid
popcon::Path::OverridePopconUserSourceDir TestPopcon::odusd
Popcon TestPopcon::popcon
The documentation for this struct was generated from the following file:
popcon.test.h