libept: TestApt Struct Reference
TestApt Struct Reference
#include <apt.test.h>
Public Member Functions
Test iterators ()
Test aptExists ()
Test timestamp ()
Test validity ()
Test versions ()
Test versionValidity ()
Test rawRecord ()
Test state ()
Test recordIteration ()
Test recordIteration2 ()
Test stlIteration ()
Test stlRecordIteration ()
Test checkUpdates ()
Public Member Functions inherited from AptTestEnvironment
AptTestEnvironment ()
Public Attributes
Apt apt
Member Function Documentation
Test TestApt::aptExists () inline
Test TestApt::checkUpdates () inline
Test TestApt::iterators () inline
Test TestApt::rawRecord () inline
References ept::apt::Version::isValid().
Test TestApt::recordIteration () inline
Test TestApt::recordIteration2 () inline
Test TestApt::state () inline
References ept::apt::PackageState::isInstalled(), and ept::apt::PackageState::isValid().
Test TestApt::stlIteration () inline
Test TestApt::stlRecordIteration () inline
Test TestApt::timestamp () inline
Test TestApt::validity () inline
Test TestApt::versions () inline
References ept::apt::Version::isValid().
Test TestApt::versionValidity () inline
Member Data Documentation
Apt TestApt::apt
The documentation for this struct was generated from the following file:
apt.test.h