libept: TestVocabulary Struct Reference
TestVocabulary Struct Reference
#include <vocabulary.test.h>
Public Member Functions
Vocabulary & tags ()
Test _1 ()
Test _2 ()
Test _3 ()
Test _4 ()
Test _5 ()
Test _6 ()
Test _7 ()
Test _8 ()
Test _9 ()
Test _10 ()
Test _11 ()
Test _12 ()
Test _13 ()
Test _14 ()
Test _15 ()
Test _16 ()
Test _17 ()
Test _18 ()
Test _19 ()
Test _20 ()
Test _21 ()
Public Member Functions inherited from DebtagsTestEnvironment
DebtagsTestEnvironment ()
Public Member Functions inherited from AptTestEnvironment
AptTestEnvironment ()
Public Attributes
Vocabulary m_tags
Public Attributes inherited from DebtagsTestEnvironment
ept::debtags::Path::OverrideDebtagsSourceDir odsd
ept::debtags::Path::OverrideDebtagsIndexDir odid
ept::debtags::Path::OverrideDebtagsUserSourceDir odusd
ept::debtags::Path::OverrideDebtagsUserIndexDir oduid
Member Function Documentation
Test TestVocabulary::_1 () inline
Test TestVocabulary::_10 () inline
Test TestVocabulary::_11 () inline
Test TestVocabulary::_12 () inline
Test TestVocabulary::_13 () inline
References ept::debtags::voc::Data::name, ept::debtags::voc::Data::shortDescription(), and ept::debtags::Vocabulary::tagData().
Test TestVocabulary::_14 () inline
Test TestVocabulary::_15 () inline
Test TestVocabulary::_16 () inline
Test TestVocabulary::_17 () inline
Test TestVocabulary::_18 () inline
Test TestVocabulary::_19 () inline
Test TestVocabulary::_2 () inline
Test TestVocabulary::_20 () inline
Test TestVocabulary::_21 () inline
References ept::debtags::Vocabulary::facets(), ept::debtags::Vocabulary::hasData(), and ept::debtags::Vocabulary::tags().
Test TestVocabulary::_3 () inline
Test TestVocabulary::_4 () inline
Test TestVocabulary::_5 () inline
Test TestVocabulary::_6 () inline
References ept::debtags::voc::Data::name.
Test TestVocabulary::_7 () inline
References ept::debtags::voc::FacetData::tags().
Test TestVocabulary::_8 () inline
Test TestVocabulary::_9 () inline
References ept::debtags::voc::Data::longDescription(), and ept::debtags::voc::Data::shortDescription().
Vocabulary& TestVocabulary::tags () inline
Member Data Documentation
Vocabulary TestVocabulary::m_tags
The documentation for this struct was generated from the following file:
vocabulary.test.h