libept: TestAptVersion Struct Reference
TestAptVersion Struct Reference
#include <version.test.h>
Public Member Functions
Test invalid ()
Test basic ()
Test comparison ()
Test valueCopy ()
Test upstreamVersion ()
Test policyComparison ()
Member Function Documentation
Test TestAptVersion::basic () inline
References ept::apt::Version::isValid(), ept::apt::Version::name(), and ept::apt::Version::version().
Test TestAptVersion::comparison () inline
Test TestAptVersion::invalid () inline
References ept::apt::Version::isValid(), ept::apt::Version::name(), and ept::apt::Version::version().
Test TestAptVersion::policyComparison () inline
Test TestAptVersion::upstreamVersion () inline
Test TestAptVersion::valueCopy () inline
The documentation for this struct was generated from the following file:
version.test.h