libept: ept::Token Struct Reference
ept::Token Struct Reference
#include <token.h>
Public Member Functions
std::string id () const
Token ()
Token (std::string s)
std::string version () const
std::string package () const
bool isDesktop () const
std::string desktop () const
bool hasVersion () const
bool valid () const
bool operator<= (const Token &o) const
Public Attributes
std::string _id
Constructor & Destructor Documentation
ept::Token::Token () inline
ept::Token::Token (std::string s) inline
Member Function Documentation
std::string ept::Token::desktop () const inline
References _id, and isDesktop().
bool ept::Token::hasVersion () const inline
References version().
std::string ept::Token::id () const inline
References _id.
Referenced by operator<<().
bool ept::Token::isDesktop () const inline
References _id.
Referenced by desktop().
bool ept::Token::operator<= (const Token & o) const inline
References _id.
std::string ept::Token::package () const inline
References _id.
bool ept::Token::valid () const inline
References _id.
std::string ept::Token::version () const inline
References _id.
Referenced by hasVersion().
Member Data Documentation
std::string ept::Token::_id
Referenced by desktop(), id(), isDesktop(), operator<=(), package(), valid(), and version().
The documentation for this struct was generated from the following file:
token.h