libept: TestAptPackagerecord Struct Reference
TestAptPackagerecord Struct Reference
#include <packagerecord.test.h>
Public Member Functions
Test supportedFields ()
Member Function Documentation
Test TestAptPackagerecord::supportedFields () inline
References ept::apt::PackageRecord::architecture(), ept::apt::PackageRecord::buildEssential(), ept::apt::PackageRecord::conflicts(), ept::apt::PackageRecord::depends(), ept::apt::PackageRecord::description(), ept::apt::PackageRecord::enhances(), ept::apt::PackageRecord::filename(), ept::apt::PackageRecord::installedSize(), ept::apt::PackageRecord::longDescription(), ept::apt::PackageRecord::maintainer(), ept::apt::PackageRecord::md5sum(), ept::apt::PackageRecord::package(), ept::apt::PackageRecord::packageSize(), ept::apt::PackageRecord::preDepends(), ept::apt::PackageRecord::priority(), ept::apt::PackageRecord::provides(), ept::apt::PackageRecord::recommends(), ept::apt::PackageRecord::replaces(), ept::apt::PackageRecord::section(), ept::apt::PackageRecord::sha1(), ept::apt::PackageRecord::sha256(), ept::apt::PackageRecord::shortDescription(), ept::apt::RecordParser::size(), ept::apt::PackageRecord::source(), ept::apt::PackageRecord::suggests(), ept::apt::PackageRecord::tag(), and ept::apt::PackageRecord::version().
The documentation for this struct was generated from the following file:
packagerecord.test.h