libept: ept::popcon::PopconIndexer Struct Reference
ept::popcon::PopconIndexer Struct Reference
#include <popconindexer.h>
Public Member Functions
time_t sourceTimestamp () const
bool needsRebuild () const
bool rebuild (const std::string &scofname, const std::string &idxfname)
bool rebuildIfNeeded ()
bool getUpToDatePopcon (std::string &scofname, std::string &idxfname)
bool userIndexIsRedundant () const
bool deleteRedundantUserIndex ()
void rescan ()
PopconIndexer ()
Static Public Member Functions
static bool obtainWorkingPopcon (std::string &scofname, std::string &idxfname)
Public Attributes
SourceDir mainSource
SourceDir userSource
time_t ts_main_src
time_t ts_user_src
time_t ts_main_sco
time_t ts_user_sco
time_t ts_main_idx
time_t ts_user_idx
Constructor & Destructor Documentation
ept::popcon::PopconIndexer::PopconIndexer ()
References rescan().
Member Function Documentation
bool ept::popcon::PopconIndexer::deleteRedundantUserIndex ()
References ept::popcon::Path::scores(), ept::popcon::Path::scoresIndex(), ts_user_idx, ts_user_sco, userIndexIsRedundant(), ept::popcon::Path::userScores(), and ept::popcon::Path::userScoresIndex().
Referenced by obtainWorkingPopcon().
bool ept::popcon::PopconIndexer::getUpToDatePopcon (std::string & scofname, std::string & idxfname)
References ept::popcon::Path::scores(), ept::popcon::Path::scoresIndex(), sourceTimestamp(), ts_main_idx, ts_main_sco, ts_user_idx, ts_user_sco, ts_user_src, ept::popcon::Path::userScores(), and ept::popcon::Path::userScoresIndex().
Referenced by obtainWorkingPopcon().
bool ept::popcon::PopconIndexer::needsRebuild () const
References sourceTimestamp(), ts_main_idx, ts_main_sco, ts_user_idx, ts_user_sco, and ts_user_src.
Referenced by rebuildIfNeeded().
bool ept::popcon::PopconIndexer::obtainWorkingPopcon (std::string & scofname, std::string & idxfname) static
References deleteRedundantUserIndex(), getUpToDatePopcon(), and rebuildIfNeeded().
bool ept::popcon::PopconIndexer::rebuild (const std::string & scofname, const std::string & idxfname)
References mainSource, ept::popcon::SourceDir::readScores(), ept::popcon::InfoStruct::submissions, and userSource.
Referenced by rebuildIfNeeded().
bool ept::popcon::PopconIndexer::rebuildIfNeeded ()
References ept::popcon::Path::access(), needsRebuild(), ept::popcon::Path::popconIndexDir(), rebuild(), ept::popcon::Path::scores(), ept::popcon::Path::scoresIndex(), ept::axi::timestamp(), ts_main_idx, ts_main_sco, ts_user_idx, ts_user_sco, ept::popcon::Path::userScores(), and ept::popcon::Path::userScoresIndex().
Referenced by obtainWorkingPopcon().
void ept::popcon::PopconIndexer::rescan ()
References mainSource, ept::popcon::Path::scores(), ept::popcon::Path::scoresIndex(), ept::popcon::SourceDir::timestamp(), ept::axi::timestamp(), ts_main_idx, ts_main_sco, ts_main_src, ts_user_idx, ts_user_sco, ts_user_src, ept::popcon::Path::userScores(), ept::popcon::Path::userScoresIndex(), and userSource.
Referenced by PopconIndexer().
time_t ept::popcon::PopconIndexer::sourceTimestamp () const inline
References ts_main_src, and ts_user_src.
Referenced by getUpToDatePopcon(), needsRebuild(), and userIndexIsRedundant().
bool ept::popcon::PopconIndexer::userIndexIsRedundant () const
References sourceTimestamp(), ts_main_idx, and ts_user_idx.
Referenced by deleteRedundantUserIndex().
Member Data Documentation
SourceDir ept::popcon::PopconIndexer::mainSource
Referenced by rebuild(), and rescan().
time_t ept::popcon::PopconIndexer::ts_main_idx
Referenced by getUpToDatePopcon(), needsRebuild(), rebuildIfNeeded(), rescan(), and userIndexIsRedundant().
time_t ept::popcon::PopconIndexer::ts_main_sco
Referenced by getUpToDatePopcon(), needsRebuild(), rebuildIfNeeded(), and rescan().
time_t ept::popcon::PopconIndexer::ts_main_src
Referenced by rescan(), and sourceTimestamp().
time_t ept::popcon::PopconIndexer::ts_user_idx
Referenced by deleteRedundantUserIndex(), getUpToDatePopcon(), needsRebuild(), rebuildIfNeeded(), rescan(), and userIndexIsRedundant().
time_t ept::popcon::PopconIndexer::ts_user_sco
Referenced by deleteRedundantUserIndex(), getUpToDatePopcon(), needsRebuild(), rebuildIfNeeded(), and rescan().
time_t ept::popcon::PopconIndexer::ts_user_src
Referenced by getUpToDatePopcon(), needsRebuild(), rescan(), and sourceTimestamp().
SourceDir ept::popcon::PopconIndexer::userSource
Referenced by rebuild(), and rescan().
The documentation for this struct was generated from the following files:
popconindexer.h
popconindexer.cc