libept: ept::apt::PackageState Struct Reference
ept::apt::PackageState Struct Reference
#include <apt.h>
Public Types
enum Query {
Install = 1 << 0, Upgrade = 1 << 1, Keep = 1 << 2, Remove = 1 << 3,
Installed = 1 << 4, Upgradable = 1 << 5, NowBroken = 1 << 6, WillBreak = 1 << 7,
ReInstall = 1 << 8, Purge = 1 << 9, Hold = 1 << 10, Valid = 1 << 11
}
typedef unsigned state
Public Member Functions
operator unsigned ()
PackageState & operator= (unsigned i)
PackageState & operator|= (const PackageState &s)
PackageState (unsigned a)
PackageState ()
bool isValid () const
bool isInstalled () const
bool install () const
bool reinstall () const
bool remove () const
bool purge () const
bool keep () const
bool willBreak () const
bool upgrade () const
bool newInstall () const
bool hold () const
bool installed () const
bool hasNewVersion () const
bool upgradable () const
bool held () const
bool nowBroken () const
bool modify () const
Protected Attributes
unsigned m_state
Member Typedef Documentation
typedef unsigned ept::apt::PackageState::state
Member Enumeration Documentation
enum ept::apt::PackageState::Query
Enumerator:
Install
Upgrade
Keep
Remove
Installed
Upgradable
NowBroken
WillBreak
ReInstall
Purge
Hold
Valid
Constructor & Destructor Documentation
ept::apt::PackageState::PackageState (unsigned a) inline
References m_state.
ept::apt::PackageState::PackageState () inline
Member Function Documentation
bool ept::apt::PackageState::hasNewVersion () const inline
References m_state, and Upgradable.
Referenced by held(), upgradable(), and upgrade().
bool ept::apt::PackageState::held () const inline
References hasNewVersion(), and hold().
bool ept::apt::PackageState::hold () const inline
References Hold, and m_state.
Referenced by held(), and upgradable().
bool ept::apt::PackageState::install () const inline
References Install, and m_state.
Referenced by modify(), newInstall(), and upgrade().
bool ept::apt::PackageState::installed () const inline
References Installed, and m_state.
Referenced by isInstalled(), and newInstall().
bool ept::apt::PackageState::isInstalled () const inline
References installed().
Referenced by TestApt::state().
bool ept::apt::PackageState::isValid () const inline
References m_state, and Valid.
Referenced by TestApt::state().
bool ept::apt::PackageState::keep () const inline
References Keep, and m_state.
bool ept::apt::PackageState::modify () const inline
References install().
bool ept::apt::PackageState::newInstall () const inline
References install(), and installed().
bool ept::apt::PackageState::nowBroken () const inline
References m_state, and NowBroken.
ept::apt::PackageState::operator unsigned () inline
References m_state.
PackageState& ept::apt::PackageState::operator= (unsigned i) inline
References m_state.
PackageState& ept::apt::PackageState::operator|= (const PackageState & s) inline
References m_state.
bool ept::apt::PackageState::purge () const inline
References m_state, and Purge.
bool ept::apt::PackageState::reinstall () const inline
References m_state, and ReInstall.
bool ept::apt::PackageState::remove () const inline
References m_state, and Remove.
bool ept::apt::PackageState::upgradable () const inline
References hasNewVersion(), and hold().
bool ept::apt::PackageState::upgrade () const inline
References hasNewVersion(), and install().
bool ept::apt::PackageState::willBreak () const inline
References m_state, and WillBreak.
Member Data Documentation
unsigned ept::apt::PackageState::m_state protected
Referenced by hasNewVersion(), hold(), install(), installed(), isValid(), keep(), nowBroken(), operator unsigned(), operator=(), operator|=(), PackageState(), purge(), reinstall(), remove(), and willBreak().
The documentation for this struct was generated from the following file:
apt.h