libept: TestDebtags Struct Reference
TestDebtags Struct Reference
#include <debtags.test.h>
Public Member Functions
TestDebtags ()
Test _1 ()
Test _2 ()
Test _3 ()
Test _4 ()
Test _5 ()
Public Member Functions inherited from DebtagsTestEnvironment
DebtagsTestEnvironment ()
Public Member Functions inherited from AptTestEnvironment
AptTestEnvironment ()
Public Attributes
Debtags debtags
Public Attributes inherited from DebtagsTestEnvironment
ept::debtags::Path::OverrideDebtagsSourceDir odsd
ept::debtags::Path::OverrideDebtagsIndexDir odid
ept::debtags::Path::OverrideDebtagsUserSourceDir odusd
ept::debtags::Path::OverrideDebtagsUserIndexDir oduid
Constructor & Destructor Documentation
TestDebtags::TestDebtags () inline
Member Function Documentation
Test TestDebtags::_1 () inline
Test TestDebtags::_2 () inline
Test TestDebtags::_3 () inline
Test TestDebtags::_4 () inline
Test TestDebtags::_5 () inline
References ept::debtags::Debtags::changes(), ept::debtags::Debtags::hasData(), ept::debtags::Debtags::outputPatched(), ept::debtags::Debtags::outputSystem(), and ept::debtags::Debtags::timestamp().
Member Data Documentation
Debtags TestDebtags::debtags
The documentation for this struct was generated from the following file:
debtags.test.h