libept: RunAll Struct Reference
RunAll Struct Reference
#include <test-runner.h>
Public Member Functions
RunSuite * findSuite (std::string name)
void waitForAck ()
void runSuite (RunSuite &s, int fromTest, int suite, int suiteCount)
void runFrom (int suite, int test)
Public Attributes
RunSuite * suites
int suiteCount
FILE * status
FILE * confirm
Member Function Documentation
RunSuite* RunAll::findSuite (std::string name) inline
References suiteCount, and suites.
Referenced by Main::child().
void RunAll::runFrom (int suite, int test) inline
References runSuite(), suiteCount, and suites.
Referenced by Main::child().
void RunAll::runSuite (RunSuite & s, int fromTest, int suite, int suiteCount) inline
References RunTest::name, RunSuite::name, RunTest::run, status, RunSuite::testCount, RunSuite::tests, and waitForAck().
Referenced by Main::child(), and runFrom().
void RunAll::waitForAck () inline
References confirm.
Referenced by runSuite().
Member Data Documentation
FILE * RunAll::confirm
Referenced by Main::child(), and waitForAck().
FILE* RunAll::status
Referenced by Main::child(), and runSuite().
int RunAll::suiteCount
Referenced by findSuite(), Main::main(), and runFrom().
RunSuite* RunAll::suites
Referenced by findSuite(), Main::main(), and runFrom().
The documentation for this struct was generated from the following file:
test-runner.h